from AttribsOutput import *
import re,string,xml.dom.minidom,sys

# CR.33769 This script used to generate an all inclusive file: LicenseError.cpp.
# Modified so that it now generates the file: LicenseError_py.cpp. Which is intended 
# to be wrapped by static code in LicenseError.cpp.
# All C++ function definitions have been removed from the script so changes 
# can happen directly in the source file vs here in the script.
#
# Note: The output filename base, LicenseError is actually defined in the 
# HReulstClass.xml file. If that were to change, then the output filename
# would be adjusted automatically. But it is unlikely to ever be changed.

def CreateComments(comments):
	if (len(comments)>0):
		comments = string.replace(comments,'*/','  ')
		comments = string.strip(comments)
		return "/*\n%s\n*/\n" % (comments,)
	return ''

def EscapeCStringLiteral(s):
	r=s
	r=string.replace(r,'\\','\\\\')
	r=string.replace(r,'\n','\\n')
	r=string.replace(r,'\t','\\t')
	r=string.replace(r,'"','\\"')
	r=string.replace(r,'\'','\\\'')
	return r
	
def EncodeBufferLiteral(s):
	return '<CBuffer><Size>%d</Size><Data>%s</Data></CBuffer>' % (len(s)/2,s[0:len(s)/2 * 2])

# outputs the c++ version of the hresults class source file
class HResultOutputCPP(AttribsOutput):
	def __init__(self):
		AttribsOutput.__init__(self)
	
	def ProcessXML(self, class_list):
		# for each attribs class
		for hresult_class in class_list.values():   
			self.GenerateGenericHResultsFile(hresult_class)

	# SLB 22.may.2025 CR.33769; Restructured output from this script. No longer defines general functions here.
	# Those get defined in checked in code. 
	def GenerateHResultsClass(self, hresults_class):
		class_text =  'namespace LicenseServerError\n'
		class_text += '{\n'


		class_text += '\t/*\n'
		class_text += '\t * SL_ERROR - Solimar License Error\n'
		class_text += '\t */\n'
		class_text += '\ttypedef struct _SL_ERROR\n'
		class_text += '\t{\n'
		class_text += '\t\tunsigned long	EC;\n'
		class_text += '\t\tHRESULT HR;\n'
		class_text += '\t\tconst wchar_t* message;\n'
		class_text += '\t} SL_ERROR;\n\n'

		class_text += '\t/*\n'
		class_text += '\t * SLErrors[]\n'
		class_text += '\t *\n'
		class_text += '\t * Licensing custom errors.\n'
		class_text += '\t */\n'
		class_text += '\tconst SL_ERROR SLErrors[] =\n'
		class_text += '\t{\n'
		class_text += '\t\t//----------------------------------------------------------------------------------------------\n'
		class_text += '\t\t// Error Code\t\t\t\t\t\tHRESULT\t\t\t\t\t\tMessage\n'
		class_text += '\t\t//----------------------------------------------------------------------------------------------\n\n'
		class_text += '\t\t// License server errors'
                
		#Custom HRESULTS
		for ordered_hresults in OutputOrderDictionaryValues(hresults_class['hresults']):
			i=0
			class_text += '\n'
			for hresult_group in ordered_hresults.values():
				if (i < len(ordered_hresults)-1):
					class_text += "\t\t{%s,\t\t\t\t\t\t%s,\t\t\t\t\t\tL\"%s\"},\n" % (hresult_group['ecode'], hresult_group['name'],hresult_group['alias'])
					i+=1

		class_text += '\t};\n\n'
		class_text += '\tconst unsigned long SL_ERROR_COUNT = sizeof(SLErrors) / sizeof(SL_ERROR);\n\n'

		#close namespace
		class_text += '}'
                                
		return class_text		
	
	def ComputeFilePath(self, filename_base):
		return self.ComputeFileName(filename_base)
	def ComputeFileName(self, filename_base):
		return filename_base + '_py.cpp'																					# CR.33769; modified.
	
	# SLB 22.may.2025 CR.33769; Removed code, from literal string, which included header files.
	# those header files are expected to be handled by the file (LicenseError.cpp) which wraps
	# this file.
	def GenerateGenericHResultsFile(self, hresults_class):
		# generate and write the header file text
		self.WriteFileIfDifferent(self.ComputeFilePath(hresults_class['filename']),     
														"""// File auto generated by HRESULTClassesCompiler.py\n\n%s\n""" %    
														(self.GenerateHResultsClass(hresults_class)))		
