from AttribsOutput import *
import re,string,xml.dom.minidom,sys

# CR.33769 This script used to generate an all inclusive file: LicenseError.h.
# Modified so that it now generates the file: LicenseError_py.h. Which is intended 
# to be wrapped by static code in LicenseError.h.
# All C++ function definitions have been removed from the script so changes 
# can happen directly in the source file vs here in the script.
#
# Note: The output filename base, LicenseError is actually defined in the 
# HReulstClass.xml file. If that were to change, then the output filename
# would be adjusted automatically. But it is unlikely to ever be changed.

def CreateComments(comments):
	if (len(comments)>0):
		comments = string.replace(comments,'*/','  ')
		comments = string.strip(comments)
		return "/*\n%s\n*/\n" % (comments,)
	return ''

def EscapeCStringLiteral(s):
    r=s
    r=string.replace(r,'\\','\\\\')
    r=string.replace(r,'\n','\\n')
    r=string.replace(r,'\t','\\t')
    r=string.replace(r,'"','\\"')
    r=string.replace(r,'\'','\\\'')
    return r
	
def EncodeBufferLiteral(s):
    return '<CBuffer><Size>%d</Size><Data>%s</Data></CBuffer>' % (len(s)/2,s[0:len(s)/2 * 2])

# outputs the c++ version of the hresults class header files
class HResultOutputH(AttribsOutput):
	def __init__(self):
		AttribsOutput.__init__(self)
	
	def ProcessXML(self, class_list):
		# for each attribs class
		for hresult_class in class_list.values():   
			self.GenerateGenericHResultsFile(hresult_class)
    

	# SLB 22.may.2025 CR.33769; Restructured output from this script. No longer defines general functions here.
	# Those get defined in checked in code. 
	def GenerateHResultsClass(self, hresults_class):
		# class declaration header

		class_text =  '{\n'
		class_text += '\t/* Custom Error Base   HR Error Codes should all offset from this base. */\n'
		
		# Offset defines
		for offset in OutputOrderDictionaryValues(hresults_class['offsets']):
			if (offset['base'] == 'HRESULT_BASE' or offset['base'] == ''):    #no hresult base for cpp file
				class_text += '\tconst unsigned long %s = %s;\n' % (offset['name'],offset['value'])
			else:
				class_text += '\tconst unsigned long %s = %s+%s;\n' % (offset['name'],offset['base'],offset['value'])

		# Rainbow Error Codes
		class_text += '\n#ifndef SP_ACCESS_DENIED\t//RAINBOW API Error Codes\n'
		for rnbo in OutputOrderDictionaryValues(hresults_class['rnbos']):
			if (rnbo['name'] != 'SP_INVALID_STATUS'):
				class_text += '\tconst unsigned long %s = %s;\n' % (rnbo['name'],rnbo['value'])
		class_text += '#endif\n'

		class_text += '\n'
		class_text += '\t//07-01-11 - JWL\n'
		class_text += '\t//Note: This is a rainbow error that is not defined in current 3rd party .h file.\n'
		class_text += '\t//If receive a new .h file and receive an error because it is already defined, move\n'
		class_text += '\t//this above.\n'
		class_text += '\tconst unsigned long SP_INVALID_STATUS = 255;\n'


		#Custom HRESULTS
		for ordered_hresults in OutputOrderDictionaryValues(hresults_class['hresults']):
			i=0
			class_text += '\n'                  
			for hresult_group in ordered_hresults.values():
				if (i==0):
					if hresult_group['offset'] == 'ITF_LIC_SVR_OFFSET' :
						class_text += '\t/* Error Codes used for custom HRESULTs. */\n'
					else :
						class_text += '\t// Rainbow driver errors\n'
				if (i < len(ordered_hresults)-1):
					class_text += "\tconst unsigned long %s = %s+%s;\n" % (hresult_group['ecode'], hresult_group['offset'],hresult_group['value'])
					i+=1                  

		#HRESULTS defines
		class_text += '\n\t/* HRESULTS defined from custom error codes above. */'
		for ordered_hresults in OutputOrderDictionaryValues(hresults_class['hresults']):
			i=0
			class_text += '\n'
			for hresult_group in ordered_hresults.values():
				if (i < len(ordered_hresults)-1):
					class_text += "\tconst HRESULT %s = MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, %s);\n" % (hresult_group['name'], hresult_group['ecode'])
					i+=1

                
		return class_text		
	
	def ComputeFilePath(self, filename_base):
		return self.ComputeFileName(filename_base)
	def ComputeFileName(self, filename_base):
		return filename_base + '_py.h'																					# CR.33769; modified.
	
	# SLB 22.may.2025 CR.33769; Removed code, from literal string, which included header files.
	# those header files are expected to be handled by the file (LicenseError.h) which wraps
	# this file.
	def GenerateGenericHResultsFile(self, hresults_class): #include <string>\n\n
		# generate and write the header file text
		self.WriteFileIfDifferent(self.ComputeFilePath(hresults_class['filename']),     
                                          """// File auto generated by HRESULTClassesCompiler.py\n#pragma once\n\nnamespace LicenseServerError\n%s}\n\n""" %  
                                          (self.GenerateHResultsClass(hresults_class)))
			

		

	


