// ILicensingMessage.h : Declaration of the ILicensingMessage interface
// This interface is used to facilitate verifying the integrity and authenticity 
// of the code behind a COM proxy
// 
// SLB 09.sep.2025 CR.34426; conditionally uses the Attributes definition for the 
// interface definition or the header file generated by the MIDL compiler (default).
#pragma once

#include <objbase.h>																						// CR.32662; added.
#include <comdef.h>																						// CR.32662; added.
#include <comsvcs.h>																						// CR.32662; added.
#include <atlbase.h>																						// CR.32662; added.
#include <atlcom.h>																						// CR.32662; added.
#include <atlsafe.h>																						// CR.32662; added.
#include <atlctl.h>																						// CR.32662; added.
#include <comutil.h>																						// CR.32662; added.

#ifndef _LIC_ATL_ATTRIBUTES																			// CR.34426; added.
// Most projects will use this.
#include "_SSILicenseInterfaces.h"																	// CR.34426; added.
#else																											// CR.34426; added.

// CR.34426; ATL Attributes code is specifically for the ATL COM implementation 
// files (eg SolimarLicenseMgr.cpp) and the SSILicenseInterfaces project.

// ILicensingMessage
[
	object,
	uuid("025336D2-0EF1-4dab-9126-E8ACD750FFE5"),
	dual,	helpstring("ILicensingMessage Interface"),
	pointer_default(unique)
]
__interface ILicensingMessage : IDispatch
{
	// Message/Event support
	[id(4),helpstring("method GetLicenseMessageList")] HRESULT GetLicenseMessageList([in] VARIANT_BOOL clear_messages, [out,retval] VARIANT *pvtMessageList);
	[id(5),helpstring("method DispatchLicenseMessageList")] HRESULT DispatchLicenseMessageList([in] VARIANT_BOOL clear_messages);
};

#endif