// IObjectAuthentication.h : Declaration of the IObjectAuthentication interface
// 
// This interface is used to facilitate verifying the integrity and authenticity of 
// the code behind a COM proxy 
// 
// SLB 09.sep.2025 CR.34426; conditionally uses the Attributes definition for the 
// interface definition or the header file generated by the MIDL compiler (default).

#pragma once

#ifndef _LIC_ATL_ATTRIBUTES																			// CR.34426; added.
// Most projects will use this.
#include "_SSILicenseInterfaces.h"																	// CR.34426; added.
#else																											// CR.34426; added.

// CR.34426; ATL Attributes code is specifically for the ATL COM implementation 
// files (eg SolimarLicenseMgr.cpp) and the SSILicenseInterfaces project.

// IObjectAuthentication
[
	object,
	uuid("779FE092-038A-43c2-8F99-5F4974D14997"),
	dual,	helpstring("IObjectAuthentication Interface"),
	pointer_default(unique)
]
__interface IObjectAuthentication : IDispatch
{
	// Client authenticates Server.
	[id(1),helpstring("method Challenge")] HRESULT Challenge([in] VARIANT vtChallenge, [out,retval] VARIANT *pvtResponse);
	// Server authenticates Client.
	[id(2),helpstring("method GetChallenge")] HRESULT GetChallenge([out,retval] VARIANT *pvtChallenge);
	[id(3),helpstring("method PutResponse")] HRESULT PutResponse([in] VARIANT vtResponse);
};


#endif