// ISoftwareLicensingMessage.h : Declaration of the ISoftwareLicensingMessage interface
//
// SLB 09.sep.2025 CR.34426; conditionally uses the Attributes definition for the 
// interface definition or the header file generated by the MIDL compiler (default).
#pragma once

#ifndef _LIC_ATL_ATTRIBUTES																			// CR.34426; added.
// Most projects will use this.
#include "_SSILicenseInterfaces.h"																	// CR.34426; added.
#else																											// CR.34426; added.

// CR.34426; ATL Attributes code is specifically for the ATL COM implementation 
// files (eg SolimarLicenseMgr.cpp) and the SSILicenseInterfaces project.

// ISoftwareLicensingMessage
[
	object,
	uuid("817EA560-B5F3-4f63-9AD5-3AE239849C68"),
	dual,	helpstring("ISoftwareLicensingMessage Interface"),
	pointer_default(unique)
]
__interface ISoftwareLicensingMessage : IDispatch
{
	// Software License Message/Event support
	[id(4),helpstring("method GetSoftwareLicenseMessageList")] HRESULT GetSoftwareLicenseMessageList([in] VARIANT_BOOL clear_messages, [out,retval] VARIANT *pvtMessageList);
	[id(5),helpstring("method DispatchSoftwareLicenseMessageList")] HRESULT DispatchSoftwareLicenseMessageList([in] VARIANT_BOOL clear_messages);
};

#endif