// ISolimarLicenseSvr.h : Declaration of the ISolimarLicenseSvr interface
// 
// SLB 31.dec.2024 CR.32662; created. Split the ISolimarLicenseSvr interface definition
// out of the SolimarLicenseSvr.h file.
// SLB 09.sep.2025 CR.34426; conditionally uses the Attributes definition for the 
// interface definition or the header file generated by the MIDL compiler (default).

#pragma once
#include <objbase.h>
#include <comdef.h>
#include <comsvcs.h>
#include <atlbase.h>
#include <atlcom.h>
#include <atlsafe.h>
#include <atlctl.h>
#include <comutil.h>

const GUID CLSID_CSolimarLicenseSvr = {0x4735A522,0x8C07,0x46D0,{0xBA,0x08,0x68,0xBF,0xF2,0xB1,0xB3,0xA6}};

#ifndef _LIC_ATL_ATTRIBUTES																			// CR.34426; added.
// Most projects will use this.
#include "_SSILicenseInterfaces.h"																	// CR.34426; added.
#else																											// CR.34426; added.

// CR.34426; ATL Attributes code is specifically for the ATL COM implementation 
// files (eg SolimarLicenseMgr.cpp) and the SSILicenseInterfaces project.

// ISolimarLicenseSvr
[
	object,
		uuid("C6CCE857-1A24-41D5-A44C-4DC629CD370D"),
		dual, helpstring("ISolimarLicenseSvr Interface"),
		pointer_default(unique)
]
__interface ISolimarLicenseSvr : IDispatch
{
	// Top level functions
	[id(1), helpstring("method Heartbeat")] HRESULT Heartbeat();
	[id(2), helpstring("method KeyEnumerate")] HRESULT KeyEnumerate([out, retval] VARIANT* keylist);
	[id(3), helpstring("method EnterPassword")] HRESULT EnterPassword([in] BSTR password);
	[id(4), helpstring("method EnterPasswordPacket")] HRESULT EnterPasswordPacket([in] VARIANT vtPasswordPacket, [out, retval] BSTR* verification_code);
	[id(5), helpstring("method GenerateBasePassword")] HRESULT GenerateBasePassword([in] long customer_number, [in] long key_number, [out, retval] BSTR* password);
	[id(6), helpstring("method GenerateVersionPassword")] HRESULT GenerateVersionPassword([in] long customer_number, [in] long key_number, [in] long ver_major, [in] long ver_minor, [out, retval] BSTR* password);
	[id(7), helpstring("method GenerateExtensionPassword")] HRESULT GenerateExtensionPassword([in] long customer_number, [in] long key_number, [in] long extend_days, [in] long extension_num, [out, retval] BSTR* password);
	[id(8), helpstring("method GenerateModulePassword")] HRESULT GenerateModulePassword([in] long customer_number, [in] long key_number, [in] long product_ident, [in] long module_ident, [in] long license_count, [out, retval] BSTR* password);
	[id(9), helpstring("method GetLicenseServerTime")] HRESULT GetLicenseServerTime([out, retval] VARIANT* pvtSystemTime);
	[id(10), helpstring("method GenerateModulePassword2")] HRESULT GenerateModulePassword2([in] long customer_number, [in] long key_number, [in] long product_ident, [in] long module_ident, [in] long license_count, [in] long password_number, [out, retval] BSTR* password);

	// Password packet management
	[id(20), helpstring("method PasswordPacketInitialize")] HRESULT PasswordPacketInitialize();
	[id(21), helpstring("method PasswordPacketAppendPassword")] HRESULT PasswordPacketAppendPassword([in] VARIANT vtExpires, [in] BSTR password);
	[id(22), helpstring("method PasswordPacketFinalize")] HRESULT PasswordPacketFinalize();
	[id(23), helpstring("method PasswordPacketGetPacket")] HRESULT PasswordPacketGetPacket([out, retval] VARIANT* pvtPacketData);
	[id(24), helpstring("method PasswordPacketGetVerificationCode")] HRESULT PasswordPacketGetVerificationCode([out, retval] BSTR* verification_code);

	// Key specific functions
	[id(32), helpstring("method KeyTrialExpires")] HRESULT KeyTrialExpires([in] BSTR key_ident, [out, retval] VARIANT* expire_date);
	[id(33), helpstring("method KeyTrialHours")] HRESULT KeyTrialHours([in] BSTR key_ident, [out, retval] long* trial_hours);
	[id(34), helpstring("method KeyIsActive")] HRESULT KeyIsActive([in] BSTR key_ident, [out, retval] VARIANT_BOOL* key_active);
	[id(35), helpstring("method KeyIsProgrammed")] HRESULT KeyIsProgrammed([in] BSTR key_ident, [out, retval] VARIANT_BOOL* key_programmed);
	[id(36), helpstring("method KeyIsPresent")] HRESULT KeyIsPresent([in] BSTR key_ident, [out, retval] VARIANT_BOOL* key_present);
	[id(37), helpstring("method KeyHeaderQuery")] HRESULT KeyHeaderQuery([in] BSTR key_ident, [in] long header_ident, [out, retval] VARIANT* value);

	// License locking support
	// locking a key prevents it from being used by others until it is unlocked
	[id(41), helpstring("method KeyLock")] HRESULT KeyLock([in] BSTR key_ident);
	[id(42), helpstring("method KeyUnlock")] HRESULT KeyUnlock([in] BSTR key_ident);
	// indicates that if the key is trial, to start using up hours until it is released
	[id(43), helpstring("method KeyObtain")] HRESULT KeyObtain([in] BSTR key_ident);
	[id(44), helpstring("method KeyRelease")] HRESULT KeyRelease([in] BSTR key_ident);

	// Module information and locking
	[id(50), helpstring("method KeyValidateLicense")] HRESULT KeyValidateLicense([in] BSTR key_ident, [out, retval] VARIANT_BOOL* license_valid);
	[id(51), helpstring("method KeyModuleEnumerate")] HRESULT KeyModuleEnumerate([in] BSTR key_ident, [out, retval] VARIANT* key_module_list);
	[id(52), helpstring("method KeyModuleQuery")] HRESULT KeyModuleQuery([in] BSTR key_ident, [in] long module_identifier, [out, retval] VARIANT* vtValue);
	[id(53), helpstring("method KeyModuleLicenseTotal")] HRESULT KeyModuleLicenseTotal([in] BSTR key_ident, [in] long module_ident, [out, retval] long* license_count);
	[id(54), helpstring("method KeyModuleLicenseInUse")] HRESULT KeyModuleLicenseInUse([in] BSTR key_ident, [in] long module_ident, [out, retval] long* license_count);
	[id(55), helpstring("method KeyModuleLicenseObtain")] HRESULT KeyModuleLicenseObtain([in] BSTR key_ident, [in] long module_ident, [in] long license_count);
	[id(56), helpstring("method KeyModuleLicenseRelease")] HRESULT KeyModuleLicenseRelease([in] BSTR key_ident, [in] long module_ident, [in] long license_count);
	[id(57), helpstring("method KeyModuleLicenseCounterDecrement")] HRESULT KeyModuleLicenseCounterDecrement([in] BSTR key_ident, [in] long module_ident, [in] long license_count);

	// Key Programming/Creator support
	// Sets all writable cells on a key to zero
	[id(60), helpstring("method KeyFormat")] HRESULT KeyFormat([in] BSTR key_ident, [out, retval] BSTR* new_key_ident);
	// Programs a key
	[id(61), helpstring("method KeyProgram")] HRESULT KeyProgram([in] BSTR key_ident, [in] long customer_number, [in] long key_number, [in] long product_ident, [in] long ver_major, [in] long ver_minor, [in] long key_type, [in] long days, [in] VARIANT module_value_list, [out, retval] BSTR* new_key_ident);
	// Reads raw data off the key
	[id(62), helpstring("method KeyReadRaw")] HRESULT KeyReadRaw([in] BSTR key_ident, [out, retval] VARIANT* pvtKeyData);

};

// ISolimarLicenseSvr2
[
	object,
		uuid("4852B206-97BA-4934-AFD8-35E85F7FC855"),
		dual, helpstring("ISolimarLicenseSvr2 Interface"),
		pointer_default(unique)
]
__interface ISolimarLicenseSvr2 : ISolimarLicenseSvr
{
	[id(70), helpstring("method KeyModuleLicenseInUse2")] HRESULT KeyModuleLicenseInUse2([in] BSTR key_ident, [in] long module_ident, [out, retval] long* license_count);
	[id(71), helpstring("method KeyModuleInUse")] HRESULT KeyModuleInUse([in] BSTR key_ident, [in] long module_ident, [out, retval] long* license_count);
};

// ISolimarLicenseSvr3
[
	object,
		uuid("BDA195D0-FC1A-4814-9DE0-364394D8D810"),
		dual, helpstring("ISolimarLicenseSvr3 Interface"),
		pointer_default(unique)
]
__interface ISolimarLicenseSvr3 : ISolimarLicenseSvr2
{
	[id(72), helpstring("method GenerateApplicationInstancePassword")] HRESULT GenerateApplicationInstancePassword([in] long customer_number, [in] long key_number, [in] long license_count, [in] long password_number, [out, retval] BSTR* password);
	// Programs a key
	[id(73), helpstring("method KeyProgram2")] HRESULT KeyProgram2([in] BSTR key_ident, [in] long customer_number, [in] long key_number, [in] long product_ident, [in] long ver_major, [in] long ver_minor, [in] long key_type, [in] long application_instances, [in] long days, [in] VARIANT module_value_list, [out, retval] BSTR* new_key_ident);
	// Gets the Version of the License Server
	[id(74), helpstring("method GetVersionLicenseServer")] HRESULT GetVersionLicenseServer([out] long* p_ver_major, [out] long* p_ver_minor, [out] long* p_ver_build);
	[id(75), helpstring("method AddApplicationInstance")] HRESULT AddApplicationInstance([in] BSTR key_ident, [in] BSTR application_instance, [in] VARIANT_BOOL b_app_instance_lock_key);
	[id(76), helpstring("method RemoveApplicationInstance")] HRESULT RemoveApplicationInstance([in] BSTR key_ident, [in] BSTR application_instance);
	[id(77), helpstring("method GetApplicationInstanceList")] HRESULT GetApplicationInstanceList([in] BSTR key_ident, [out, retval] VARIANT* pvtAppInstanceList);

	// Sets to treat the Module License as Unlimited
	[id(78), helpstring("method KeyModuleLicenseUnlimited")] HRESULT KeyModuleLicenseUnlimited([in] BSTR key_ident, [in] long module_ident, [in] VARIANT_BOOL b_module_is_unlimited);
};

// ISolimarLicenseSvr4
[
	object,
		uuid("70C717AC-46ED-44d8-B0EF-AFCCC63DC98E"),
		dual, helpstring("ISolimarLicenseSvr4 Interface"),
		pointer_default(unique)
]
__interface ISolimarLicenseSvr4 : ISolimarLicenseSvr3
{
	[id(79), helpstring("method KeyModuleLicenseInUse_ByApp")] HRESULT KeyModuleLicenseInUse_ByApp([in] BSTR key_ident, [in] long module_ident, [out, retval] long* license_count);
};

#endif
