// ISolimarSoftwareLicenseSvr.h : Declaration of the ISolimarSoftwareLicenseSvr
// 
// SLB 31.dec.2024 CR.32662; created. Split the ISolimarLicenseSvr interface definition
// out of the SolimarLicenseSvr.h file.
// SLB 09.sep.2025 CR.34426; conditionally uses the Attributes definition for the 
// interface definition or the header file generated by the MIDL compiler (default).

#pragma once

#include <objbase.h>
#include <comdef.h>
#include <comsvcs.h>
#include <atlbase.h>
#include <atlcom.h>
#include <atlsafe.h>
#include <atlctl.h>
#include <comutil.h>

#ifndef _LIC_ATL_ATTRIBUTES																			// CR.34426; added.
// Most projects will use this.
#include "_SSILicenseInterfaces.h"																	// CR.34426; added.
#else																											// CR.34426; added.

// CR.34426; ATL Attributes code is specifically for the ATL COM implementation 
// files (eg SolimarLicenseMgr.cpp) and the SSILicenseInterfaces project.

// ISolimarSoftwareLicenseSvr
[
	object,
		uuid("7FFD4EEB-DC7A-43f0-9117-667D77EF93A2"),
		dual, helpstring("ISolimarSoftwareLicenseSvr Interface"),
		pointer_default(unique)
]
__interface ISolimarSoftwareLicenseSvr : IDispatch
{
	[id(80), helpstring("method SoftwareModuleLicenseTotalForAll_ByProduct")] HRESULT SoftwareModuleLicenseTotalForAll_ByProduct([in] long productID, [in] long moduleIdent, [out, retval] long* pLicenseCount);
	[id(81), helpstring("method SoftwareModuleLicenseInUseForAll_ByProduct")] HRESULT SoftwareModuleLicenseInUseForAll_ByProduct([in] long productID, [in] long moduleIdent, [out, retval] long* pLicenseCount);
	[id(82), helpstring("method SoftwareValidateLicenseApp_ByProduct")] HRESULT SoftwareValidateLicenseApp_ByProduct([in] long productID, [out, retval] VARIANT_BOOL* pbLicenseValid);
	[id(83), helpstring("method SoftwareModuleLicenseInUseByApp_ByProduct")] HRESULT SoftwareModuleLicenseInUseByApp_ByProduct([in] long productID, [in] long moduleIdent, [out, retval] long* pLicenseCount);
	[id(84), helpstring("method SoftwareModuleLicenseInUseByConnection_ByProduct")] HRESULT SoftwareModuleLicenseInUseByConnection_ByProduct([in] long productID, [in] long moduleIdent, [out, retval] long* pLicenseCount);
	[id(85), helpstring("method SoftwareModuleLicenseObtainByApp_ByProduct")] HRESULT SoftwareModuleLicenseObtainByApp_ByProduct([in] long productID, [in] long moduleIdent, [in] long licenseCount);
	[id(86), helpstring("method SoftwareModuleLicenseReleaseByApp_ByProduct")] HRESULT SoftwareModuleLicenseReleaseByApp_ByProduct([in] long productID, [in] long moduleIdent, [in] long licenseCount);
	[id(87), helpstring("method SoftwareModuleLicenseCounterDecrementByApp_ByProduct")] HRESULT SoftwareModuleLicenseCounterDecrementByApp_ByProduct([in] long productID, [in] long moduleIdent, [in] long licenseCount);

	[id(88), helpstring("method GetSoftwareLicenseInfoByProduct_ForAll")] HRESULT GetSoftwareLicenseInfoByProduct_ForAll([in] long productID, [out, retval] BSTR* pBstrProductInfoAttribsStream);
	[id(89), helpstring("method GetSoftwareLicenseInfo_ForAll")] HRESULT GetSoftwareLicenseInfo_ForAll([out, retval] BSTR* pBstrLicenseInfoAttribsStream);

	[id(90), helpstring("method GetAllSoftwareLicenses")] HRESULT GetAllSoftwareLicenses([out, retval] BSTR* pBstrListAllLicensesStream);
	[id(91), helpstring("method GetSoftwareLicenseInfoByProduct_ByLicense")] HRESULT GetSoftwareLicenseInfoByProduct_ByLicense([in] BSTR softwareLicense, [in] long productID, [out, retval] BSTR* pBstrProductInfoAttribsStream);
	[id(92), helpstring("method GetSoftwareLicenseInfo_ByLicense")] HRESULT GetSoftwareLicenseInfo_ByLicense([in] BSTR softwareLicense, [out, retval] BSTR* pBstrLicenseInfoAttribsStream);

	[id(93), helpstring("method GetSoftwareLicenseStatus_ByProduct")] HRESULT GetSoftwareLicenseStatus_ByProduct([in] long productID, [out, retval] BSTR* pBstrStringToDwordMap);
	[id(94), helpstring("method GetSoftwareLicenseStatus_ByLicense")] HRESULT GetSoftwareLicenseStatus_ByLicense([in] BSTR softwareLicense);

	[id(95), helpstring("method GetSoftwareSpecByProduct")] HRESULT GetSoftwareSpecByProduct([in] long productID, [out, retval] BSTR* pBstrProductSoftwareSpecAttribs);
	[id(96), helpstring("method GetSoftwareSpec")] HRESULT GetSoftwareSpec([out, retval] BSTR* pBstrSoftwareSpecAttribsStream);

	[id(97), helpstring("method SoftwareAddApplicationInstanceByProduct")] HRESULT SoftwareAddApplicationInstanceByProduct([in] long productID, [in] BSTR applicationInstance);
	[id(98), helpstring("method SoftwareRemoveApplicationInstanceByProduct")] HRESULT SoftwareRemoveApplicationInstanceByProduct([in] long productID, [in] BSTR applicationInstance);
	[id(99), helpstring("method SoftwareGetApplicationInstanceListByProduct")] HRESULT SoftwareGetApplicationInstanceListByProduct([in] long productID, [out, retval] BSTR* pBstrListAppInstStream);

	[id(100), helpstring("method GenerateSoftwareLicPacket")] HRESULT GenerateSoftwareLicPacket([in] BSTR bstrLicPackageAttribsStream, [in] VARIANT vtExpires, [out] BSTR* pBstrVerificationCode, [out, retval] VARIANT* pVtLicensePacket);
	[id(101), helpstring("method EnterSoftwareLicPacket")] HRESULT EnterSoftwareLicPacket([in] VARIANT vtLicensePacket, [out, retval] BSTR* pBstrVerificationCode);

	[id(102), helpstring("method ValidateToken_ByLicense")] HRESULT ValidateToken_ByLicense([in] BSTR softwareLicense, [in] long validationTokenType, [in] BSTR validationValue);

	[id(103), helpstring("method SoftwareLicenseUseActivationToExtendTime_ByLicenseAndContractNumber")] HRESULT SoftwareLicenseUseActivationToExtendTime_ByLicenseAndContractNumber([in] BSTR softwareLicense, [in] BSTR contractNumber);

	[id(104), helpstring("method GenerateVerifyDataWithVerCode_ByLicense")] HRESULT GenerateVerifyDataWithVerCode_ByLicense([in] BSTR softwareLicense, [out, retval] VARIANT* pVtLicensePacket);
	[id(105), helpstring("method GenerateVerifyDataWithLicInfo_ByLicense")] HRESULT GenerateVerifyDataWithLicInfo_ByLicense([in] BSTR softwareLicense, [out, retval] VARIANT* pVtLicensePacket);
	[id(106), helpstring("method GenerateSoftwareLicArchive_ByLicense")] HRESULT GenerateSoftwareLicArchive_ByLicense([in] BSTR softwareLicense, [out, retval] VARIANT* pVtLicenseArchive);
	[id(107), helpstring("method GenerateLicPackage_ByVerifyData")] HRESULT GenerateLicPackage_ByVerifyData([in] VARIANT vtLicensePacket, [out, retval] BSTR* pBstrLicensePackageAttribsStream);
	[id(108), helpstring("method GenerateLicPackage_BySoftwareLicArchive")] HRESULT GenerateLicPackage_BySoftwareLicArchive([in] VARIANT vtLicenseArchive, [out, retval] BSTR* pBstrLicensePackageAttribsStream);
	[id(109), helpstring("method GenerateLicPackage_BySoftwareLicPacket")] HRESULT GenerateLicPackage_BySoftwareLicPacket([in] VARIANT vtLicensePacket, [out, retval] BSTR* pBstrLicensePackageAttribsStream);
	[id(110), helpstring("method EnterSoftwareLicArchive")] HRESULT EnterSoftwareLicArchive([in] VARIANT vtLicenseArchive);
	[id(111), helpstring("method GenerateLicenseSystemData")] HRESULT GenerateLicenseSystemData([out, retval] VARIANT* pVtLicSysDataPacket);
	[id(112), helpstring("method GenerateStream_ByLicenseSystemData")] HRESULT GenerateStream_ByLicenseSystemData([in] VARIANT vtLicSysDataPacket, [out, retval] BSTR* pBstrLicSysDataAttribsStream);
	[id(113), helpstring("method GenerateStreamData_ByLicenseSystemData")] HRESULT GenerateStreamData_ByLicenseSystemData([in] VARIANT vtLicSysDataPacket, [out] BSTR* pBstrCreatedDateStreamed, [out] BSTR* pBstrKeyAttribsListStream, [out] BSTR* pBstrLicUsageDataAttribsStream, [out] BSTR* pBstrConnectionAttribsListStream, [out] BSTR* pBstrEventLogAttribsListStream, [out, retval] BSTR* pBstrLicInfoDataAttribsListStream);
	[id(114), helpstring("method GetEventLogEntries_ForLicenseServer")] HRESULT GetEventLogList_ForLicenseServer([out, retval] BSTR* pBstrEventLogAttribsListStream);
};

// ISolimarSoftwareLicenseSvr2
[
	object,
		uuid("3295BF3C-D692-435a-86AF-DC559094FD86"),
		dual, helpstring("ISolimarSoftwareLicenseSvr2 Interface"),
		pointer_default(unique)
]
__interface ISolimarSoftwareLicenseSvr2 : ISolimarSoftwareLicenseSvr
{
	[id(115), helpstring("method SoftwareAddApplicationInstanceByProduct2")] HRESULT SoftwareAddApplicationInstanceByProduct2([in] long productID, [in] BSTR applicationInstance, [in] long flags);
	[id(116), helpstring("method SoftwareGetApplicationInstanceListByProduct2")] HRESULT SoftwareGetApplicationInstanceListByProduct2([in] long productID, [out, retval] BSTR* pBstrListUsAppInstInfoAttribs);
};

// ISolimarSoftwareLicenseSvr3
[
	object,
		uuid("0C0E18D9-DB58-49bf-8049-491601DFD84E"),
		dual, helpstring("ISolimarSoftwareLicenseSvr3 Interface"),
		pointer_default(unique)
]
__interface ISolimarSoftwareLicenseSvr3 : ISolimarSoftwareLicenseSvr2
{
	[id(125), helpstring("method GenerateStreamData_ByLicenseSystemData2")] HRESULT GenerateStreamData_ByLicenseSystemData2([in] VARIANT vtLicSysDataPacket, [out] BSTR* pBstrCreatedDateStreamed, [out] BSTR* pBstrKeyAttribsListStream, [out] BSTR* pBstrLicUsageDataAttribsStream, [out] BSTR* pBstrConnectionAttribsListStream, [out] BSTR* pBstrEventLogAttribsListStream, [out] BSTR* pBstrLicInfoDataAttribsListStream, [out, retval] BSTR* pBstrLicAlertInfoAttribs);
	[id(126), helpstring("method GenerateLicenseSystemDataForSolimar")] HRESULT GenerateLicenseSystemDataForSolimar();
};


#endif
