// ISolimarLicenseEmailAlert.h : Declaration of the ISolimarLicenseEmailAlert interface.
// 
// SLB 31.dec.2024 CR.32662; created. Split the ISolimarLicenseEmailAlert interface definition
// out of the SolimarLicenseSvr.h file.
// SLB 09.sep.2025 CR.34426; conditionally uses the Attributes definition for the 
// interface definition or the header file generated by the MIDL compiler (default).

#pragma once
#include <objbase.h>
#include <comdef.h>
#include <comsvcs.h>
#include <atlbase.h>
#include <atlcom.h>
#include <atlsafe.h>
#include <atlctl.h>
#include <comutil.h>

#ifndef _LIC_ATL_ATTRIBUTES																			// CR.34426; added.
// Most projects will use this.
#include "_SSILicenseInterfaces.h"																	// CR.34426; added.
#else																											// CR.34426; added.

// CR.34426; ATL Attributes code is specifically for the ATL COM implementation 
// files (eg SolimarLicenseMgr.cpp) and the SSILicenseInterfaces project.

// ISolimarLicenseEmailAlert
[
	object,
		uuid("64BF79C5-F816-439d-80D6-EBB7296BC803"),
		dual, helpstring("ISolimarLicenseEmailAlert Interface"),
		pointer_default(unique)
]
__interface ISolimarLicenseEmailAlert : IDispatch
{
	[id(117), helpstring("method GetMailServerInfo")] HRESULT GetMailServerInfo([out, retval] BSTR* pBstrAlertMailServerAttribsStream);
	[id(118), helpstring("method SetMailServerInfo")] HRESULT SetMailServerInfo([in] BSTR bstrAlertMailServerAttribsStream);
	[id(119), helpstring("method TestMailServerInfo")] HRESULT TestMailServerInfo([in] BSTR bstrTestMailServerAttribsStream);
	[id(120), helpstring("method GetAllEmailAlerts")] HRESULT GetAllEmailAlerts([out, retval] BSTR* pBstrEmailAlertMailAttribsListStream);
	[id(121), helpstring("method GetEmailAlert")] HRESULT GetEmailAlert([in] BSTR bstrEmailAlertId, [out, retval] BSTR* pBstrEmailAlertMailAttribsStream);
	[id(122), helpstring("method SetEmailAlert")] HRESULT SetEmailAlert([in] BSTR bstrEmailAlertId, [in] BSTR bstrEmailAlertMailAttribsStream);
	[id(123), helpstring("method AddEmailAlert")] HRESULT AddEmailAlert([in] BSTR bstrEmailAlertMailAttribsStream, [out, retval] BSTR* pBstrEmailAlertId);
	[id(124), helpstring("method DeleteEmailAlert")] HRESULT DeleteEmailAlert([in] BSTR bstrEmailAlertId);
};


#endif
