// LicenseError.h
#pragma once

#include <windows.h>
#include <string>

// Include declarations/definitions generated by the python script 
// HResultClassesCompiler.py.
#include "LicenseError_py.h"																			// CR.33679; added.

namespace LicenseServerError
{

	/*
	 * GetErrorMessage should be used by programs to translate error HRESULTS
	 */
	std::wstring GetErrorMessage(HRESULT hr);
	std::wstring GetECMessage(unsigned long echr);

	/*
	 * GenerateErrorMessage should be used by programs to translate error HRESULTS
	 */
	std::wstring GenerateErrorMessage(
		HRESULT hr, 
		std::wstring wsHeaderMsg = L"", 
		bool bAppendExistingErrorInfo = true);

	/*
	 * SAVE_ERRORINFO, RESTORE_ERRORINFO
	 * Helper macros to save and restore IErrorInfo objects in return blocks.
	 * For instance, if a COM object is released between a COM error occurring, 
	 * and returning an errored hr from a function, the IErrorInfo object may 
	 * be cleared (similar to the lasterror for Win32 calls). Use these
	 * macros to help store the IErrorInfo during COM cleanup, and then
	 *restore IErrorInfo before returning.
	 */
#define SAVE_ERRORINFO \
	IErrorInfo* save_error_info = NULL; \
	GetErrorInfo(0, &save_error_info); \
	if (save_error_info) \
		SetErrorInfo(0, save_error_info);
#define RESTORE_ERRORINFO \
	if (save_error_info) \
	{ \
		SetErrorInfo(0, save_error_info); \
		save_error_info->Release(); \
	}

	HRESULT WriteEventLog(const wchar_t *event_log_msg, unsigned int event_type, long event_id);
	HRESULT WriteEventLog(const wchar_t *event_log_msg, unsigned int event_type, long event_id, long product_id);
	HRESULT TReadEventLog();

	/*
	 * LIC_PROPAGATE_CUSTOM_ERROR()
	 *
	 * Pulls the error message from a given HR, and sets the
	 * calling objects ISupportErrorInfo with the information.
	 * This macro can be used to easily propagate error info
	 * from object to object within Licensing.
	 * 
	 * SLB 21.may.2025 CR.33769; Fix for not passing a true BSTR to AtlReportError().
	 */
#define LIC_PROPAGATE_CUSTOM_ERROR(hr, clsid, iid) \
	if (FAILED(hr)) \
		AtlReportError((clsid), CComBSTR(LicenseServerError::GetErrorMessage(hr).c_str()), (iid), (hr));

#define LIC_PROPAGATE_CUSTOM_ERROR_MESSAGE(hr, wsMsg, clsid, iid) \
	if (FAILED(hr)) \
		AtlReportError((clsid), CComBSTR(wsMsg.c_str()), (iid), (hr));


	/*
	* SL_IS_LIC_HR()
	*
	* Determine if hr is a Lic HR
	*/

	#define SL_IS_LIC_HR(hr) \
		(((hr) & 0x0000F000) == ITF_LIC_MIN)
	/*
	* SL_EC_FROM_EHR()
	*
	* Extracts the error code portion from an HRESULT.
	*/
	#define SL_EC_FROM_EHR(hr) \
		((hr) & 0x0000FFFF)
}

