//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Creator.CreatorService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TokenTable", Namespace="http://schemas.datacontract.org/2004/07/CreatorData")]
    [System.SerializableAttribute()]
    public partial class TokenTable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LicenseIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte TokenTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte TokenStatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LicenseID {
            get {
                return this.LicenseIDField;
            }
            set {
                if ((this.LicenseIDField.Equals(value) != true)) {
                    this.LicenseIDField = value;
                    this.RaisePropertyChanged("LicenseID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte TokenType {
            get {
                return this.TokenTypeField;
            }
            set {
                if ((this.TokenTypeField.Equals(value) != true)) {
                    this.TokenTypeField = value;
                    this.RaisePropertyChanged("TokenType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TokenValue {
            get {
                return this.TokenValueField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenValueField, value) != true)) {
                    this.TokenValueField = value;
                    this.RaisePropertyChanged("TokenValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int CustID {
            get {
                return this.CustIDField;
            }
            set {
                if ((this.CustIDField.Equals(value) != true)) {
                    this.CustIDField = value;
                    this.RaisePropertyChanged("CustID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public byte TokenStatus {
            get {
                return this.TokenStatusField;
            }
            set {
                if ((this.TokenStatusField.Equals(value) != true)) {
                    this.TokenStatusField = value;
                    this.RaisePropertyChanged("TokenStatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DestinationNameTable", Namespace="http://schemas.datacontract.org/2004/07/CreatorData")]
    [System.SerializableAttribute()]
    public partial class DestinationNameTable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DestIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DestNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int CustID {
            get {
                return this.CustIDField;
            }
            set {
                if ((this.CustIDField.Equals(value) != true)) {
                    this.CustIDField = value;
                    this.RaisePropertyChanged("CustID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int DestID {
            get {
                return this.DestIDField;
            }
            set {
                if ((this.DestIDField.Equals(value) != true)) {
                    this.DestIDField = value;
                    this.RaisePropertyChanged("DestID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string DestName {
            get {
                return this.DestNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DestNameField, value) != true)) {
                    this.DestNameField = value;
                    this.RaisePropertyChanged("DestName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PermissionsTable", Namespace="http://schemas.datacontract.org/2004/07/CreatorData")]
    [System.SerializableAttribute()]
    public partial class PermissionsTable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pt_loginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> pt_create_modify_keyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> pt_extension_pwdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> pt_version_pwdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> pt_module_pwdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> pt_permanent_pwdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pt_login {
            get {
                return this.pt_loginField;
            }
            set {
                if ((object.ReferenceEquals(this.pt_loginField, value) != true)) {
                    this.pt_loginField = value;
                    this.RaisePropertyChanged("pt_login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.Nullable<bool> pt_create_modify_key {
            get {
                return this.pt_create_modify_keyField;
            }
            set {
                if ((this.pt_create_modify_keyField.Equals(value) != true)) {
                    this.pt_create_modify_keyField = value;
                    this.RaisePropertyChanged("pt_create_modify_key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Nullable<bool> pt_extension_pwd {
            get {
                return this.pt_extension_pwdField;
            }
            set {
                if ((this.pt_extension_pwdField.Equals(value) != true)) {
                    this.pt_extension_pwdField = value;
                    this.RaisePropertyChanged("pt_extension_pwd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<bool> pt_version_pwd {
            get {
                return this.pt_version_pwdField;
            }
            set {
                if ((this.pt_version_pwdField.Equals(value) != true)) {
                    this.pt_version_pwdField = value;
                    this.RaisePropertyChanged("pt_version_pwd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<bool> pt_module_pwd {
            get {
                return this.pt_module_pwdField;
            }
            set {
                if ((this.pt_module_pwdField.Equals(value) != true)) {
                    this.pt_module_pwdField = value;
                    this.RaisePropertyChanged("pt_module_pwd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.Nullable<bool> pt_permanent_pwd {
            get {
                return this.pt_permanent_pwdField;
            }
            set {
                if ((this.pt_permanent_pwdField.Equals(value) != true)) {
                    this.pt_permanent_pwdField = value;
                    this.RaisePropertyChanged("pt_permanent_pwd");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductTable", Namespace="http://schemas.datacontract.org/2004/07/CreatorData")]
    [System.SerializableAttribute()]
    public partial class ProductTable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int pIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int pVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int pId {
            get {
                return this.pIdField;
            }
            set {
                if ((this.pIdField.Equals(value) != true)) {
                    this.pIdField = value;
                    this.RaisePropertyChanged("pId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int pVersion {
            get {
                return this.pVersionField;
            }
            set {
                if ((this.pVersionField.Equals(value) != true)) {
                    this.pVersionField = value;
                    this.RaisePropertyChanged("pVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string pName {
            get {
                return this.pNameField;
            }
            set {
                if ((object.ReferenceEquals(this.pNameField, value) != true)) {
                    this.pNameField = value;
                    this.RaisePropertyChanged("pName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PacketTable", Namespace="http://schemas.datacontract.org/2004/07/CreatorData")]
    [System.SerializableAttribute()]
    public partial class PacketTable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateCreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PacketVerificationCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsVerifiedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PacketCommentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PacketNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LicenseIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ExpiredDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VerifiedByField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime DateCreated {
            get {
                return this.DateCreatedField;
            }
            set {
                if ((this.DateCreatedField.Equals(value) != true)) {
                    this.DateCreatedField = value;
                    this.RaisePropertyChanged("DateCreated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string PacketVerificationCode {
            get {
                return this.PacketVerificationCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PacketVerificationCodeField, value) != true)) {
                    this.PacketVerificationCodeField = value;
                    this.RaisePropertyChanged("PacketVerificationCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool IsVerified {
            get {
                return this.IsVerifiedField;
            }
            set {
                if ((this.IsVerifiedField.Equals(value) != true)) {
                    this.IsVerifiedField = value;
                    this.RaisePropertyChanged("IsVerified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string PacketComments {
            get {
                return this.PacketCommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.PacketCommentsField, value) != true)) {
                    this.PacketCommentsField = value;
                    this.RaisePropertyChanged("PacketComments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string PacketName {
            get {
                return this.PacketNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PacketNameField, value) != true)) {
                    this.PacketNameField = value;
                    this.RaisePropertyChanged("PacketName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int LicenseID {
            get {
                return this.LicenseIDField;
            }
            set {
                if ((this.LicenseIDField.Equals(value) != true)) {
                    this.LicenseIDField = value;
                    this.RaisePropertyChanged("LicenseID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public System.DateTime ExpiredDate {
            get {
                return this.ExpiredDateField;
            }
            set {
                if ((this.ExpiredDateField.Equals(value) != true)) {
                    this.ExpiredDateField = value;
                    this.RaisePropertyChanged("ExpiredDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string VerifiedBy {
            get {
                return this.VerifiedByField;
            }
            set {
                if ((object.ReferenceEquals(this.VerifiedByField, value) != true)) {
                    this.VerifiedByField = value;
                    this.RaisePropertyChanged("VerifiedBy");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransactionTable", Namespace="http://schemas.datacontract.org/2004/07/CreatorData")]
    [System.SerializableAttribute()]
    public partial class TransactionTable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte taTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string taDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string taUnitsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime taDateCreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string taUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> taPacketIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int taLicenseIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> taOrderIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte taType {
            get {
                return this.taTypeField;
            }
            set {
                if ((this.taTypeField.Equals(value) != true)) {
                    this.taTypeField = value;
                    this.RaisePropertyChanged("taType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string taDescription {
            get {
                return this.taDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.taDescriptionField, value) != true)) {
                    this.taDescriptionField = value;
                    this.RaisePropertyChanged("taDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string taUnits {
            get {
                return this.taUnitsField;
            }
            set {
                if ((object.ReferenceEquals(this.taUnitsField, value) != true)) {
                    this.taUnitsField = value;
                    this.RaisePropertyChanged("taUnits");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime taDateCreated {
            get {
                return this.taDateCreatedField;
            }
            set {
                if ((this.taDateCreatedField.Equals(value) != true)) {
                    this.taDateCreatedField = value;
                    this.RaisePropertyChanged("taDateCreated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string taUser {
            get {
                return this.taUserField;
            }
            set {
                if ((object.ReferenceEquals(this.taUserField, value) != true)) {
                    this.taUserField = value;
                    this.RaisePropertyChanged("taUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.Nullable<int> taPacketID {
            get {
                return this.taPacketIDField;
            }
            set {
                if ((this.taPacketIDField.Equals(value) != true)) {
                    this.taPacketIDField = value;
                    this.RaisePropertyChanged("taPacketID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int taLicenseID {
            get {
                return this.taLicenseIDField;
            }
            set {
                if ((this.taLicenseIDField.Equals(value) != true)) {
                    this.taLicenseIDField = value;
                    this.RaisePropertyChanged("taLicenseID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public System.Nullable<int> taOrderID {
            get {
                return this.taOrderIDField;
            }
            set {
                if ((this.taOrderIDField.Equals(value) != true)) {
                    this.taOrderIDField = value;
                    this.RaisePropertyChanged("taOrderID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderTable", Namespace="http://schemas.datacontract.org/2004/07/CreatorData")]
    [System.SerializableAttribute()]
    public partial class OrderTable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte OrderStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LicenseIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ExpirationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParentOrderNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderIndex {
            get {
                return this.OrderIndexField;
            }
            set {
                if ((this.OrderIndexField.Equals(value) != true)) {
                    this.OrderIndexField = value;
                    this.RaisePropertyChanged("OrderIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderNumber {
            get {
                return this.OrderNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderNumberField, value) != true)) {
                    this.OrderNumberField = value;
                    this.RaisePropertyChanged("OrderNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte OrderState {
            get {
                return this.OrderStateField;
            }
            set {
                if ((this.OrderStateField.Equals(value) != true)) {
                    this.OrderStateField = value;
                    this.RaisePropertyChanged("OrderState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int LicenseID {
            get {
                return this.LicenseIDField;
            }
            set {
                if ((this.LicenseIDField.Equals(value) != true)) {
                    this.LicenseIDField = value;
                    this.RaisePropertyChanged("LicenseID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.Nullable<System.DateTime> ExpirationDate {
            get {
                return this.ExpirationDateField;
            }
            set {
                if ((this.ExpirationDateField.Equals(value) != true)) {
                    this.ExpirationDateField = value;
                    this.RaisePropertyChanged("ExpirationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string ProductVersion {
            get {
                return this.ProductVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductVersionField, value) != true)) {
                    this.ProductVersionField = value;
                    this.RaisePropertyChanged("ProductVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string ParentOrderNumber {
            get {
                return this.ParentOrderNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentOrderNumberField, value) != true)) {
                    this.ParentOrderNumberField = value;
                    this.RaisePropertyChanged("ParentOrderNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerTable", Namespace="http://schemas.datacontract.org/2004/07/CreatorData")]
    [System.SerializableAttribute()]
    public partial class CustomerTable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SCRnumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SCRnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SCRoperatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Client.Creator.CreatorService.LicenseTable> LicenseTablesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SCRnumber {
            get {
                return this.SCRnumberField;
            }
            set {
                if ((this.SCRnumberField.Equals(value) != true)) {
                    this.SCRnumberField = value;
                    this.RaisePropertyChanged("SCRnumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string SCRname {
            get {
                return this.SCRnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SCRnameField, value) != true)) {
                    this.SCRnameField = value;
                    this.RaisePropertyChanged("SCRname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string SCRoperator {
            get {
                return this.SCRoperatorField;
            }
            set {
                if ((object.ReferenceEquals(this.SCRoperatorField, value) != true)) {
                    this.SCRoperatorField = value;
                    this.RaisePropertyChanged("SCRoperator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public System.Collections.Generic.List<Client.Creator.CreatorService.LicenseTable> LicenseTables {
            get {
                return this.LicenseTablesField;
            }
            set {
                if ((object.ReferenceEquals(this.LicenseTablesField, value) != true)) {
                    this.LicenseTablesField = value;
                    this.RaisePropertyChanged("LicenseTables");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LicenseTable", Namespace="http://schemas.datacontract.org/2004/07/CreatorData")]
    [System.SerializableAttribute()]
    public partial class LicenseTable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SCRnumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DestinationIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GroupIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LicenseNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte LicenseTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LicenseInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LicenseCommentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Client.Creator.CreatorService.TransactionTable> TransactionTablesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Client.Creator.CreatorService.OrderTable> OrderTablesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Client.Creator.CreatorService.TokenTable> TokenTablesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Client.Creator.CreatorService.PacketTable> PacketTablesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SCRnumber {
            get {
                return this.SCRnumberField;
            }
            set {
                if ((this.SCRnumberField.Equals(value) != true)) {
                    this.SCRnumberField = value;
                    this.RaisePropertyChanged("SCRnumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int DestinationID {
            get {
                return this.DestinationIDField;
            }
            set {
                if ((this.DestinationIDField.Equals(value) != true)) {
                    this.DestinationIDField = value;
                    this.RaisePropertyChanged("DestinationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int GroupID {
            get {
                return this.GroupIDField;
            }
            set {
                if ((this.GroupIDField.Equals(value) != true)) {
                    this.GroupIDField = value;
                    this.RaisePropertyChanged("GroupID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string LicenseName {
            get {
                return this.LicenseNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LicenseNameField, value) != true)) {
                    this.LicenseNameField = value;
                    this.RaisePropertyChanged("LicenseName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public byte LicenseType {
            get {
                return this.LicenseTypeField;
            }
            set {
                if ((this.LicenseTypeField.Equals(value) != true)) {
                    this.LicenseTypeField = value;
                    this.RaisePropertyChanged("LicenseType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string LicenseInfo {
            get {
                return this.LicenseInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.LicenseInfoField, value) != true)) {
                    this.LicenseInfoField = value;
                    this.RaisePropertyChanged("LicenseInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string LicenseComments {
            get {
                return this.LicenseCommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.LicenseCommentsField, value) != true)) {
                    this.LicenseCommentsField = value;
                    this.RaisePropertyChanged("LicenseComments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int OrderIndex {
            get {
                return this.OrderIndexField;
            }
            set {
                if ((this.OrderIndexField.Equals(value) != true)) {
                    this.OrderIndexField = value;
                    this.RaisePropertyChanged("OrderIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public System.Collections.Generic.List<Client.Creator.CreatorService.TransactionTable> TransactionTables {
            get {
                return this.TransactionTablesField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionTablesField, value) != true)) {
                    this.TransactionTablesField = value;
                    this.RaisePropertyChanged("TransactionTables");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public System.Collections.Generic.List<Client.Creator.CreatorService.OrderTable> OrderTables {
            get {
                return this.OrderTablesField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderTablesField, value) != true)) {
                    this.OrderTablesField = value;
                    this.RaisePropertyChanged("OrderTables");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public System.Collections.Generic.List<Client.Creator.CreatorService.TokenTable> TokenTables {
            get {
                return this.TokenTablesField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenTablesField, value) != true)) {
                    this.TokenTablesField = value;
                    this.RaisePropertyChanged("TokenTables");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public System.Collections.Generic.List<Client.Creator.CreatorService.PacketTable> PacketTables {
            get {
                return this.PacketTablesField;
            }
            set {
                if ((object.ReferenceEquals(this.PacketTablesField, value) != true)) {
                    this.PacketTablesField = value;
                    this.RaisePropertyChanged("PacketTables");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Condition", Namespace="http://schemas.datacontract.org/2004/07/Service.Creator")]
    [System.SerializableAttribute()]
    public partial class Condition : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.Creator.CreatorService.Name ConditionNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.Creator.CreatorService.Operator ConditionOperatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConditionValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.Creator.CreatorService.Name ConditionName {
            get {
                return this.ConditionNameField;
            }
            set {
                if ((this.ConditionNameField.Equals(value) != true)) {
                    this.ConditionNameField = value;
                    this.RaisePropertyChanged("ConditionName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.Creator.CreatorService.Operator ConditionOperator {
            get {
                return this.ConditionOperatorField;
            }
            set {
                if ((this.ConditionOperatorField.Equals(value) != true)) {
                    this.ConditionOperatorField = value;
                    this.RaisePropertyChanged("ConditionOperator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConditionValue {
            get {
                return this.ConditionValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ConditionValueField, value) != true)) {
                    this.ConditionValueField = value;
                    this.RaisePropertyChanged("ConditionValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Name", Namespace="http://schemas.datacontract.org/2004/07/Service.Creator")]
    public enum Name : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Customer = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DestinationID = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GroupID = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LicenseType = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Operator", Namespace="http://schemas.datacontract.org/2004/07/Service.Creator")]
    public enum Operator : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Equals = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LessThan = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GreaterThan = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CreatorService.ICreator")]
    public interface ICreator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/UpdateToken", ReplyAction="http://tempuri.org/ICreator/UpdateTokenResponse")]
        void UpdateToken(Client.Creator.CreatorService.TokenTable ta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/DeleteToken", ReplyAction="http://tempuri.org/ICreator/DeleteTokenResponse")]
        void DeleteToken(Client.Creator.CreatorService.TokenTable ta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/GetDestNamesByCustID", ReplyAction="http://tempuri.org/ICreator/GetDestNamesByCustIDResponse")]
        System.Collections.Generic.List<Client.Creator.CreatorService.DestinationNameTable> GetDestNamesByCustID(int custID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/GetDestinationName", ReplyAction="http://tempuri.org/ICreator/GetDestinationNameResponse")]
        Client.Creator.CreatorService.DestinationNameTable GetDestinationName(int custID, int destID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/GetDestinationID", ReplyAction="http://tempuri.org/ICreator/GetDestinationIDResponse")]
        Client.Creator.CreatorService.DestinationNameTable GetDestinationID(int custID, string destName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/GetNextDestinationID", ReplyAction="http://tempuri.org/ICreator/GetNextDestinationIDResponse")]
        uint GetNextDestinationID(uint custID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/CreateDestinationName", ReplyAction="http://tempuri.org/ICreator/CreateDestinationNameResponse")]
        void CreateDestinationName(Client.Creator.CreatorService.DestinationNameTable destName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/UpdateDestinationName", ReplyAction="http://tempuri.org/ICreator/UpdateDestinationNameResponse")]
        void UpdateDestinationName(Client.Creator.CreatorService.DestinationNameTable destName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/DeleteDestinationName", ReplyAction="http://tempuri.org/ICreator/DeleteDestinationNameResponse")]
        void DeleteDestinationName(Client.Creator.CreatorService.DestinationNameTable destName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/GetPermissionsByUser", ReplyAction="http://tempuri.org/ICreator/GetPermissionsByUserResponse")]
        Client.Creator.CreatorService.PermissionsTable GetPermissionsByUser(string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/GetProducts", ReplyAction="http://tempuri.org/ICreator/GetProductsResponse")]
        System.Collections.Generic.List<Client.Creator.CreatorService.ProductTable> GetProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/GetProduct", ReplyAction="http://tempuri.org/ICreator/GetProductResponse")]
        Client.Creator.CreatorService.ProductTable GetProduct(string product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/UpdateProductTable", ReplyAction="http://tempuri.org/ICreator/UpdateProductTableResponse")]
        void UpdateProductTable(Client.Creator.CreatorService.ProductTable product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/GetPacketByVerificationCode", ReplyAction="http://tempuri.org/ICreator/GetPacketByVerificationCodeResponse")]
        Client.Creator.CreatorService.PacketTable GetPacketByVerificationCode(string verificationCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/ValidateVerificationCode", ReplyAction="http://tempuri.org/ICreator/ValidateVerificationCodeResponse")]
        bool ValidateVerificationCode(string packetName, string verificationCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/GenerateLicInfoByVerifyData", ReplyAction="http://tempuri.org/ICreator/GenerateLicInfoByVerifyDataResponse")]
        string GenerateLicInfoByVerifyData(ref byte[] byteVerifyData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/CreatePacket", ReplyAction="http://tempuri.org/ICreator/CreatePacketResponse")]
        void CreatePacket(Client.Creator.CreatorService.PacketTable packet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/UpdatePacket", ReplyAction="http://tempuri.org/ICreator/UpdatePacketResponse")]
        void UpdatePacket(Client.Creator.CreatorService.PacketTable packet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/DeletePacket", ReplyAction="http://tempuri.org/ICreator/DeletePacketResponse")]
        void DeletePacket(Client.Creator.CreatorService.PacketTable packet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/GetTransactionsByPacketID", ReplyAction="http://tempuri.org/ICreator/GetTransactionsByPacketIDResponse")]
        System.Collections.Generic.List<Client.Creator.CreatorService.TransactionTable> GetTransactionsByPacketID(int packetID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/GetNewTransactionsByLicenseName", ReplyAction="http://tempuri.org/ICreator/GetNewTransactionsByLicenseNameResponse")]
        System.Collections.Generic.List<Client.Creator.CreatorService.TransactionTable> GetNewTransactionsByLicenseName(string licenseName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/UpdateSubLicenseTransactionsByOrder", ReplyAction="http://tempuri.org/ICreator/UpdateSubLicenseTransactionsByOrderResponse")]
        void UpdateSubLicenseTransactionsByOrder(int stdLicOrderID, int subLicOrderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/CreateTransaction", ReplyAction="http://tempuri.org/ICreator/CreateTransactionResponse")]
        void CreateTransaction(Client.Creator.CreatorService.TransactionTable ta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/UpdateTransaction", ReplyAction="http://tempuri.org/ICreator/UpdateTransactionResponse")]
        void UpdateTransaction(Client.Creator.CreatorService.TransactionTable ta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/DeleteTransaction", ReplyAction="http://tempuri.org/ICreator/DeleteTransactionResponse")]
        void DeleteTransaction(Client.Creator.CreatorService.TransactionTable ta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/GetAllOrders", ReplyAction="http://tempuri.org/ICreator/GetAllOrdersResponse")]
        System.Collections.Generic.List<Client.Creator.CreatorService.OrderTable> GetAllOrders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/GetOrdersByLicenseName", ReplyAction="http://tempuri.org/ICreator/GetOrdersByLicenseNameResponse")]
        System.Collections.Generic.List<Client.Creator.CreatorService.OrderTable> GetOrdersByLicenseName(string licenseName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/GetOrdersEqualsProduct", ReplyAction="http://tempuri.org/ICreator/GetOrdersEqualsProductResponse")]
        System.Collections.Generic.List<Client.Creator.CreatorService.OrderTable> GetOrdersEqualsProduct(string licenseName, string productName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/GetAddOnOrdersByStandardOrder", ReplyAction="http://tempuri.org/ICreator/GetAddOnOrdersByStandardOrderResponse")]
        System.Collections.Generic.List<string> GetAddOnOrdersByStandardOrder(string standardOrder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/GetOrderByOrderName", ReplyAction="http://tempuri.org/ICreator/GetOrderByOrderNameResponse")]
        Client.Creator.CreatorService.OrderTable GetOrderByOrderName(string orderName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/GetNextOrderIndex", ReplyAction="http://tempuri.org/ICreator/GetNextOrderIndexResponse")]
        int GetNextOrderIndex(string licenseName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/GetProductVersionFromTable", ReplyAction="http://tempuri.org/ICreator/GetProductVersionFromTableResponse")]
        int GetProductVersionFromTable(int productID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/CreateOrder", ReplyAction="http://tempuri.org/ICreator/CreateOrderResponse")]
        void CreateOrder(Client.Creator.CreatorService.OrderTable ta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/UpdateOrder", ReplyAction="http://tempuri.org/ICreator/UpdateOrderResponse")]
        void UpdateOrder(Client.Creator.CreatorService.OrderTable ta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/DeleteOrder", ReplyAction="http://tempuri.org/ICreator/DeleteOrderResponse")]
        void DeleteOrder(Client.Creator.CreatorService.OrderTable ta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/GetAllTokens", ReplyAction="http://tempuri.org/ICreator/GetAllTokensResponse")]
        System.Collections.Generic.List<Client.Creator.CreatorService.TokenTable> GetAllTokens(string searchString, Solimar.Licensing.Attribs.Lic_PackageAttribs.Lic_LicenseInfoAttribs.Lic_ValidationTokenAttribs.TTokenType token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/GetAllTokensByCustomer", ReplyAction="http://tempuri.org/ICreator/GetAllTokensByCustomerResponse")]
        System.Collections.Generic.List<Client.Creator.CreatorService.TokenTable> GetAllTokensByCustomer(string searchString, string custName, Solimar.Licensing.Attribs.Lic_PackageAttribs.Lic_LicenseInfoAttribs.Lic_ValidationTokenAttribs.TTokenType token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/GetTokensByLicenseName", ReplyAction="http://tempuri.org/ICreator/GetTokensByLicenseNameResponse")]
        System.Collections.Generic.List<Client.Creator.CreatorService.TokenTable> GetTokensByLicenseName(string licenseName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/GetHardwareTokenByKeyValue", ReplyAction="http://tempuri.org/ICreator/GetHardwareTokenByKeyValueResponse")]
        Client.Creator.CreatorService.TokenTable GetHardwareTokenByKeyValue(string keyValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/GetAvailableHardwareTokensByCustID", ReplyAction="http://tempuri.org/ICreator/GetAvailableHardwareTokensByCustIDResponse")]
        System.Collections.Generic.List<Client.Creator.CreatorService.TokenTable> GetAvailableHardwareTokensByCustID(uint custID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/GetTokenByLicenseName", ReplyAction="http://tempuri.org/ICreator/GetTokenByLicenseNameResponse")]
        Client.Creator.CreatorService.TokenTable GetTokenByLicenseName(string licenseName, byte tokenType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/TokenExists", ReplyAction="http://tempuri.org/ICreator/TokenExistsResponse")]
        bool TokenExists(uint custID, byte tokenType, string tokenValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/IsHardwareTokenActive", ReplyAction="http://tempuri.org/ICreator/IsHardwareTokenActiveResponse")]
        bool IsHardwareTokenActive(uint custID, string tokenValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/GetNextHardwareTokenValue", ReplyAction="http://tempuri.org/ICreator/GetNextHardwareTokenValueResponse")]
        uint GetNextHardwareTokenValue(uint custID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/CreateToken", ReplyAction="http://tempuri.org/ICreator/CreateTokenResponse")]
        void CreateToken(Client.Creator.CreatorService.TokenTable ta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/GetAllCustomers", ReplyAction="http://tempuri.org/ICreator/GetAllCustomersResponse")]
        System.Collections.Generic.List<Client.Creator.CreatorService.CustomerTable> GetAllCustomers(string searchString, bool enableLoadOptions);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/GetAllCustomerNames", ReplyAction="http://tempuri.org/ICreator/GetAllCustomerNamesResponse")]
        System.Collections.Generic.List<string> GetAllCustomerNames(string searchString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/GetCustomerCount", ReplyAction="http://tempuri.org/ICreator/GetCustomerCountResponse")]
        int GetCustomerCount(string searchString, bool enableLoadOptions);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/GetCustomer", ReplyAction="http://tempuri.org/ICreator/GetCustomerResponse")]
        Client.Creator.CreatorService.CustomerTable GetCustomer(string searchString, bool enableLoadOptions);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/CreateCustomer", ReplyAction="http://tempuri.org/ICreator/CreateCustomerResponse")]
        void CreateCustomer(Client.Creator.CreatorService.CustomerTable custRecord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/UpdateCustomer", ReplyAction="http://tempuri.org/ICreator/UpdateCustomerResponse")]
        void UpdateCustomer(Client.Creator.CreatorService.CustomerTable custRecord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/DeleteCustomer", ReplyAction="http://tempuri.org/ICreator/DeleteCustomerResponse")]
        void DeleteCustomer(Client.Creator.CreatorService.CustomerTable custRecord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/GetLastCustomerID", ReplyAction="http://tempuri.org/ICreator/GetLastCustomerIDResponse")]
        int GetLastCustomerID();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/GetAllLicenses", ReplyAction="http://tempuri.org/ICreator/GetAllLicensesResponse")]
        System.Collections.Generic.List<Client.Creator.CreatorService.LicenseTable> GetAllLicenses(string searchString, bool enableLoadOptions);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/GetLicensesByID", ReplyAction="http://tempuri.org/ICreator/GetLicensesByIDResponse")]
        System.Collections.Generic.List<Client.Creator.CreatorService.LicenseTable> GetLicensesByID(int custID, int destID, int groupID, bool enableLoadOptions);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/GetLicenseByName", ReplyAction="http://tempuri.org/ICreator/GetLicenseByNameResponse")]
        Client.Creator.CreatorService.LicenseTable GetLicenseByName(string licenseName, bool enableLoadOptions);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/GetLicenseByID", ReplyAction="http://tempuri.org/ICreator/GetLicenseByIDResponse")]
        Client.Creator.CreatorService.LicenseTable GetLicenseByID(int licID, bool enableLoadOptions);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/GetLicenseCountByID", ReplyAction="http://tempuri.org/ICreator/GetLicenseCountByIDResponse")]
        int GetLicenseCountByID(int custID, int destID, int groupID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/GetNextGroupID", ReplyAction="http://tempuri.org/ICreator/GetNextGroupIDResponse")]
        uint GetNextGroupID(uint custID, uint destID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/GetLastGroupID", ReplyAction="http://tempuri.org/ICreator/GetLastGroupIDResponse")]
        uint GetLastGroupID(uint custID, uint destID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/GetLicenseCountByDestName", ReplyAction="http://tempuri.org/ICreator/GetLicenseCountByDestNameResponse")]
        int GetLicenseCountByDestName(uint custID, uint destID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/GetLastDestinationID", ReplyAction="http://tempuri.org/ICreator/GetLastDestinationIDResponse")]
        uint GetLastDestinationID(uint custID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/GetLicencesByConditions", ReplyAction="http://tempuri.org/ICreator/GetLicencesByConditionsResponse")]
        System.Collections.Generic.List<Client.Creator.CreatorService.LicenseTable> GetLicencesByConditions(System.Collections.Generic.List<Client.Creator.CreatorService.Condition> conditionList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/IsLicenseModified", ReplyAction="http://tempuri.org/ICreator/IsLicenseModifiedResponse")]
        bool IsLicenseModified(string licenseName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/IsLicenseUpdated", ReplyAction="http://tempuri.org/ICreator/IsLicenseUpdatedResponse")]
        bool IsLicenseUpdated(string licenseName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/GetModifiedLicensesByCustomer", ReplyAction="http://tempuri.org/ICreator/GetModifiedLicensesByCustomerResponse")]
        System.Collections.Generic.List<string> GetModifiedLicensesByCustomer(string custName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/GetUpdatedLicensesByCustomer", ReplyAction="http://tempuri.org/ICreator/GetUpdatedLicensesByCustomerResponse")]
        System.Collections.Generic.List<string> GetUpdatedLicensesByCustomer(string custName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/GetLicenseCountByType", ReplyAction="http://tempuri.org/ICreator/GetLicenseCountByTypeResponse")]
        int GetLicenseCountByType(uint custID, uint destID, uint groupID, Solimar.Licensing.Attribs.Lic_PackageAttribs.Lic_LicenseInfoAttribs.TSoftwareLicenseType licType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/GetDerivedLicenseCount", ReplyAction="http://tempuri.org/ICreator/GetDerivedLicenseCountResponse")]
        int GetDerivedLicenseCount(uint custID, uint destID, uint groupID, Solimar.Licensing.Attribs.Lic_PackageAttribs.Lic_LicenseInfoAttribs.TSoftwareLicenseType licType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/GenerateLicensePacket", ReplyAction="http://tempuri.org/ICreator/GenerateLicensePacketResponse")]
        void GenerateLicensePacket(string packetName, string licenseName, System.DateTime expDate, string comments, ref string verificationCode, ref byte[] newByteArrayLicensePacket, string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/KeyEnumerate", ReplyAction="http://tempuri.org/ICreator/KeyEnumerateResponse")]
        System.Collections.Generic.List<Solimar.Licensing.LicenseManagerWrapper.SolimarLicenseProtectionKeyInfo> KeyEnumerate();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/KeyFormat", ReplyAction="http://tempuri.org/ICreator/KeyFormatResponse")]
        string KeyFormat(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/KeyProgramVerification", ReplyAction="http://tempuri.org/ICreator/KeyProgramVerificationResponse")]
        string KeyProgramVerification(string key, int customerNumber, int keyNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/CreateLicense", ReplyAction="http://tempuri.org/ICreator/CreateLicenseResponse")]
        void CreateLicense(Client.Creator.CreatorService.LicenseTable license);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/UpdateLicense", ReplyAction="http://tempuri.org/ICreator/UpdateLicenseResponse")]
        void UpdateLicense(Client.Creator.CreatorService.LicenseTable license);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/DeleteLicense", ReplyAction="http://tempuri.org/ICreator/DeleteLicenseResponse")]
        void DeleteLicense(Client.Creator.CreatorService.LicenseTable license);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreator/GetPacketsByLicenseName", ReplyAction="http://tempuri.org/ICreator/GetPacketsByLicenseNameResponse")]
        System.Collections.Generic.List<Client.Creator.CreatorService.PacketTable> GetPacketsByLicenseName(string licenseName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ICreatorChannel : Client.Creator.CreatorService.ICreator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class CreatorClient : System.ServiceModel.ClientBase<Client.Creator.CreatorService.ICreator>, Client.Creator.CreatorService.ICreator {
        
        public CreatorClient() {
        }
        
        public CreatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CreatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void UpdateToken(Client.Creator.CreatorService.TokenTable ta) {
            base.Channel.UpdateToken(ta);
        }
        
        public void DeleteToken(Client.Creator.CreatorService.TokenTable ta) {
            base.Channel.DeleteToken(ta);
        }
        
        public System.Collections.Generic.List<Client.Creator.CreatorService.DestinationNameTable> GetDestNamesByCustID(int custID) {
            return base.Channel.GetDestNamesByCustID(custID);
        }
        
        public Client.Creator.CreatorService.DestinationNameTable GetDestinationName(int custID, int destID) {
            return base.Channel.GetDestinationName(custID, destID);
        }
        
        public Client.Creator.CreatorService.DestinationNameTable GetDestinationID(int custID, string destName) {
            return base.Channel.GetDestinationID(custID, destName);
        }
        
        public uint GetNextDestinationID(uint custID) {
            return base.Channel.GetNextDestinationID(custID);
        }
        
        public void CreateDestinationName(Client.Creator.CreatorService.DestinationNameTable destName) {
            base.Channel.CreateDestinationName(destName);
        }
        
        public void UpdateDestinationName(Client.Creator.CreatorService.DestinationNameTable destName) {
            base.Channel.UpdateDestinationName(destName);
        }
        
        public void DeleteDestinationName(Client.Creator.CreatorService.DestinationNameTable destName) {
            base.Channel.DeleteDestinationName(destName);
        }
        
        public Client.Creator.CreatorService.PermissionsTable GetPermissionsByUser(string user) {
            return base.Channel.GetPermissionsByUser(user);
        }
        
        public System.Collections.Generic.List<Client.Creator.CreatorService.ProductTable> GetProducts() {
            return base.Channel.GetProducts();
        }
        
        public Client.Creator.CreatorService.ProductTable GetProduct(string product) {
            return base.Channel.GetProduct(product);
        }
        
        public void UpdateProductTable(Client.Creator.CreatorService.ProductTable product) {
            base.Channel.UpdateProductTable(product);
        }
        
        public Client.Creator.CreatorService.PacketTable GetPacketByVerificationCode(string verificationCode) {
            return base.Channel.GetPacketByVerificationCode(verificationCode);
        }
        
        public bool ValidateVerificationCode(string packetName, string verificationCode) {
            return base.Channel.ValidateVerificationCode(packetName, verificationCode);
        }
        
        public string GenerateLicInfoByVerifyData(ref byte[] byteVerifyData) {
            return base.Channel.GenerateLicInfoByVerifyData(ref byteVerifyData);
        }
        
        public void CreatePacket(Client.Creator.CreatorService.PacketTable packet) {
            base.Channel.CreatePacket(packet);
        }
        
        public void UpdatePacket(Client.Creator.CreatorService.PacketTable packet) {
            base.Channel.UpdatePacket(packet);
        }
        
        public void DeletePacket(Client.Creator.CreatorService.PacketTable packet) {
            base.Channel.DeletePacket(packet);
        }
        
        public System.Collections.Generic.List<Client.Creator.CreatorService.TransactionTable> GetTransactionsByPacketID(int packetID) {
            return base.Channel.GetTransactionsByPacketID(packetID);
        }
        
        public System.Collections.Generic.List<Client.Creator.CreatorService.TransactionTable> GetNewTransactionsByLicenseName(string licenseName) {
            return base.Channel.GetNewTransactionsByLicenseName(licenseName);
        }
        
        public void UpdateSubLicenseTransactionsByOrder(int stdLicOrderID, int subLicOrderID) {
            base.Channel.UpdateSubLicenseTransactionsByOrder(stdLicOrderID, subLicOrderID);
        }
        
        public void CreateTransaction(Client.Creator.CreatorService.TransactionTable ta) {
            base.Channel.CreateTransaction(ta);
        }
        
        public void UpdateTransaction(Client.Creator.CreatorService.TransactionTable ta) {
            base.Channel.UpdateTransaction(ta);
        }
        
        public void DeleteTransaction(Client.Creator.CreatorService.TransactionTable ta) {
            base.Channel.DeleteTransaction(ta);
        }
        
        public System.Collections.Generic.List<Client.Creator.CreatorService.OrderTable> GetAllOrders() {
            return base.Channel.GetAllOrders();
        }
        
        public System.Collections.Generic.List<Client.Creator.CreatorService.OrderTable> GetOrdersByLicenseName(string licenseName) {
            return base.Channel.GetOrdersByLicenseName(licenseName);
        }
        
        public System.Collections.Generic.List<Client.Creator.CreatorService.OrderTable> GetOrdersEqualsProduct(string licenseName, string productName) {
            return base.Channel.GetOrdersEqualsProduct(licenseName, productName);
        }
        
        public System.Collections.Generic.List<string> GetAddOnOrdersByStandardOrder(string standardOrder) {
            return base.Channel.GetAddOnOrdersByStandardOrder(standardOrder);
        }
        
        public Client.Creator.CreatorService.OrderTable GetOrderByOrderName(string orderName) {
            return base.Channel.GetOrderByOrderName(orderName);
        }
        
        public int GetNextOrderIndex(string licenseName) {
            return base.Channel.GetNextOrderIndex(licenseName);
        }
        
        public int GetProductVersionFromTable(int productID) {
            return base.Channel.GetProductVersionFromTable(productID);
        }
        
        public void CreateOrder(Client.Creator.CreatorService.OrderTable ta) {
            base.Channel.CreateOrder(ta);
        }
        
        public void UpdateOrder(Client.Creator.CreatorService.OrderTable ta) {
            base.Channel.UpdateOrder(ta);
        }
        
        public void DeleteOrder(Client.Creator.CreatorService.OrderTable ta) {
            base.Channel.DeleteOrder(ta);
        }
        
        public System.Collections.Generic.List<Client.Creator.CreatorService.TokenTable> GetAllTokens(string searchString, Solimar.Licensing.Attribs.Lic_PackageAttribs.Lic_LicenseInfoAttribs.Lic_ValidationTokenAttribs.TTokenType token) {
            return base.Channel.GetAllTokens(searchString, token);
        }
        
        public System.Collections.Generic.List<Client.Creator.CreatorService.TokenTable> GetAllTokensByCustomer(string searchString, string custName, Solimar.Licensing.Attribs.Lic_PackageAttribs.Lic_LicenseInfoAttribs.Lic_ValidationTokenAttribs.TTokenType token) {
            return base.Channel.GetAllTokensByCustomer(searchString, custName, token);
        }
        
        public System.Collections.Generic.List<Client.Creator.CreatorService.TokenTable> GetTokensByLicenseName(string licenseName) {
            return base.Channel.GetTokensByLicenseName(licenseName);
        }
        
        public Client.Creator.CreatorService.TokenTable GetHardwareTokenByKeyValue(string keyValue) {
            return base.Channel.GetHardwareTokenByKeyValue(keyValue);
        }
        
        public System.Collections.Generic.List<Client.Creator.CreatorService.TokenTable> GetAvailableHardwareTokensByCustID(uint custID) {
            return base.Channel.GetAvailableHardwareTokensByCustID(custID);
        }
        
        public Client.Creator.CreatorService.TokenTable GetTokenByLicenseName(string licenseName, byte tokenType) {
            return base.Channel.GetTokenByLicenseName(licenseName, tokenType);
        }
        
        public bool TokenExists(uint custID, byte tokenType, string tokenValue) {
            return base.Channel.TokenExists(custID, tokenType, tokenValue);
        }
        
        public bool IsHardwareTokenActive(uint custID, string tokenValue) {
            return base.Channel.IsHardwareTokenActive(custID, tokenValue);
        }
        
        public uint GetNextHardwareTokenValue(uint custID) {
            return base.Channel.GetNextHardwareTokenValue(custID);
        }
        
        public void CreateToken(Client.Creator.CreatorService.TokenTable ta) {
            base.Channel.CreateToken(ta);
        }
        
        public System.Collections.Generic.List<Client.Creator.CreatorService.CustomerTable> GetAllCustomers(string searchString, bool enableLoadOptions) {
            return base.Channel.GetAllCustomers(searchString, enableLoadOptions);
        }
        
        public System.Collections.Generic.List<string> GetAllCustomerNames(string searchString) {
            return base.Channel.GetAllCustomerNames(searchString);
        }
        
        public int GetCustomerCount(string searchString, bool enableLoadOptions) {
            return base.Channel.GetCustomerCount(searchString, enableLoadOptions);
        }
        
        public Client.Creator.CreatorService.CustomerTable GetCustomer(string searchString, bool enableLoadOptions) {
            return base.Channel.GetCustomer(searchString, enableLoadOptions);
        }
        
        public void CreateCustomer(Client.Creator.CreatorService.CustomerTable custRecord) {
            base.Channel.CreateCustomer(custRecord);
        }
        
        public void UpdateCustomer(Client.Creator.CreatorService.CustomerTable custRecord) {
            base.Channel.UpdateCustomer(custRecord);
        }
        
        public void DeleteCustomer(Client.Creator.CreatorService.CustomerTable custRecord) {
            base.Channel.DeleteCustomer(custRecord);
        }
        
        public int GetLastCustomerID() {
            return base.Channel.GetLastCustomerID();
        }
        
        public System.Collections.Generic.List<Client.Creator.CreatorService.LicenseTable> GetAllLicenses(string searchString, bool enableLoadOptions) {
            return base.Channel.GetAllLicenses(searchString, enableLoadOptions);
        }
        
        public System.Collections.Generic.List<Client.Creator.CreatorService.LicenseTable> GetLicensesByID(int custID, int destID, int groupID, bool enableLoadOptions) {
            return base.Channel.GetLicensesByID(custID, destID, groupID, enableLoadOptions);
        }
        
        public Client.Creator.CreatorService.LicenseTable GetLicenseByName(string licenseName, bool enableLoadOptions) {
            return base.Channel.GetLicenseByName(licenseName, enableLoadOptions);
        }
        
        public Client.Creator.CreatorService.LicenseTable GetLicenseByID(int licID, bool enableLoadOptions) {
            return base.Channel.GetLicenseByID(licID, enableLoadOptions);
        }
        
        public int GetLicenseCountByID(int custID, int destID, int groupID) {
            return base.Channel.GetLicenseCountByID(custID, destID, groupID);
        }
        
        public uint GetNextGroupID(uint custID, uint destID) {
            return base.Channel.GetNextGroupID(custID, destID);
        }
        
        public uint GetLastGroupID(uint custID, uint destID) {
            return base.Channel.GetLastGroupID(custID, destID);
        }
        
        public int GetLicenseCountByDestName(uint custID, uint destID) {
            return base.Channel.GetLicenseCountByDestName(custID, destID);
        }
        
        public uint GetLastDestinationID(uint custID) {
            return base.Channel.GetLastDestinationID(custID);
        }
        
        public System.Collections.Generic.List<Client.Creator.CreatorService.LicenseTable> GetLicencesByConditions(System.Collections.Generic.List<Client.Creator.CreatorService.Condition> conditionList) {
            return base.Channel.GetLicencesByConditions(conditionList);
        }
        
        public bool IsLicenseModified(string licenseName) {
            return base.Channel.IsLicenseModified(licenseName);
        }
        
        public bool IsLicenseUpdated(string licenseName) {
            return base.Channel.IsLicenseUpdated(licenseName);
        }
        
        public System.Collections.Generic.List<string> GetModifiedLicensesByCustomer(string custName) {
            return base.Channel.GetModifiedLicensesByCustomer(custName);
        }
        
        public System.Collections.Generic.List<string> GetUpdatedLicensesByCustomer(string custName) {
            return base.Channel.GetUpdatedLicensesByCustomer(custName);
        }
        
        public int GetLicenseCountByType(uint custID, uint destID, uint groupID, Solimar.Licensing.Attribs.Lic_PackageAttribs.Lic_LicenseInfoAttribs.TSoftwareLicenseType licType) {
            return base.Channel.GetLicenseCountByType(custID, destID, groupID, licType);
        }
        
        public int GetDerivedLicenseCount(uint custID, uint destID, uint groupID, Solimar.Licensing.Attribs.Lic_PackageAttribs.Lic_LicenseInfoAttribs.TSoftwareLicenseType licType) {
            return base.Channel.GetDerivedLicenseCount(custID, destID, groupID, licType);
        }
        
        public void GenerateLicensePacket(string packetName, string licenseName, System.DateTime expDate, string comments, ref string verificationCode, ref byte[] newByteArrayLicensePacket, string user) {
            base.Channel.GenerateLicensePacket(packetName, licenseName, expDate, comments, ref verificationCode, ref newByteArrayLicensePacket, user);
        }
        
        public System.Collections.Generic.List<Solimar.Licensing.LicenseManagerWrapper.SolimarLicenseProtectionKeyInfo> KeyEnumerate() {
            return base.Channel.KeyEnumerate();
        }
        
        public string KeyFormat(string key) {
            return base.Channel.KeyFormat(key);
        }
        
        public string KeyProgramVerification(string key, int customerNumber, int keyNumber) {
            return base.Channel.KeyProgramVerification(key, customerNumber, keyNumber);
        }
        
        public void CreateLicense(Client.Creator.CreatorService.LicenseTable license) {
            base.Channel.CreateLicense(license);
        }
        
        public void UpdateLicense(Client.Creator.CreatorService.LicenseTable license) {
            base.Channel.UpdateLicense(license);
        }
        
        public void DeleteLicense(Client.Creator.CreatorService.LicenseTable license) {
            base.Channel.DeleteLicense(license);
        }
        
        public System.Collections.Generic.List<Client.Creator.CreatorService.PacketTable> GetPacketsByLicenseName(string licenseName) {
            return base.Channel.GetPacketsByLicenseName(licenseName);
        }
    }
}
