#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreatorData
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.Runtime.Serialization;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TestKey")]
	public partial class CreatorDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCustomerTable(CustomerTable instance);
    partial void UpdateCustomerTable(CustomerTable instance);
    partial void DeleteCustomerTable(CustomerTable instance);
    partial void InsertLicenseTable(LicenseTable instance);
    partial void UpdateLicenseTable(LicenseTable instance);
    partial void DeleteLicenseTable(LicenseTable instance);
    partial void InsertProductTable(ProductTable instance);
    partial void UpdateProductTable(ProductTable instance);
    partial void DeleteProductTable(ProductTable instance);
    partial void InsertPermissionsTable(PermissionsTable instance);
    partial void UpdatePermissionsTable(PermissionsTable instance);
    partial void DeletePermissionsTable(PermissionsTable instance);
    partial void InsertPacketTable(PacketTable instance);
    partial void UpdatePacketTable(PacketTable instance);
    partial void DeletePacketTable(PacketTable instance);
    partial void InsertDestinationNameTable(DestinationNameTable instance);
    partial void UpdateDestinationNameTable(DestinationNameTable instance);
    partial void DeleteDestinationNameTable(DestinationNameTable instance);
    partial void InsertProductLicenseTable(ProductLicenseTable instance);
    partial void UpdateProductLicenseTable(ProductLicenseTable instance);
    partial void DeleteProductLicenseTable(ProductLicenseTable instance);
    partial void InsertSoftwareTokenTable(SoftwareTokenTable instance);
    partial void UpdateSoftwareTokenTable(SoftwareTokenTable instance);
    partial void DeleteSoftwareTokenTable(SoftwareTokenTable instance);
    partial void InsertTransactionTable(TransactionTable instance);
    partial void UpdateTransactionTable(TransactionTable instance);
    partial void DeleteTransactionTable(TransactionTable instance);
    partial void InsertTokenTable(TokenTable instance);
    partial void UpdateTokenTable(TokenTable instance);
    partial void DeleteTokenTable(TokenTable instance);
    partial void InsertModuleTable(ModuleTable instance);
    partial void UpdateModuleTable(ModuleTable instance);
    partial void DeleteModuleTable(ModuleTable instance);
    partial void InsertProductLicenseType(ProductLicenseType instance);
    partial void UpdateProductLicenseType(ProductLicenseType instance);
    partial void DeleteProductLicenseType(ProductLicenseType instance);
    #endregion
		
		public CreatorDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CreatorDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CreatorDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CreatorDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CustomerTable> CustomerTables
		{
			get
			{
				return this.GetTable<CustomerTable>();
			}
		}
		
		public System.Data.Linq.Table<LicenseTable> LicenseTables
		{
			get
			{
				return this.GetTable<LicenseTable>();
			}
		}
		
		public System.Data.Linq.Table<ProductTable> ProductTables
		{
			get
			{
				return this.GetTable<ProductTable>();
			}
		}
		
		public System.Data.Linq.Table<PermissionsTable> PermissionsTables
		{
			get
			{
				return this.GetTable<PermissionsTable>();
			}
		}
		
		public System.Data.Linq.Table<PacketTable> PacketTables
		{
			get
			{
				return this.GetTable<PacketTable>();
			}
		}
		
		public System.Data.Linq.Table<DestinationNameTable> DestinationNameTables
		{
			get
			{
				return this.GetTable<DestinationNameTable>();
			}
		}
		
		public System.Data.Linq.Table<ProductLicenseTable> ProductLicenseTables
		{
			get
			{
				return this.GetTable<ProductLicenseTable>();
			}
		}
		
		public System.Data.Linq.Table<SoftwareTokenTable> SoftwareTokenTables
		{
			get
			{
				return this.GetTable<SoftwareTokenTable>();
			}
		}
		
		public System.Data.Linq.Table<TransactionTable> TransactionTables
		{
			get
			{
				return this.GetTable<TransactionTable>();
			}
		}
		
		public System.Data.Linq.Table<TokenTable> TokenTables
		{
			get
			{
				return this.GetTable<TokenTable>();
			}
		}
		
		public System.Data.Linq.Table<ModuleTable> ModuleTables
		{
			get
			{
				return this.GetTable<ModuleTable>();
			}
		}
		
		public System.Data.Linq.Table<ProductLicenseType> ProductLicenseTypes
		{
			get
			{
				return this.GetTable<ProductLicenseType>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SCustomerRecord")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class CustomerTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SCRnumber;
		
		private string _SCRname;
		
		private string _SCRoperator;
		
		private EntitySet<LicenseTable> _Licenses;
		
		private EntitySet<DestinationNameTable> _DestinationNameTables;
		
		private bool serializing;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSCRnumberChanging(int value);
    partial void OnSCRnumberChanged();
    partial void OnSCRnameChanging(string value);
    partial void OnSCRnameChanged();
    partial void OnSCRoperatorChanging(string value);
    partial void OnSCRoperatorChanged();
    #endregion
		
		public CustomerTable()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SCRnumber", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int SCRnumber
		{
			get
			{
				return this._SCRnumber;
			}
			set
			{
				if ((this._SCRnumber != value))
				{
					this.OnSCRnumberChanging(value);
					this.SendPropertyChanging();
					this._SCRnumber = value;
					this.SendPropertyChanged("SCRnumber");
					this.OnSCRnumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SCRname", DbType="VarChar(255)", UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string SCRname
		{
			get
			{
				return this._SCRname;
			}
			set
			{
				if ((this._SCRname != value))
				{
					this.OnSCRnameChanging(value);
					this.SendPropertyChanging();
					this._SCRname = value;
					this.SendPropertyChanged("SCRname");
					this.OnSCRnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SCRoperator", DbType="VarChar(14)", UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string SCRoperator
		{
			get
			{
				return this._SCRoperator;
			}
			set
			{
				if ((this._SCRoperator != value))
				{
					this.OnSCRoperatorChanging(value);
					this.SendPropertyChanging();
					this._SCRoperator = value;
					this.SendPropertyChanged("SCRoperator");
					this.OnSCRoperatorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CustomerTable_LicenseTable", Storage="_Licenses", ThisKey="SCRnumber", OtherKey="SCRnumber")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4, EmitDefaultValue=false)]
		public EntitySet<LicenseTable> LicenseTables
		{
			get
			{
				if ((this.serializing 
							&& (this._Licenses.HasLoadedOrAssignedValues == false)))
				{
					return null;
				}
				return this._Licenses;
			}
			set
			{
				this._Licenses.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CustomerTable_DestinationNameTable", Storage="_DestinationNameTables", ThisKey="SCRnumber", OtherKey="CustID")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5, EmitDefaultValue=false)]
		public EntitySet<DestinationNameTable> DestinationNameTables
		{
			get
			{
				if ((this.serializing 
							&& (this._DestinationNameTables.HasLoadedOrAssignedValues == false)))
				{
					return null;
				}
				return this._DestinationNameTables;
			}
			set
			{
				this._DestinationNameTables.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Licenses(LicenseTable entity)
		{
			this.SendPropertyChanging();
			entity.CustomerTable = this;
		}
		
		private void detach_Licenses(LicenseTable entity)
		{
			this.SendPropertyChanging();
			entity.CustomerTable = null;
		}
		
		private void attach_DestinationNameTables(DestinationNameTable entity)
		{
			this.SendPropertyChanging();
			entity.CustomerTable = this;
		}
		
		private void detach_DestinationNameTables(DestinationNameTable entity)
		{
			this.SendPropertyChanging();
			entity.CustomerTable = null;
		}
		
		private void Initialize()
		{
			this._Licenses = new EntitySet<LicenseTable>(new Action<LicenseTable>(this.attach_Licenses), new Action<LicenseTable>(this.detach_Licenses));
			this._DestinationNameTables = new EntitySet<DestinationNameTable>(new Action<DestinationNameTable>(this.attach_DestinationNameTables), new Action<DestinationNameTable>(this.detach_DestinationNameTables));
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
		
		[global::System.Runtime.Serialization.OnSerializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerializing(StreamingContext context)
		{
			this.serializing = true;
		}
		
		[global::System.Runtime.Serialization.OnSerializedAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerialized(StreamingContext context)
		{
			this.serializing = false;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.License")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class LicenseTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _SCRnumber;
		
		private int _DestinationID;
		
		private int _GroupID;
		
		private string _LicenseName;
		
		private System.Data.Linq.Link<string> _LicenseInfo;
		
		private string _LicenseComments;
		
		private int _OrderIndex;
		
		private bool _IsDirty;
		
		private bool _IsActive;
		
		private string _UserLock;
		
		private System.Nullable<System.DateTime> _DateCreated;
		
		private EntitySet<PacketTable> _PacketTables;
		
		private EntitySet<ProductLicenseTable> _ProductLicenseTables;
		
		private EntitySet<TransactionTable> _TransactionTables;
		
		private EntitySet<TokenTable> _TokenTables;
		
		private EntityRef<CustomerTable> _SCustomerRecord;
		
		private bool serializing;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnSCRnumberChanging(int value);
    partial void OnSCRnumberChanged();
    partial void OnDestinationIDChanging(int value);
    partial void OnDestinationIDChanged();
    partial void OnGroupIDChanging(int value);
    partial void OnGroupIDChanged();
    partial void OnLicenseNameChanging(string value);
    partial void OnLicenseNameChanged();
    partial void OnLicenseInfoChanging(string value);
    partial void OnLicenseInfoChanged();
    partial void OnLicenseCommentsChanging(string value);
    partial void OnLicenseCommentsChanged();
    partial void OnOrderIndexChanging(int value);
    partial void OnOrderIndexChanged();
    partial void OnIsDirtyChanging(bool value);
    partial void OnIsDirtyChanged();
    partial void OnIsActiveChanging(bool value);
    partial void OnIsActiveChanged();
    partial void OnUserLockChanging(string value);
    partial void OnUserLockChanged();
    partial void OnDateCreatedChanging(System.Nullable<System.DateTime> value);
    partial void OnDateCreatedChanged();
    #endregion
		
		public LicenseTable()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SCRnumber", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public int SCRnumber
		{
			get
			{
				return this._SCRnumber;
			}
			set
			{
				if ((this._SCRnumber != value))
				{
					if (this._SCustomerRecord.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSCRnumberChanging(value);
					this.SendPropertyChanging();
					this._SCRnumber = value;
					this.SendPropertyChanged("SCRnumber");
					this.OnSCRnumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DestinationID", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public int DestinationID
		{
			get
			{
				return this._DestinationID;
			}
			set
			{
				if ((this._DestinationID != value))
				{
					this.OnDestinationIDChanging(value);
					this.SendPropertyChanging();
					this._DestinationID = value;
					this.SendPropertyChanged("DestinationID");
					this.OnDestinationIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupID", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public int GroupID
		{
			get
			{
				return this._GroupID;
			}
			set
			{
				if ((this._GroupID != value))
				{
					this.OnGroupIDChanging(value);
					this.SendPropertyChanging();
					this._GroupID = value;
					this.SendPropertyChanged("GroupID");
					this.OnGroupIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LicenseName", DbType="VarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public string LicenseName
		{
			get
			{
				return this._LicenseName;
			}
			set
			{
				if ((this._LicenseName != value))
				{
					this.OnLicenseNameChanging(value);
					this.SendPropertyChanging();
					this._LicenseName = value;
					this.SendPropertyChanged("LicenseName");
					this.OnLicenseNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LicenseInfo", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public string LicenseInfo
		{
			get
			{
				return this._LicenseInfo.Value;
			}
			set
			{
				if ((this._LicenseInfo.Value != value))
				{
					this.OnLicenseInfoChanging(value);
					this.SendPropertyChanging();
					this._LicenseInfo.Value = value;
					this.SendPropertyChanged("LicenseInfo");
					this.OnLicenseInfoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LicenseComments", DbType="VarChar(255)", UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public string LicenseComments
		{
			get
			{
				return this._LicenseComments;
			}
			set
			{
				if ((this._LicenseComments != value))
				{
					this.OnLicenseCommentsChanging(value);
					this.SendPropertyChanging();
					this._LicenseComments = value;
					this.SendPropertyChanged("LicenseComments");
					this.OnLicenseCommentsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderIndex", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=8)]
		public int OrderIndex
		{
			get
			{
				return this._OrderIndex;
			}
			set
			{
				if ((this._OrderIndex != value))
				{
					this.OnOrderIndexChanging(value);
					this.SendPropertyChanging();
					this._OrderIndex = value;
					this.SendPropertyChanged("OrderIndex");
					this.OnOrderIndexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDirty", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=9)]
		public bool IsDirty
		{
			get
			{
				return this._IsDirty;
			}
			set
			{
				if ((this._IsDirty != value))
				{
					this.OnIsDirtyChanging(value);
					this.SendPropertyChanging();
					this._IsDirty = value;
					this.SendPropertyChanged("IsDirty");
					this.OnIsDirtyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=10)]
		public bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this.OnIsActiveChanging(value);
					this.SendPropertyChanging();
					this._IsActive = value;
					this.SendPropertyChanged("IsActive");
					this.OnIsActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserLock", DbType="VarChar(50)", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=11)]
		public string UserLock
		{
			get
			{
				return this._UserLock;
			}
			set
			{
				if ((this._UserLock != value))
				{
					this.OnUserLockChanging(value);
					this.SendPropertyChanging();
					this._UserLock = value;
					this.SendPropertyChanged("UserLock");
					this.OnUserLockChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCreated", DbType="DateTime NOT NULL", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=12)]
		public System.Nullable<System.DateTime> DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				if ((this._DateCreated != value))
				{
					this.OnDateCreatedChanging(value);
					this.SendPropertyChanging();
					this._DateCreated = value;
					this.SendPropertyChanged("DateCreated");
					this.OnDateCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LicenseTable_PacketTable", Storage="_PacketTables", ThisKey="ID", OtherKey="LicenseID")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=13, EmitDefaultValue=false)]
		public EntitySet<PacketTable> PacketTables
		{
			get
			{
				if ((this.serializing 
							&& (this._PacketTables.HasLoadedOrAssignedValues == false)))
				{
					return null;
				}
				return this._PacketTables;
			}
			set
			{
				this._PacketTables.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LicenseTable_ProductLicenseTable", Storage="_ProductLicenseTables", ThisKey="ID", OtherKey="LicenseID")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=14, EmitDefaultValue=false)]
		public EntitySet<ProductLicenseTable> ProductLicenseTables
		{
			get
			{
				if ((this.serializing 
							&& (this._ProductLicenseTables.HasLoadedOrAssignedValues == false)))
				{
					return null;
				}
				return this._ProductLicenseTables;
			}
			set
			{
				this._ProductLicenseTables.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LicenseTable_TransactionTable", Storage="_TransactionTables", ThisKey="ID", OtherKey="taLicenseID")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=15, EmitDefaultValue=false)]
		public EntitySet<TransactionTable> TransactionTables
		{
			get
			{
				if ((this.serializing 
							&& (this._TransactionTables.HasLoadedOrAssignedValues == false)))
				{
					return null;
				}
				return this._TransactionTables;
			}
			set
			{
				this._TransactionTables.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LicenseTable_TokenTable", Storage="_TokenTables", ThisKey="ID", OtherKey="LicenseID")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=16, EmitDefaultValue=false)]
		public EntitySet<TokenTable> TokenTables
		{
			get
			{
				if ((this.serializing 
							&& (this._TokenTables.HasLoadedOrAssignedValues == false)))
				{
					return null;
				}
				return this._TokenTables;
			}
			set
			{
				this._TokenTables.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CustomerTable_LicenseTable", Storage="_SCustomerRecord", ThisKey="SCRnumber", OtherKey="SCRnumber", IsForeignKey=true)]
		public CustomerTable CustomerTable
		{
			get
			{
				return this._SCustomerRecord.Entity;
			}
			set
			{
				CustomerTable previousValue = this._SCustomerRecord.Entity;
				if (((previousValue != value) 
							|| (this._SCustomerRecord.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SCustomerRecord.Entity = null;
						previousValue.LicenseTables.Remove(this);
					}
					this._SCustomerRecord.Entity = value;
					if ((value != null))
					{
						value.LicenseTables.Add(this);
						this._SCRnumber = value.SCRnumber;
					}
					else
					{
						this._SCRnumber = default(int);
					}
					this.SendPropertyChanged("CustomerTable");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PacketTables(PacketTable entity)
		{
			this.SendPropertyChanging();
			entity.LicenseTable = this;
		}
		
		private void detach_PacketTables(PacketTable entity)
		{
			this.SendPropertyChanging();
			entity.LicenseTable = null;
		}
		
		private void attach_ProductLicenseTables(ProductLicenseTable entity)
		{
			this.SendPropertyChanging();
			entity.LicenseTable = this;
		}
		
		private void detach_ProductLicenseTables(ProductLicenseTable entity)
		{
			this.SendPropertyChanging();
			entity.LicenseTable = null;
		}
		
		private void attach_TransactionTables(TransactionTable entity)
		{
			this.SendPropertyChanging();
			entity.LicenseTable = this;
		}
		
		private void detach_TransactionTables(TransactionTable entity)
		{
			this.SendPropertyChanging();
			entity.LicenseTable = null;
		}
		
		private void attach_TokenTables(TokenTable entity)
		{
			this.SendPropertyChanging();
			entity.LicenseTable = this;
		}
		
		private void detach_TokenTables(TokenTable entity)
		{
			this.SendPropertyChanging();
			entity.LicenseTable = null;
		}
		
		private void Initialize()
		{
			this._PacketTables = new EntitySet<PacketTable>(new Action<PacketTable>(this.attach_PacketTables), new Action<PacketTable>(this.detach_PacketTables));
			this._ProductLicenseTables = new EntitySet<ProductLicenseTable>(new Action<ProductLicenseTable>(this.attach_ProductLicenseTables), new Action<ProductLicenseTable>(this.detach_ProductLicenseTables));
			this._TransactionTables = new EntitySet<TransactionTable>(new Action<TransactionTable>(this.attach_TransactionTables), new Action<TransactionTable>(this.detach_TransactionTables));
			this._TokenTables = new EntitySet<TokenTable>(new Action<TokenTable>(this.attach_TokenTables), new Action<TokenTable>(this.detach_TokenTables));
			this._SCustomerRecord = default(EntityRef<CustomerTable>);
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
		
		[global::System.Runtime.Serialization.OnSerializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerializing(StreamingContext context)
		{
			this.serializing = true;
		}
		
		[global::System.Runtime.Serialization.OnSerializedAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerialized(StreamingContext context)
		{
			this.serializing = false;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sProducts")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class ProductTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _pId;
		
		private int _pVersion;
		
		private string _pName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnpIdChanging(int value);
    partial void OnpIdChanged();
    partial void OnpVersionChanging(int value);
    partial void OnpVersionChanged();
    partial void OnpNameChanging(string value);
    partial void OnpNameChanged();
    #endregion
		
		public ProductTable()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pId", DbType="Int NOT NULL", IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int pId
		{
			get
			{
				return this._pId;
			}
			set
			{
				if ((this._pId != value))
				{
					this.OnpIdChanging(value);
					this.SendPropertyChanging();
					this._pId = value;
					this.SendPropertyChanged("pId");
					this.OnpIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pVersion", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public int pVersion
		{
			get
			{
				return this._pVersion;
			}
			set
			{
				if ((this._pVersion != value))
				{
					this.OnpVersionChanging(value);
					this.SendPropertyChanging();
					this._pVersion = value;
					this.SendPropertyChanged("pVersion");
					this.OnpVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pName", DbType="VarChar(50)", UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string pName
		{
			get
			{
				return this._pName;
			}
			set
			{
				if ((this._pName != value))
				{
					this.OnpNameChanging(value);
					this.SendPropertyChanging();
					this._pName = value;
					this.SendPropertyChanged("pName");
					this.OnpNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PermissionsTable")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class PermissionsTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _pt_login;
		
		private System.Nullable<bool> _pt_create_modify_key;
		
		private System.Nullable<bool> _pt_extension_pwd;
		
		private System.Nullable<bool> _pt_version_pwd;
		
		private System.Nullable<bool> _pt_module_pwd;
		
		private System.Nullable<bool> _pt_permanent_pwd;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpt_loginChanging(string value);
    partial void Onpt_loginChanged();
    partial void Onpt_create_modify_keyChanging(System.Nullable<bool> value);
    partial void Onpt_create_modify_keyChanged();
    partial void Onpt_extension_pwdChanging(System.Nullable<bool> value);
    partial void Onpt_extension_pwdChanged();
    partial void Onpt_version_pwdChanging(System.Nullable<bool> value);
    partial void Onpt_version_pwdChanged();
    partial void Onpt_module_pwdChanging(System.Nullable<bool> value);
    partial void Onpt_module_pwdChanged();
    partial void Onpt_permanent_pwdChanging(System.Nullable<bool> value);
    partial void Onpt_permanent_pwdChanged();
    #endregion
		
		public PermissionsTable()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pt_login", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public string pt_login
		{
			get
			{
				return this._pt_login;
			}
			set
			{
				if ((this._pt_login != value))
				{
					this.Onpt_loginChanging(value);
					this.SendPropertyChanging();
					this._pt_login = value;
					this.SendPropertyChanged("pt_login");
					this.Onpt_loginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pt_create_modify_key", DbType="Bit", UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public System.Nullable<bool> pt_create_modify_key
		{
			get
			{
				return this._pt_create_modify_key;
			}
			set
			{
				if ((this._pt_create_modify_key != value))
				{
					this.Onpt_create_modify_keyChanging(value);
					this.SendPropertyChanging();
					this._pt_create_modify_key = value;
					this.SendPropertyChanged("pt_create_modify_key");
					this.Onpt_create_modify_keyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pt_extension_pwd", DbType="Bit", UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public System.Nullable<bool> pt_extension_pwd
		{
			get
			{
				return this._pt_extension_pwd;
			}
			set
			{
				if ((this._pt_extension_pwd != value))
				{
					this.Onpt_extension_pwdChanging(value);
					this.SendPropertyChanging();
					this._pt_extension_pwd = value;
					this.SendPropertyChanged("pt_extension_pwd");
					this.Onpt_extension_pwdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pt_version_pwd", DbType="Bit", UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public System.Nullable<bool> pt_version_pwd
		{
			get
			{
				return this._pt_version_pwd;
			}
			set
			{
				if ((this._pt_version_pwd != value))
				{
					this.Onpt_version_pwdChanging(value);
					this.SendPropertyChanging();
					this._pt_version_pwd = value;
					this.SendPropertyChanged("pt_version_pwd");
					this.Onpt_version_pwdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pt_module_pwd", DbType="Bit", UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public System.Nullable<bool> pt_module_pwd
		{
			get
			{
				return this._pt_module_pwd;
			}
			set
			{
				if ((this._pt_module_pwd != value))
				{
					this.Onpt_module_pwdChanging(value);
					this.SendPropertyChanging();
					this._pt_module_pwd = value;
					this.SendPropertyChanged("pt_module_pwd");
					this.Onpt_module_pwdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pt_permanent_pwd", DbType="Bit", UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public System.Nullable<bool> pt_permanent_pwd
		{
			get
			{
				return this._pt_permanent_pwd;
			}
			set
			{
				if ((this._pt_permanent_pwd != value))
				{
					this.Onpt_permanent_pwdChanging(value);
					this.SendPropertyChanging();
					this._pt_permanent_pwd = value;
					this.SendPropertyChanged("pt_permanent_pwd");
					this.Onpt_permanent_pwdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Packet")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class PacketTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.DateTime _DateCreated;
		
		private string _PacketVerificationCode;
		
		private bool _IsVerified;
		
		private string _PacketComments;
		
		private string _PacketName;
		
		private int _LicenseID;
		
		private string _UserName;
		
		private System.DateTime _ExpiredDate;
		
		private string _VerifiedBy;
		
		private EntityRef<LicenseTable> _LicenseTable;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnDateCreatedChanging(System.DateTime value);
    partial void OnDateCreatedChanged();
    partial void OnPacketVerificationCodeChanging(string value);
    partial void OnPacketVerificationCodeChanged();
    partial void OnIsVerifiedChanging(bool value);
    partial void OnIsVerifiedChanged();
    partial void OnPacketCommentsChanging(string value);
    partial void OnPacketCommentsChanged();
    partial void OnPacketNameChanging(string value);
    partial void OnPacketNameChanged();
    partial void OnLicenseIDChanging(int value);
    partial void OnLicenseIDChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnExpiredDateChanging(System.DateTime value);
    partial void OnExpiredDateChanged();
    partial void OnVerifiedByChanging(string value);
    partial void OnVerifiedByChanged();
    #endregion
		
		public PacketTable()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCreated", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public System.DateTime DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				if ((this._DateCreated != value))
				{
					this.OnDateCreatedChanging(value);
					this.SendPropertyChanging();
					this._DateCreated = value;
					this.SendPropertyChanged("DateCreated");
					this.OnDateCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PacketVerificationCode", DbType="NVarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string PacketVerificationCode
		{
			get
			{
				return this._PacketVerificationCode;
			}
			set
			{
				if ((this._PacketVerificationCode != value))
				{
					this.OnPacketVerificationCodeChanging(value);
					this.SendPropertyChanging();
					this._PacketVerificationCode = value;
					this.SendPropertyChanged("PacketVerificationCode");
					this.OnPacketVerificationCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsVerified", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public bool IsVerified
		{
			get
			{
				return this._IsVerified;
			}
			set
			{
				if ((this._IsVerified != value))
				{
					this.OnIsVerifiedChanging(value);
					this.SendPropertyChanging();
					this._IsVerified = value;
					this.SendPropertyChanged("IsVerified");
					this.OnIsVerifiedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PacketComments", DbType="VarChar(255)", UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public string PacketComments
		{
			get
			{
				return this._PacketComments;
			}
			set
			{
				if ((this._PacketComments != value))
				{
					this.OnPacketCommentsChanging(value);
					this.SendPropertyChanging();
					this._PacketComments = value;
					this.SendPropertyChanged("PacketComments");
					this.OnPacketCommentsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PacketName", DbType="VarChar(128) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public string PacketName
		{
			get
			{
				return this._PacketName;
			}
			set
			{
				if ((this._PacketName != value))
				{
					this.OnPacketNameChanging(value);
					this.SendPropertyChanging();
					this._PacketName = value;
					this.SendPropertyChanged("PacketName");
					this.OnPacketNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LicenseID", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public int LicenseID
		{
			get
			{
				return this._LicenseID;
			}
			set
			{
				if ((this._LicenseID != value))
				{
					if (this._LicenseTable.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnLicenseIDChanging(value);
					this.SendPropertyChanging();
					this._LicenseID = value;
					this.SendPropertyChanged("LicenseID");
					this.OnLicenseIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=8)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpiredDate", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=9)]
		public System.DateTime ExpiredDate
		{
			get
			{
				return this._ExpiredDate;
			}
			set
			{
				if ((this._ExpiredDate != value))
				{
					this.OnExpiredDateChanging(value);
					this.SendPropertyChanging();
					this._ExpiredDate = value;
					this.SendPropertyChanged("ExpiredDate");
					this.OnExpiredDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VerifiedBy", DbType="VarChar(50)", UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=10)]
		public string VerifiedBy
		{
			get
			{
				return this._VerifiedBy;
			}
			set
			{
				if ((this._VerifiedBy != value))
				{
					this.OnVerifiedByChanging(value);
					this.SendPropertyChanging();
					this._VerifiedBy = value;
					this.SendPropertyChanged("VerifiedBy");
					this.OnVerifiedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LicenseTable_PacketTable", Storage="_LicenseTable", ThisKey="LicenseID", OtherKey="ID", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public LicenseTable LicenseTable
		{
			get
			{
				return this._LicenseTable.Entity;
			}
			set
			{
				LicenseTable previousValue = this._LicenseTable.Entity;
				if (((previousValue != value) 
							|| (this._LicenseTable.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LicenseTable.Entity = null;
						previousValue.PacketTables.Remove(this);
					}
					this._LicenseTable.Entity = value;
					if ((value != null))
					{
						value.PacketTables.Add(this);
						this._LicenseID = value.ID;
					}
					else
					{
						this._LicenseID = default(int);
					}
					this.SendPropertyChanged("LicenseTable");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			this._LicenseTable = default(EntityRef<LicenseTable>);
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DestinationName")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class DestinationNameTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _CustID;
		
		private int _DestID;
		
		private string _DestName;
		
		private EntityRef<CustomerTable> _CustomerTable;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCustIDChanging(int value);
    partial void OnCustIDChanged();
    partial void OnDestIDChanging(int value);
    partial void OnDestIDChanged();
    partial void OnDestNameChanging(string value);
    partial void OnDestNameChanged();
    #endregion
		
		public DestinationNameTable()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustID", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public int CustID
		{
			get
			{
				return this._CustID;
			}
			set
			{
				if ((this._CustID != value))
				{
					if (this._CustomerTable.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCustIDChanging(value);
					this.SendPropertyChanging();
					this._CustID = value;
					this.SendPropertyChanged("CustID");
					this.OnCustIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DestID", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public int DestID
		{
			get
			{
				return this._DestID;
			}
			set
			{
				if ((this._DestID != value))
				{
					this.OnDestIDChanging(value);
					this.SendPropertyChanging();
					this._DestID = value;
					this.SendPropertyChanged("DestID");
					this.OnDestIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DestName", DbType="VarChar(100) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public string DestName
		{
			get
			{
				return this._DestName;
			}
			set
			{
				if ((this._DestName != value))
				{
					this.OnDestNameChanging(value);
					this.SendPropertyChanging();
					this._DestName = value;
					this.SendPropertyChanged("DestName");
					this.OnDestNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CustomerTable_DestinationNameTable", Storage="_CustomerTable", ThisKey="CustID", OtherKey="SCRnumber", IsForeignKey=true)]
		public CustomerTable CustomerTable
		{
			get
			{
				return this._CustomerTable.Entity;
			}
			set
			{
				CustomerTable previousValue = this._CustomerTable.Entity;
				if (((previousValue != value) 
							|| (this._CustomerTable.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CustomerTable.Entity = null;
						previousValue.DestinationNameTables.Remove(this);
					}
					this._CustomerTable.Entity = value;
					if ((value != null))
					{
						value.DestinationNameTables.Add(this);
						this._CustID = value.SCRnumber;
					}
					else
					{
						this._CustID = default(int);
					}
					this.SendPropertyChanged("CustomerTable");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			this._CustomerTable = default(EntityRef<CustomerTable>);
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ProductLicense")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class ProductLicenseTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _plIndex;
		
		private string _plID;
		
		private byte _plState;
		
		private int _LicenseID;
		
		private System.Nullable<System.DateTime> _ExpirationDate;
		
		private string _Description;
		
		private byte _ProductID;
		
		private string _ProductVersion;
		
		private string _ParentProductLicenseID;
		
		private bool _IsActive;
		
		private byte _Activations;
		
		private byte _ActivationAmount;
		
		private byte _Extensions;
		
		private byte _ProductConnection;
		
		private System.Nullable<System.DateTime> _DateCreated;
		
		private int _TypeID;
		
		private EntitySet<ModuleTable> _ModuleTables;
		
		private EntitySet<ProductLicenseType> _ProductLicenseTypes;
		
		private EntityRef<LicenseTable> _LicenseTable;
		
		private bool serializing;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnplIndexChanging(int value);
    partial void OnplIndexChanged();
    partial void OnplIDChanging(string value);
    partial void OnplIDChanged();
    partial void OnplStateChanging(byte value);
    partial void OnplStateChanged();
    partial void OnLicenseIDChanging(int value);
    partial void OnLicenseIDChanged();
    partial void OnExpirationDateChanging(System.Nullable<System.DateTime> value);
    partial void OnExpirationDateChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnProductIDChanging(byte value);
    partial void OnProductIDChanged();
    partial void OnProductVersionChanging(string value);
    partial void OnProductVersionChanged();
    partial void OnParentProductLicenseIDChanging(string value);
    partial void OnParentProductLicenseIDChanged();
    partial void OnIsActiveChanging(bool value);
    partial void OnIsActiveChanged();
    partial void OnActivationsChanging(byte value);
    partial void OnActivationsChanged();
    partial void OnActivationAmountChanging(byte value);
    partial void OnActivationAmountChanged();
    partial void OnExtensionsChanging(byte value);
    partial void OnExtensionsChanged();
    partial void OnProductConnectionChanging(byte value);
    partial void OnProductConnectionChanged();
    partial void OnDateCreatedChanging(System.Nullable<System.DateTime> value);
    partial void OnDateCreatedChanged();
    partial void OnTypeIDChanging(int value);
    partial void OnTypeIDChanged();
    #endregion
		
		public ProductLicenseTable()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plIndex", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public int plIndex
		{
			get
			{
				return this._plIndex;
			}
			set
			{
				if ((this._plIndex != value))
				{
					this.OnplIndexChanging(value);
					this.SendPropertyChanging();
					this._plIndex = value;
					this.SendPropertyChanged("plIndex");
					this.OnplIndexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plID", DbType="VarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string plID
		{
			get
			{
				return this._plID;
			}
			set
			{
				if ((this._plID != value))
				{
					this.OnplIDChanging(value);
					this.SendPropertyChanging();
					this._plID = value;
					this.SendPropertyChanged("plID");
					this.OnplIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plState", DbType="TinyInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public byte plState
		{
			get
			{
				return this._plState;
			}
			set
			{
				if ((this._plState != value))
				{
					this.OnplStateChanging(value);
					this.SendPropertyChanging();
					this._plState = value;
					this.SendPropertyChanged("plState");
					this.OnplStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LicenseID", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public int LicenseID
		{
			get
			{
				return this._LicenseID;
			}
			set
			{
				if ((this._LicenseID != value))
				{
					if (this._LicenseTable.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnLicenseIDChanging(value);
					this.SendPropertyChanging();
					this._LicenseID = value;
					this.SendPropertyChanged("LicenseID");
					this.OnLicenseIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpirationDate", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public System.Nullable<System.DateTime> ExpirationDate
		{
			get
			{
				return this._ExpirationDate;
			}
			set
			{
				if ((this._ExpirationDate != value))
				{
					this.OnExpirationDateChanging(value);
					this.SendPropertyChanging();
					this._ExpirationDate = value;
					this.SendPropertyChanged("ExpirationDate");
					this.OnExpirationDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(255)", UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductID", DbType="TinyInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=8)]
		public byte ProductID
		{
			get
			{
				return this._ProductID;
			}
			set
			{
				if ((this._ProductID != value))
				{
					this.OnProductIDChanging(value);
					this.SendPropertyChanging();
					this._ProductID = value;
					this.SendPropertyChanged("ProductID");
					this.OnProductIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductVersion", DbType="VarChar(10) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=9)]
		public string ProductVersion
		{
			get
			{
				return this._ProductVersion;
			}
			set
			{
				if ((this._ProductVersion != value))
				{
					this.OnProductVersionChanging(value);
					this.SendPropertyChanging();
					this._ProductVersion = value;
					this.SendPropertyChanged("ProductVersion");
					this.OnProductVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentProductLicenseID", DbType="VarChar(50)", UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=10)]
		public string ParentProductLicenseID
		{
			get
			{
				return this._ParentProductLicenseID;
			}
			set
			{
				if ((this._ParentProductLicenseID != value))
				{
					this.OnParentProductLicenseIDChanging(value);
					this.SendPropertyChanging();
					this._ParentProductLicenseID = value;
					this.SendPropertyChanged("ParentProductLicenseID");
					this.OnParentProductLicenseIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=11)]
		public bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this.OnIsActiveChanging(value);
					this.SendPropertyChanging();
					this._IsActive = value;
					this.SendPropertyChanged("IsActive");
					this.OnIsActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Activations", DbType="TinyInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=12)]
		public byte Activations
		{
			get
			{
				return this._Activations;
			}
			set
			{
				if ((this._Activations != value))
				{
					this.OnActivationsChanging(value);
					this.SendPropertyChanging();
					this._Activations = value;
					this.SendPropertyChanged("Activations");
					this.OnActivationsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActivationAmount", DbType="TinyInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=13)]
		public byte ActivationAmount
		{
			get
			{
				return this._ActivationAmount;
			}
			set
			{
				if ((this._ActivationAmount != value))
				{
					this.OnActivationAmountChanging(value);
					this.SendPropertyChanging();
					this._ActivationAmount = value;
					this.SendPropertyChanged("ActivationAmount");
					this.OnActivationAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Extensions", DbType="TinyInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=14)]
		public byte Extensions
		{
			get
			{
				return this._Extensions;
			}
			set
			{
				if ((this._Extensions != value))
				{
					this.OnExtensionsChanging(value);
					this.SendPropertyChanging();
					this._Extensions = value;
					this.SendPropertyChanged("Extensions");
					this.OnExtensionsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductConnection", DbType="TinyInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=15)]
		public byte ProductConnection
		{
			get
			{
				return this._ProductConnection;
			}
			set
			{
				if ((this._ProductConnection != value))
				{
					this.OnProductConnectionChanging(value);
					this.SendPropertyChanging();
					this._ProductConnection = value;
					this.SendPropertyChanged("ProductConnection");
					this.OnProductConnectionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCreated", DbType="DateTime NOT NULL", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=16)]
		public System.Nullable<System.DateTime> DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				if ((this._DateCreated != value))
				{
					this.OnDateCreatedChanging(value);
					this.SendPropertyChanging();
					this._DateCreated = value;
					this.SendPropertyChanged("DateCreated");
					this.OnDateCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeID", DbType="TinyInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=17)]
		public int TypeID
		{
			get
			{
				return this._TypeID;
			}
			set
			{
				if ((this._TypeID != value))
				{
					this.OnTypeIDChanging(value);
					this.SendPropertyChanging();
					this._TypeID = value;
					this.SendPropertyChanged("TypeID");
					this.OnTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ProductLicenseTable_ModuleTable", Storage="_ModuleTables", ThisKey="ID", OtherKey="ProductLicenseID")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=18, EmitDefaultValue=false)]
		public EntitySet<ModuleTable> ModuleTables
		{
			get
			{
				if ((this.serializing 
							&& (this._ModuleTables.HasLoadedOrAssignedValues == false)))
				{
					return null;
				}
				return this._ModuleTables;
			}
			set
			{
				this._ModuleTables.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ProductLicenseTable_ProductLicenseType", Storage="_ProductLicenseTypes", ThisKey="TypeID", OtherKey="ID")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=19, EmitDefaultValue=false)]
		public EntitySet<ProductLicenseType> ProductLicenseTypes
		{
			get
			{
				if ((this.serializing 
							&& (this._ProductLicenseTypes.HasLoadedOrAssignedValues == false)))
				{
					return null;
				}
				return this._ProductLicenseTypes;
			}
			set
			{
				this._ProductLicenseTypes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LicenseTable_ProductLicenseTable", Storage="_LicenseTable", ThisKey="LicenseID", OtherKey="ID", IsForeignKey=true)]
		public LicenseTable LicenseTable
		{
			get
			{
				return this._LicenseTable.Entity;
			}
			set
			{
				LicenseTable previousValue = this._LicenseTable.Entity;
				if (((previousValue != value) 
							|| (this._LicenseTable.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LicenseTable.Entity = null;
						previousValue.ProductLicenseTables.Remove(this);
					}
					this._LicenseTable.Entity = value;
					if ((value != null))
					{
						value.ProductLicenseTables.Add(this);
						this._LicenseID = value.ID;
					}
					else
					{
						this._LicenseID = default(int);
					}
					this.SendPropertyChanged("LicenseTable");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ModuleTables(ModuleTable entity)
		{
			this.SendPropertyChanging();
			entity.ProductLicenseTable = this;
		}
		
		private void detach_ModuleTables(ModuleTable entity)
		{
			this.SendPropertyChanging();
			entity.ProductLicenseTable = null;
		}
		
		private void attach_ProductLicenseTypes(ProductLicenseType entity)
		{
			this.SendPropertyChanging();
			entity.ProductLicenseTable = this;
		}
		
		private void detach_ProductLicenseTypes(ProductLicenseType entity)
		{
			this.SendPropertyChanging();
			entity.ProductLicenseTable = null;
		}
		
		private void Initialize()
		{
			this._ModuleTables = new EntitySet<ModuleTable>(new Action<ModuleTable>(this.attach_ModuleTables), new Action<ModuleTable>(this.detach_ModuleTables));
			this._ProductLicenseTypes = new EntitySet<ProductLicenseType>(new Action<ProductLicenseType>(this.attach_ProductLicenseTypes), new Action<ProductLicenseType>(this.detach_ProductLicenseTypes));
			this._LicenseTable = default(EntityRef<LicenseTable>);
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
		
		[global::System.Runtime.Serialization.OnSerializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerializing(StreamingContext context)
		{
			this.serializing = true;
		}
		
		[global::System.Runtime.Serialization.OnSerializedAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerialized(StreamingContext context)
		{
			this.serializing = false;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SoftwareTokenTable")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class SoftwareTokenTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _TokenType;
		
		private byte _Status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTokenTypeChanging(string value);
    partial void OnTokenTypeChanged();
    partial void OnStatusChanging(byte value);
    partial void OnStatusChanged();
    #endregion
		
		public SoftwareTokenTable()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TokenType", DbType="VarChar(20) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string TokenType
		{
			get
			{
				return this._TokenType;
			}
			set
			{
				if ((this._TokenType != value))
				{
					this.OnTokenTypeChanging(value);
					this.SendPropertyChanging();
					this._TokenType = value;
					this.SendPropertyChanged("TokenType");
					this.OnTokenTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="TinyInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public byte Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Transaction]")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class TransactionTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private byte _taType;
		
		private string _taDescription;
		
		private string _taUnits;
		
		private string _taPreviousValue;
		
		private System.DateTime _taDateCreated;
		
		private string _taUser;
		
		private System.Nullable<int> _taPacketID;
		
		private int _taLicenseID;
		
		private System.Nullable<int> _taOrderID;
		
		private EntityRef<LicenseTable> _LicenseTable;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OntaTypeChanging(byte value);
    partial void OntaTypeChanged();
    partial void OntaDescriptionChanging(string value);
    partial void OntaDescriptionChanged();
    partial void OntaUnitsChanging(string value);
    partial void OntaUnitsChanged();
    partial void OntaPreviousValueChanging(string value);
    partial void OntaPreviousValueChanged();
    partial void OntaDateCreatedChanging(System.DateTime value);
    partial void OntaDateCreatedChanged();
    partial void OntaUserChanging(string value);
    partial void OntaUserChanged();
    partial void OntaPacketIDChanging(System.Nullable<int> value);
    partial void OntaPacketIDChanged();
    partial void OntaLicenseIDChanging(int value);
    partial void OntaLicenseIDChanged();
    partial void OntaOrderIDChanging(System.Nullable<int> value);
    partial void OntaOrderIDChanged();
    #endregion
		
		public TransactionTable()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taType", DbType="TinyInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public byte taType
		{
			get
			{
				return this._taType;
			}
			set
			{
				if ((this._taType != value))
				{
					this.OntaTypeChanging(value);
					this.SendPropertyChanging();
					this._taType = value;
					this.SendPropertyChanged("taType");
					this.OntaTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taDescription", DbType="VarChar(100) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string taDescription
		{
			get
			{
				return this._taDescription;
			}
			set
			{
				if ((this._taDescription != value))
				{
					this.OntaDescriptionChanging(value);
					this.SendPropertyChanging();
					this._taDescription = value;
					this.SendPropertyChanged("taDescription");
					this.OntaDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taUnits", DbType="VarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public string taUnits
		{
			get
			{
				return this._taUnits;
			}
			set
			{
				if ((this._taUnits != value))
				{
					this.OntaUnitsChanging(value);
					this.SendPropertyChanging();
					this._taUnits = value;
					this.SendPropertyChanged("taUnits");
					this.OntaUnitsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taPreviousValue", DbType="VarChar(50)", UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public string taPreviousValue
		{
			get
			{
				return this._taPreviousValue;
			}
			set
			{
				if ((this._taPreviousValue != value))
				{
					this.OntaPreviousValueChanging(value);
					this.SendPropertyChanging();
					this._taPreviousValue = value;
					this.SendPropertyChanged("taPreviousValue");
					this.OntaPreviousValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taDateCreated", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public System.DateTime taDateCreated
		{
			get
			{
				return this._taDateCreated;
			}
			set
			{
				if ((this._taDateCreated != value))
				{
					this.OntaDateCreatedChanging(value);
					this.SendPropertyChanging();
					this._taDateCreated = value;
					this.SendPropertyChanged("taDateCreated");
					this.OntaDateCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taUser", DbType="VarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public string taUser
		{
			get
			{
				return this._taUser;
			}
			set
			{
				if ((this._taUser != value))
				{
					this.OntaUserChanging(value);
					this.SendPropertyChanging();
					this._taUser = value;
					this.SendPropertyChanged("taUser");
					this.OntaUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taPacketID", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=8)]
		public System.Nullable<int> taPacketID
		{
			get
			{
				return this._taPacketID;
			}
			set
			{
				if ((this._taPacketID != value))
				{
					this.OntaPacketIDChanging(value);
					this.SendPropertyChanging();
					this._taPacketID = value;
					this.SendPropertyChanged("taPacketID");
					this.OntaPacketIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taLicenseID", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=9)]
		public int taLicenseID
		{
			get
			{
				return this._taLicenseID;
			}
			set
			{
				if ((this._taLicenseID != value))
				{
					if (this._LicenseTable.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OntaLicenseIDChanging(value);
					this.SendPropertyChanging();
					this._taLicenseID = value;
					this.SendPropertyChanged("taLicenseID");
					this.OntaLicenseIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taOrderID", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=10)]
		public System.Nullable<int> taOrderID
		{
			get
			{
				return this._taOrderID;
			}
			set
			{
				if ((this._taOrderID != value))
				{
					this.OntaOrderIDChanging(value);
					this.SendPropertyChanging();
					this._taOrderID = value;
					this.SendPropertyChanged("taOrderID");
					this.OntaOrderIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LicenseTable_TransactionTable", Storage="_LicenseTable", ThisKey="taLicenseID", OtherKey="ID", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public LicenseTable LicenseTable
		{
			get
			{
				return this._LicenseTable.Entity;
			}
			set
			{
				LicenseTable previousValue = this._LicenseTable.Entity;
				if (((previousValue != value) 
							|| (this._LicenseTable.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LicenseTable.Entity = null;
						previousValue.TransactionTables.Remove(this);
					}
					this._LicenseTable.Entity = value;
					if ((value != null))
					{
						value.TransactionTables.Add(this);
						this._taLicenseID = value.ID;
					}
					else
					{
						this._taLicenseID = default(int);
					}
					this.SendPropertyChanged("LicenseTable");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			this._LicenseTable = default(EntityRef<LicenseTable>);
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Token")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class TokenTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _LicenseID;
		
		private byte _TokenType;
		
		private string _TokenValue;
		
		private int _CustID;
		
		private byte _TokenStatus;
		
		private System.Nullable<System.DateTime> _ActivatedDate;
		
		private System.Nullable<System.DateTime> _DeactivatedDate;
		
		private EntityRef<LicenseTable> _LicenseTable;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnLicenseIDChanging(int value);
    partial void OnLicenseIDChanged();
    partial void OnTokenTypeChanging(byte value);
    partial void OnTokenTypeChanged();
    partial void OnTokenValueChanging(string value);
    partial void OnTokenValueChanged();
    partial void OnCustIDChanging(int value);
    partial void OnCustIDChanged();
    partial void OnTokenStatusChanging(byte value);
    partial void OnTokenStatusChanged();
    partial void OnActivatedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnActivatedDateChanged();
    partial void OnDeactivatedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnDeactivatedDateChanged();
    #endregion
		
		public TokenTable()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LicenseID", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public int LicenseID
		{
			get
			{
				return this._LicenseID;
			}
			set
			{
				if ((this._LicenseID != value))
				{
					if (this._LicenseTable.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnLicenseIDChanging(value);
					this.SendPropertyChanging();
					this._LicenseID = value;
					this.SendPropertyChanged("LicenseID");
					this.OnLicenseIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TokenType", DbType="TinyInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public byte TokenType
		{
			get
			{
				return this._TokenType;
			}
			set
			{
				if ((this._TokenType != value))
				{
					this.OnTokenTypeChanging(value);
					this.SendPropertyChanging();
					this._TokenType = value;
					this.SendPropertyChanged("TokenType");
					this.OnTokenTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TokenValue", DbType="VarChar(128) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public string TokenValue
		{
			get
			{
				return this._TokenValue;
			}
			set
			{
				if ((this._TokenValue != value))
				{
					this.OnTokenValueChanging(value);
					this.SendPropertyChanging();
					this._TokenValue = value;
					this.SendPropertyChanged("TokenValue");
					this.OnTokenValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustID", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public int CustID
		{
			get
			{
				return this._CustID;
			}
			set
			{
				if ((this._CustID != value))
				{
					this.OnCustIDChanging(value);
					this.SendPropertyChanging();
					this._CustID = value;
					this.SendPropertyChanged("CustID");
					this.OnCustIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TokenStatus", DbType="TinyInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public byte TokenStatus
		{
			get
			{
				return this._TokenStatus;
			}
			set
			{
				if ((this._TokenStatus != value))
				{
					this.OnTokenStatusChanging(value);
					this.SendPropertyChanging();
					this._TokenStatus = value;
					this.SendPropertyChanged("TokenStatus");
					this.OnTokenStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActivatedDate", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public System.Nullable<System.DateTime> ActivatedDate
		{
			get
			{
				return this._ActivatedDate;
			}
			set
			{
				if ((this._ActivatedDate != value))
				{
					this.OnActivatedDateChanging(value);
					this.SendPropertyChanging();
					this._ActivatedDate = value;
					this.SendPropertyChanged("ActivatedDate");
					this.OnActivatedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeactivatedDate", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=8)]
		public System.Nullable<System.DateTime> DeactivatedDate
		{
			get
			{
				return this._DeactivatedDate;
			}
			set
			{
				if ((this._DeactivatedDate != value))
				{
					this.OnDeactivatedDateChanging(value);
					this.SendPropertyChanging();
					this._DeactivatedDate = value;
					this.SendPropertyChanged("DeactivatedDate");
					this.OnDeactivatedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LicenseTable_TokenTable", Storage="_LicenseTable", ThisKey="LicenseID", OtherKey="ID", IsForeignKey=true)]
		public LicenseTable LicenseTable
		{
			get
			{
				return this._LicenseTable.Entity;
			}
			set
			{
				LicenseTable previousValue = this._LicenseTable.Entity;
				if (((previousValue != value) 
							|| (this._LicenseTable.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LicenseTable.Entity = null;
						previousValue.TokenTables.Remove(this);
					}
					this._LicenseTable.Entity = value;
					if ((value != null))
					{
						value.TokenTables.Add(this);
						this._LicenseID = value.ID;
					}
					else
					{
						this._LicenseID = default(int);
					}
					this.SendPropertyChanged("LicenseTable");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			this._LicenseTable = default(EntityRef<LicenseTable>);
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Module")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class ModuleTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private short _ModID;
		
		private int _Value;
		
		private byte _AppInstance;
		
		private int _ProductLicenseID;
		
		private EntityRef<ProductLicenseTable> _ProductLicenseTable;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnModIDChanging(short value);
    partial void OnModIDChanged();
    partial void OnValueChanging(int value);
    partial void OnValueChanged();
    partial void OnAppInstanceChanging(byte value);
    partial void OnAppInstanceChanged();
    partial void OnProductLicenseIDChanging(int value);
    partial void OnProductLicenseIDChanged();
    #endregion
		
		public ModuleTable()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModID", DbType="SmallInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public short ModID
		{
			get
			{
				return this._ModID;
			}
			set
			{
				if ((this._ModID != value))
				{
					this.OnModIDChanging(value);
					this.SendPropertyChanging();
					this._ModID = value;
					this.SendPropertyChanged("ModID");
					this.OnModIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public int Value
		{
			get
			{
				return this._Value;
			}
			set
			{
				if ((this._Value != value))
				{
					this.OnValueChanging(value);
					this.SendPropertyChanging();
					this._Value = value;
					this.SendPropertyChanged("Value");
					this.OnValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AppInstance", DbType="TinyInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public byte AppInstance
		{
			get
			{
				return this._AppInstance;
			}
			set
			{
				if ((this._AppInstance != value))
				{
					this.OnAppInstanceChanging(value);
					this.SendPropertyChanging();
					this._AppInstance = value;
					this.SendPropertyChanged("AppInstance");
					this.OnAppInstanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductLicenseID", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public int ProductLicenseID
		{
			get
			{
				return this._ProductLicenseID;
			}
			set
			{
				if ((this._ProductLicenseID != value))
				{
					if (this._ProductLicenseTable.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProductLicenseIDChanging(value);
					this.SendPropertyChanging();
					this._ProductLicenseID = value;
					this.SendPropertyChanged("ProductLicenseID");
					this.OnProductLicenseIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ProductLicenseTable_ModuleTable", Storage="_ProductLicenseTable", ThisKey="ProductLicenseID", OtherKey="ID", IsForeignKey=true)]
		public ProductLicenseTable ProductLicenseTable
		{
			get
			{
				return this._ProductLicenseTable.Entity;
			}
			set
			{
				ProductLicenseTable previousValue = this._ProductLicenseTable.Entity;
				if (((previousValue != value) 
							|| (this._ProductLicenseTable.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ProductLicenseTable.Entity = null;
						previousValue.ModuleTables.Remove(this);
					}
					this._ProductLicenseTable.Entity = value;
					if ((value != null))
					{
						value.ModuleTables.Add(this);
						this._ProductLicenseID = value.ID;
					}
					else
					{
						this._ProductLicenseID = default(int);
					}
					this.SendPropertyChanged("ProductLicenseTable");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			this._ProductLicenseTable = default(EntityRef<ProductLicenseTable>);
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ProductLicenseType")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class ProductLicenseType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Type;
		
		private EntityRef<ProductLicenseTable> _ProductLicenseTable;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTypeChanging(string value);
    partial void OnTypeChanged();
    #endregion
		
		public ProductLicenseType()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					if (this._ProductLicenseTable.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="VarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ProductLicenseTable_ProductLicenseType", Storage="_ProductLicenseTable", ThisKey="ID", OtherKey="TypeID", IsForeignKey=true)]
		public ProductLicenseTable ProductLicenseTable
		{
			get
			{
				return this._ProductLicenseTable.Entity;
			}
			set
			{
				ProductLicenseTable previousValue = this._ProductLicenseTable.Entity;
				if (((previousValue != value) 
							|| (this._ProductLicenseTable.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ProductLicenseTable.Entity = null;
						previousValue.ProductLicenseTypes.Remove(this);
					}
					this._ProductLicenseTable.Entity = value;
					if ((value != null))
					{
						value.ProductLicenseTypes.Add(this);
						this._ID = value.TypeID;
					}
					else
					{
						this._ID = default(int);
					}
					this.SendPropertyChanged("ProductLicenseTable");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			this._ProductLicenseTable = default(EntityRef<ProductLicenseTable>);
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
}
#pragma warning restore 1591
