#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreatorData
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.Runtime.Serialization;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="TestKey3")]
	public partial class CreatorDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCustomerTable(CustomerTable instance);
    partial void UpdateCustomerTable(CustomerTable instance);
    partial void DeleteCustomerTable(CustomerTable instance);
    partial void InsertTransactionTable(TransactionTable instance);
    partial void UpdateTransactionTable(TransactionTable instance);
    partial void DeleteTransactionTable(TransactionTable instance);
    partial void InsertLicenseTable(LicenseTable instance);
    partial void UpdateLicenseTable(LicenseTable instance);
    partial void DeleteLicenseTable(LicenseTable instance);
    partial void InsertOrderTable(OrderTable instance);
    partial void UpdateOrderTable(OrderTable instance);
    partial void DeleteOrderTable(OrderTable instance);
    partial void InsertProductTable(ProductTable instance);
    partial void UpdateProductTable(ProductTable instance);
    partial void DeleteProductTable(ProductTable instance);
    partial void InsertPermissionsTable(PermissionsTable instance);
    partial void UpdatePermissionsTable(PermissionsTable instance);
    partial void DeletePermissionsTable(PermissionsTable instance);
    partial void InsertTokenTable(TokenTable instance);
    partial void UpdateTokenTable(TokenTable instance);
    partial void DeleteTokenTable(TokenTable instance);
    partial void InsertPacketTable(PacketTable instance);
    partial void UpdatePacketTable(PacketTable instance);
    partial void DeletePacketTable(PacketTable instance);
    partial void InsertDestinationNameTable(DestinationNameTable instance);
    partial void UpdateDestinationNameTable(DestinationNameTable instance);
    partial void DeleteDestinationNameTable(DestinationNameTable instance);
    #endregion
		
		public CreatorDataContext() : 
				base(global::CreatorData.Properties.Settings.Default.TestKeyConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CreatorDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CreatorDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CreatorDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CreatorDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CustomerTable> CustomerTables
		{
			get
			{
				return this.GetTable<CustomerTable>();
			}
		}
		
		public System.Data.Linq.Table<TransactionTable> TransactionTables
		{
			get
			{
				return this.GetTable<TransactionTable>();
			}
		}
		
		public System.Data.Linq.Table<LicenseTable> LicenseTables
		{
			get
			{
				return this.GetTable<LicenseTable>();
			}
		}
		
		public System.Data.Linq.Table<OrderTable> OrderTables
		{
			get
			{
				return this.GetTable<OrderTable>();
			}
		}
		
		public System.Data.Linq.Table<ProductTable> ProductTables
		{
			get
			{
				return this.GetTable<ProductTable>();
			}
		}
		
		public System.Data.Linq.Table<PermissionsTable> PermissionsTables
		{
			get
			{
				return this.GetTable<PermissionsTable>();
			}
		}
		
		public System.Data.Linq.Table<TokenTable> TokenTables
		{
			get
			{
				return this.GetTable<TokenTable>();
			}
		}
		
		public System.Data.Linq.Table<PacketTable> PacketTables
		{
			get
			{
				return this.GetTable<PacketTable>();
			}
		}
		
		public System.Data.Linq.Table<DestinationNameTable> DestinationNameTables
		{
			get
			{
				return this.GetTable<DestinationNameTable>();
			}
		}
	}
	
	[Table(Name="dbo.SCustomerRecord")]
	[DataContract()]
	public partial class CustomerTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SCRnumber;
		
		private string _SCRname;
		
		private string _SCRoperator;
		
		private EntitySet<LicenseTable> _Licenses;
		
		private EntitySet<DestinationNameTable> _DestinationNameTables;
		
		private bool serializing;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSCRnumberChanging(int value);
    partial void OnSCRnumberChanged();
    partial void OnSCRnameChanging(string value);
    partial void OnSCRnameChanged();
    partial void OnSCRoperatorChanging(string value);
    partial void OnSCRoperatorChanged();
    #endregion
		
		public CustomerTable()
		{
			this.Initialize();
		}
		
		[Column(Storage="_SCRnumber", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		[DataMember(Order=1)]
		public int SCRnumber
		{
			get
			{
				return this._SCRnumber;
			}
			set
			{
				if ((this._SCRnumber != value))
				{
					this.OnSCRnumberChanging(value);
					this.SendPropertyChanging();
					this._SCRnumber = value;
					this.SendPropertyChanged("SCRnumber");
					this.OnSCRnumberChanged();
				}
			}
		}
		
		[Column(Storage="_SCRname", DbType="VarChar(255)", UpdateCheck=UpdateCheck.Never)]
		[DataMember(Order=2)]
		public string SCRname
		{
			get
			{
				return this._SCRname;
			}
			set
			{
				if ((this._SCRname != value))
				{
					this.OnSCRnameChanging(value);
					this.SendPropertyChanging();
					this._SCRname = value;
					this.SendPropertyChanged("SCRname");
					this.OnSCRnameChanged();
				}
			}
		}
		
		[Column(Storage="_SCRoperator", DbType="VarChar(14)", UpdateCheck=UpdateCheck.Never)]
		[DataMember(Order=3)]
		public string SCRoperator
		{
			get
			{
				return this._SCRoperator;
			}
			set
			{
				if ((this._SCRoperator != value))
				{
					this.OnSCRoperatorChanging(value);
					this.SendPropertyChanging();
					this._SCRoperator = value;
					this.SendPropertyChanged("SCRoperator");
					this.OnSCRoperatorChanged();
				}
			}
		}
		
		[Association(Name="CustomerTable_LicenseTable", Storage="_Licenses", ThisKey="SCRnumber", OtherKey="SCRnumber")]
		[DataMember(Order=4, EmitDefaultValue=false)]
		public EntitySet<LicenseTable> LicenseTables
		{
			get
			{
				if ((this.serializing 
							&& (this._Licenses.HasLoadedOrAssignedValues == false)))
				{
					return null;
				}
				return this._Licenses;
			}
			set
			{
				this._Licenses.Assign(value);
			}
		}
		
		[Association(Name="CustomerTable_DestinationName", Storage="_DestinationNameTables", ThisKey="SCRnumber", OtherKey="CustID")]
		[DataMember(Order=5, EmitDefaultValue=false)]
		public EntitySet<DestinationNameTable> DestinationNameTables
		{
			get
			{
				if ((this.serializing 
							&& (this._DestinationNameTables.HasLoadedOrAssignedValues == false)))
				{
					return null;
				}
				return this._DestinationNameTables;
			}
			set
			{
				this._DestinationNameTables.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Licenses(LicenseTable entity)
		{
			this.SendPropertyChanging();
			entity.CustomerTable = this;
		}
		
		private void detach_Licenses(LicenseTable entity)
		{
			this.SendPropertyChanging();
			entity.CustomerTable = null;
		}
		
		private void attach_DestinationNameTables(DestinationNameTable entity)
		{
			this.SendPropertyChanging();
			entity.CustomerTable = this;
		}
		
		private void detach_DestinationNameTables(DestinationNameTable entity)
		{
			this.SendPropertyChanging();
			entity.CustomerTable = null;
		}
		
		private void Initialize()
		{
			this._Licenses = new EntitySet<LicenseTable>(new Action<LicenseTable>(this.attach_Licenses), new Action<LicenseTable>(this.detach_Licenses));
			this._DestinationNameTables = new EntitySet<DestinationNameTable>(new Action<DestinationNameTable>(this.attach_DestinationNameTables), new Action<DestinationNameTable>(this.detach_DestinationNameTables));
			OnCreated();
		}
		
		[OnDeserializing()]
		[System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
		
		[OnSerializing()]
		[System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerializing(StreamingContext context)
		{
			this.serializing = true;
		}
		
		[OnSerialized()]
		[System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerialized(StreamingContext context)
		{
			this.serializing = false;
		}
	}
	
	[Table(Name="[CORP\\AChou].[Transaction]")]
	[DataContract()]
	public partial class TransactionTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private byte _taType;
		
		private string _taDescription;
		
		private string _taUnits;
		
		private System.DateTime _taDateCreated;
		
		private string _taUser;
		
		private System.Nullable<int> _taPacketID;
		
		private int _taLicenseID;
		
		private System.Nullable<int> _taOrderID;
		
		private EntityRef<LicenseTable> _License;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OntaTypeChanging(byte value);
    partial void OntaTypeChanged();
    partial void OntaDescriptionChanging(string value);
    partial void OntaDescriptionChanged();
    partial void OntaUnitsChanging(string value);
    partial void OntaUnitsChanged();
    partial void OntaDateCreatedChanging(System.DateTime value);
    partial void OntaDateCreatedChanged();
    partial void OntaUserChanging(string value);
    partial void OntaUserChanged();
    partial void OntaPacketIDChanging(System.Nullable<int> value);
    partial void OntaPacketIDChanged();
    partial void OntaLicenseIDChanging(int value);
    partial void OntaLicenseIDChanged();
    partial void OntaOrderIDChanging(System.Nullable<int> value);
    partial void OntaOrderIDChanged();
    #endregion
		
		public TransactionTable()
		{
			this.Initialize();
		}
		
		[Column(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		[DataMember(Order=1)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[Column(Storage="_taType", DbType="TinyInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		[DataMember(Order=2)]
		public byte taType
		{
			get
			{
				return this._taType;
			}
			set
			{
				if ((this._taType != value))
				{
					this.OntaTypeChanging(value);
					this.SendPropertyChanging();
					this._taType = value;
					this.SendPropertyChanged("taType");
					this.OntaTypeChanged();
				}
			}
		}
		
		[Column(Storage="_taDescription", DbType="VarChar(100) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		[DataMember(Order=3)]
		public string taDescription
		{
			get
			{
				return this._taDescription;
			}
			set
			{
				if ((this._taDescription != value))
				{
					this.OntaDescriptionChanging(value);
					this.SendPropertyChanging();
					this._taDescription = value;
					this.SendPropertyChanged("taDescription");
					this.OntaDescriptionChanged();
				}
			}
		}
		
		[Column(Storage="_taUnits", DbType="VarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		[DataMember(Order=4)]
		public string taUnits
		{
			get
			{
				return this._taUnits;
			}
			set
			{
				if ((this._taUnits != value))
				{
					this.OntaUnitsChanging(value);
					this.SendPropertyChanging();
					this._taUnits = value;
					this.SendPropertyChanged("taUnits");
					this.OntaUnitsChanged();
				}
			}
		}
		
		[Column(Storage="_taDateCreated", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		[DataMember(Order=5)]
		public System.DateTime taDateCreated
		{
			get
			{
				return this._taDateCreated;
			}
			set
			{
				if ((this._taDateCreated != value))
				{
					this.OntaDateCreatedChanging(value);
					this.SendPropertyChanging();
					this._taDateCreated = value;
					this.SendPropertyChanged("taDateCreated");
					this.OntaDateCreatedChanged();
				}
			}
		}
		
		[Column(Storage="_taUser", DbType="VarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		[DataMember(Order=6)]
		public string taUser
		{
			get
			{
				return this._taUser;
			}
			set
			{
				if ((this._taUser != value))
				{
					this.OntaUserChanging(value);
					this.SendPropertyChanging();
					this._taUser = value;
					this.SendPropertyChanged("taUser");
					this.OntaUserChanged();
				}
			}
		}
		
		[Column(Storage="_taPacketID", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		[DataMember(Order=7)]
		public System.Nullable<int> taPacketID
		{
			get
			{
				return this._taPacketID;
			}
			set
			{
				if ((this._taPacketID != value))
				{
					this.OntaPacketIDChanging(value);
					this.SendPropertyChanging();
					this._taPacketID = value;
					this.SendPropertyChanged("taPacketID");
					this.OntaPacketIDChanged();
				}
			}
		}
		
		[Column(Storage="_taLicenseID", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		[DataMember(Order=8)]
		public int taLicenseID
		{
			get
			{
				return this._taLicenseID;
			}
			set
			{
				if ((this._taLicenseID != value))
				{
					if (this._License.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OntaLicenseIDChanging(value);
					this.SendPropertyChanging();
					this._taLicenseID = value;
					this.SendPropertyChanged("taLicenseID");
					this.OntaLicenseIDChanged();
				}
			}
		}
		
		[Column(Storage="_taOrderID", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		[DataMember(Order=9)]
		public System.Nullable<int> taOrderID
		{
			get
			{
				return this._taOrderID;
			}
			set
			{
				if ((this._taOrderID != value))
				{
					this.OntaOrderIDChanging(value);
					this.SendPropertyChanging();
					this._taOrderID = value;
					this.SendPropertyChanged("taOrderID");
					this.OntaOrderIDChanged();
				}
			}
		}
		
		[Association(Name="LicenseTable_TransactionTable", Storage="_License", ThisKey="taLicenseID", OtherKey="ID", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public LicenseTable LicenseTable
		{
			get
			{
				return this._License.Entity;
			}
			set
			{
				LicenseTable previousValue = this._License.Entity;
				if (((previousValue != value) 
							|| (this._License.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._License.Entity = null;
						previousValue.TransactionTables.Remove(this);
					}
					this._License.Entity = value;
					if ((value != null))
					{
						value.TransactionTables.Add(this);
						this._taLicenseID = value.ID;
					}
					else
					{
						this._taLicenseID = default(int);
					}
					this.SendPropertyChanged("LicenseTable");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			this._License = default(EntityRef<LicenseTable>);
			OnCreated();
		}
		
		[OnDeserializing()]
		[System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[Table(Name="[CORP\\AChou].License")]
	[DataContract()]
	public partial class LicenseTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _SCRnumber;
		
		private int _DestinationID;
		
		private int _GroupID;
		
		private string _LicenseName;
		
		private byte _LicenseType;
		
		private string _LicenseInfo;
		
		private string _LicenseComments;
		
		private int _OrderIndex;
		
		private EntitySet<TransactionTable> _Transactions;
		
		private EntitySet<OrderTable> _Orders;
		
		private EntitySet<TokenTable> _TokenTables;
		
		private EntitySet<PacketTable> _PacketTables;
		
		private EntityRef<CustomerTable> _SCustomerRecord;
		
		private bool serializing;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnSCRnumberChanging(int value);
    partial void OnSCRnumberChanged();
    partial void OnDestinationIDChanging(int value);
    partial void OnDestinationIDChanged();
    partial void OnGroupIDChanging(int value);
    partial void OnGroupIDChanged();
    partial void OnLicenseNameChanging(string value);
    partial void OnLicenseNameChanged();
    partial void OnLicenseTypeChanging(byte value);
    partial void OnLicenseTypeChanged();
    partial void OnLicenseInfoChanging(string value);
    partial void OnLicenseInfoChanged();
    partial void OnLicenseCommentsChanging(string value);
    partial void OnLicenseCommentsChanged();
    partial void OnOrderIndexChanging(int value);
    partial void OnOrderIndexChanged();
    #endregion
		
		public LicenseTable()
		{
			this.Initialize();
		}
		
		[Column(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		[DataMember(Order=1)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[Column(Storage="_SCRnumber", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		[DataMember(Order=2)]
		public int SCRnumber
		{
			get
			{
				return this._SCRnumber;
			}
			set
			{
				if ((this._SCRnumber != value))
				{
					if (this._SCustomerRecord.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSCRnumberChanging(value);
					this.SendPropertyChanging();
					this._SCRnumber = value;
					this.SendPropertyChanged("SCRnumber");
					this.OnSCRnumberChanged();
				}
			}
		}
		
		[Column(Storage="_DestinationID", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		[DataMember(Order=3)]
		public int DestinationID
		{
			get
			{
				return this._DestinationID;
			}
			set
			{
				if ((this._DestinationID != value))
				{
					this.OnDestinationIDChanging(value);
					this.SendPropertyChanging();
					this._DestinationID = value;
					this.SendPropertyChanged("DestinationID");
					this.OnDestinationIDChanged();
				}
			}
		}
		
		[Column(Storage="_GroupID", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		[DataMember(Order=4)]
		public int GroupID
		{
			get
			{
				return this._GroupID;
			}
			set
			{
				if ((this._GroupID != value))
				{
					this.OnGroupIDChanging(value);
					this.SendPropertyChanging();
					this._GroupID = value;
					this.SendPropertyChanged("GroupID");
					this.OnGroupIDChanged();
				}
			}
		}
		
		[Column(Storage="_LicenseName", DbType="VarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		[DataMember(Order=5)]
		public string LicenseName
		{
			get
			{
				return this._LicenseName;
			}
			set
			{
				if ((this._LicenseName != value))
				{
					this.OnLicenseNameChanging(value);
					this.SendPropertyChanging();
					this._LicenseName = value;
					this.SendPropertyChanged("LicenseName");
					this.OnLicenseNameChanged();
				}
			}
		}
		
		[Column(Storage="_LicenseType", DbType="TinyInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		[DataMember(Order=6)]
		public byte LicenseType
		{
			get
			{
				return this._LicenseType;
			}
			set
			{
				if ((this._LicenseType != value))
				{
					this.OnLicenseTypeChanging(value);
					this.SendPropertyChanging();
					this._LicenseType = value;
					this.SendPropertyChanged("LicenseType");
					this.OnLicenseTypeChanged();
				}
			}
		}
		
		[Column(Storage="_LicenseInfo", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		[DataMember(Order=7)]
		public string LicenseInfo
		{
			get
			{
				return this._LicenseInfo;
			}
			set
			{
				if ((this._LicenseInfo != value))
				{
					this.OnLicenseInfoChanging(value);
					this.SendPropertyChanging();
					this._LicenseInfo = value;
					this.SendPropertyChanged("LicenseInfo");
					this.OnLicenseInfoChanged();
				}
			}
		}
		
		[Column(Storage="_LicenseComments", DbType="VarChar(255)", UpdateCheck=UpdateCheck.Never)]
		[DataMember(Order=8)]
		public string LicenseComments
		{
			get
			{
				return this._LicenseComments;
			}
			set
			{
				if ((this._LicenseComments != value))
				{
					this.OnLicenseCommentsChanging(value);
					this.SendPropertyChanging();
					this._LicenseComments = value;
					this.SendPropertyChanged("LicenseComments");
					this.OnLicenseCommentsChanged();
				}
			}
		}
		
		[Column(Storage="_OrderIndex", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		[DataMember(Order=9)]
		public int OrderIndex
		{
			get
			{
				return this._OrderIndex;
			}
			set
			{
				if ((this._OrderIndex != value))
				{
					this.OnOrderIndexChanging(value);
					this.SendPropertyChanging();
					this._OrderIndex = value;
					this.SendPropertyChanged("OrderIndex");
					this.OnOrderIndexChanged();
				}
			}
		}
		
		[Association(Name="LicenseTable_TransactionTable", Storage="_Transactions", ThisKey="ID", OtherKey="taLicenseID")]
		[DataMember(Order=10, EmitDefaultValue=false)]
		public EntitySet<TransactionTable> TransactionTables
		{
			get
			{
				if ((this.serializing 
							&& (this._Transactions.HasLoadedOrAssignedValues == false)))
				{
					return null;
				}
				return this._Transactions;
			}
			set
			{
				this._Transactions.Assign(value);
			}
		}
		
		[Association(Name="LicenseTable_OrderTable", Storage="_Orders", ThisKey="ID", OtherKey="LicenseID")]
		[DataMember(Order=11, EmitDefaultValue=false)]
		public EntitySet<OrderTable> OrderTables
		{
			get
			{
				if ((this.serializing 
							&& (this._Orders.HasLoadedOrAssignedValues == false)))
				{
					return null;
				}
				return this._Orders;
			}
			set
			{
				this._Orders.Assign(value);
			}
		}
		
		[Association(Name="LicenseTable_TokenTable", Storage="_TokenTables", ThisKey="ID", OtherKey="LicenseID")]
		[DataMember(Order=12, EmitDefaultValue=false)]
		public EntitySet<TokenTable> TokenTables
		{
			get
			{
				if ((this.serializing 
							&& (this._TokenTables.HasLoadedOrAssignedValues == false)))
				{
					return null;
				}
				return this._TokenTables;
			}
			set
			{
				this._TokenTables.Assign(value);
			}
		}
		
		[Association(Name="LicenseTable_PacketTable", Storage="_PacketTables", ThisKey="ID", OtherKey="LicenseID")]
		[DataMember(Order=13, EmitDefaultValue=false)]
		public EntitySet<PacketTable> PacketTables
		{
			get
			{
				if ((this.serializing 
							&& (this._PacketTables.HasLoadedOrAssignedValues == false)))
				{
					return null;
				}
				return this._PacketTables;
			}
			set
			{
				this._PacketTables.Assign(value);
			}
		}
		
		[Association(Name="CustomerTable_LicenseTable", Storage="_SCustomerRecord", ThisKey="SCRnumber", OtherKey="SCRnumber", IsForeignKey=true)]
		public CustomerTable CustomerTable
		{
			get
			{
				return this._SCustomerRecord.Entity;
			}
			set
			{
				CustomerTable previousValue = this._SCustomerRecord.Entity;
				if (((previousValue != value) 
							|| (this._SCustomerRecord.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SCustomerRecord.Entity = null;
						previousValue.LicenseTables.Remove(this);
					}
					this._SCustomerRecord.Entity = value;
					if ((value != null))
					{
						value.LicenseTables.Add(this);
						this._SCRnumber = value.SCRnumber;
					}
					else
					{
						this._SCRnumber = default(int);
					}
					this.SendPropertyChanged("CustomerTable");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Transactions(TransactionTable entity)
		{
			this.SendPropertyChanging();
			entity.LicenseTable = this;
		}
		
		private void detach_Transactions(TransactionTable entity)
		{
			this.SendPropertyChanging();
			entity.LicenseTable = null;
		}
		
		private void attach_Orders(OrderTable entity)
		{
			this.SendPropertyChanging();
			entity.LicenseTable = this;
		}
		
		private void detach_Orders(OrderTable entity)
		{
			this.SendPropertyChanging();
			entity.LicenseTable = null;
		}
		
		private void attach_TokenTables(TokenTable entity)
		{
			this.SendPropertyChanging();
			entity.LicenseTable = this;
		}
		
		private void detach_TokenTables(TokenTable entity)
		{
			this.SendPropertyChanging();
			entity.LicenseTable = null;
		}
		
		private void attach_PacketTables(PacketTable entity)
		{
			this.SendPropertyChanging();
			entity.LicenseTable = this;
		}
		
		private void detach_PacketTables(PacketTable entity)
		{
			this.SendPropertyChanging();
			entity.LicenseTable = null;
		}
		
		private void Initialize()
		{
			this._Transactions = new EntitySet<TransactionTable>(new Action<TransactionTable>(this.attach_Transactions), new Action<TransactionTable>(this.detach_Transactions));
			this._Orders = new EntitySet<OrderTable>(new Action<OrderTable>(this.attach_Orders), new Action<OrderTable>(this.detach_Orders));
			this._TokenTables = new EntitySet<TokenTable>(new Action<TokenTable>(this.attach_TokenTables), new Action<TokenTable>(this.detach_TokenTables));
			this._PacketTables = new EntitySet<PacketTable>(new Action<PacketTable>(this.attach_PacketTables), new Action<PacketTable>(this.detach_PacketTables));
			this._SCustomerRecord = default(EntityRef<CustomerTable>);
			OnCreated();
		}
		
		[OnDeserializing()]
		[System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
		
		[OnSerializing()]
		[System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerializing(StreamingContext context)
		{
			this.serializing = true;
		}
		
		[OnSerialized()]
		[System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerialized(StreamingContext context)
		{
			this.serializing = false;
		}
	}
	
	[Table(Name="[CORP\\AChou].[Order]")]
	[DataContract()]
	public partial class OrderTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _OrderIndex;
		
		private string _OrderNumber;
		
		private byte _OrderState;
		
		private int _LicenseID;
		
		private System.Nullable<System.DateTime> _ExpirationDate;
		
		private string _Description;
		
		private string _ProductName;
		
		private string _ProductVersion;
		
		private string _ParentOrderNumber;
		
		private EntityRef<LicenseTable> _License;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnOrderIndexChanging(int value);
    partial void OnOrderIndexChanged();
    partial void OnOrderNumberChanging(string value);
    partial void OnOrderNumberChanged();
    partial void OnOrderStateChanging(byte value);
    partial void OnOrderStateChanged();
    partial void OnLicenseIDChanging(int value);
    partial void OnLicenseIDChanged();
    partial void OnExpirationDateChanging(System.Nullable<System.DateTime> value);
    partial void OnExpirationDateChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnProductNameChanging(string value);
    partial void OnProductNameChanged();
    partial void OnProductVersionChanging(string value);
    partial void OnProductVersionChanged();
    partial void OnParentOrderNumberChanging(string value);
    partial void OnParentOrderNumberChanged();
    #endregion
		
		public OrderTable()
		{
			this.Initialize();
		}
		
		[Column(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		[DataMember(Order=1)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[Column(Storage="_OrderIndex", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		[DataMember(Order=2)]
		public int OrderIndex
		{
			get
			{
				return this._OrderIndex;
			}
			set
			{
				if ((this._OrderIndex != value))
				{
					this.OnOrderIndexChanging(value);
					this.SendPropertyChanging();
					this._OrderIndex = value;
					this.SendPropertyChanged("OrderIndex");
					this.OnOrderIndexChanged();
				}
			}
		}
		
		[Column(Storage="_OrderNumber", DbType="VarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		[DataMember(Order=3)]
		public string OrderNumber
		{
			get
			{
				return this._OrderNumber;
			}
			set
			{
				if ((this._OrderNumber != value))
				{
					this.OnOrderNumberChanging(value);
					this.SendPropertyChanging();
					this._OrderNumber = value;
					this.SendPropertyChanged("OrderNumber");
					this.OnOrderNumberChanged();
				}
			}
		}
		
		[Column(Storage="_OrderState", DbType="TinyInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		[DataMember(Order=4)]
		public byte OrderState
		{
			get
			{
				return this._OrderState;
			}
			set
			{
				if ((this._OrderState != value))
				{
					this.OnOrderStateChanging(value);
					this.SendPropertyChanging();
					this._OrderState = value;
					this.SendPropertyChanged("OrderState");
					this.OnOrderStateChanged();
				}
			}
		}
		
		[Column(Storage="_LicenseID", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		[DataMember(Order=5)]
		public int LicenseID
		{
			get
			{
				return this._LicenseID;
			}
			set
			{
				if ((this._LicenseID != value))
				{
					if (this._License.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnLicenseIDChanging(value);
					this.SendPropertyChanging();
					this._LicenseID = value;
					this.SendPropertyChanged("LicenseID");
					this.OnLicenseIDChanged();
				}
			}
		}
		
		[Column(Storage="_ExpirationDate", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		[DataMember(Order=6)]
		public System.Nullable<System.DateTime> ExpirationDate
		{
			get
			{
				return this._ExpirationDate;
			}
			set
			{
				if ((this._ExpirationDate != value))
				{
					this.OnExpirationDateChanging(value);
					this.SendPropertyChanging();
					this._ExpirationDate = value;
					this.SendPropertyChanged("ExpirationDate");
					this.OnExpirationDateChanged();
				}
			}
		}
		
		[Column(Storage="_Description", DbType="VarChar(100)", UpdateCheck=UpdateCheck.Never)]
		[DataMember(Order=7)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[Column(Storage="_ProductName", DbType="VarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		[DataMember(Order=8)]
		public string ProductName
		{
			get
			{
				return this._ProductName;
			}
			set
			{
				if ((this._ProductName != value))
				{
					this.OnProductNameChanging(value);
					this.SendPropertyChanging();
					this._ProductName = value;
					this.SendPropertyChanged("ProductName");
					this.OnProductNameChanged();
				}
			}
		}
		
		[Column(Storage="_ProductVersion", DbType="VarChar(10) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		[DataMember(Order=9)]
		public string ProductVersion
		{
			get
			{
				return this._ProductVersion;
			}
			set
			{
				if ((this._ProductVersion != value))
				{
					this.OnProductVersionChanging(value);
					this.SendPropertyChanging();
					this._ProductVersion = value;
					this.SendPropertyChanged("ProductVersion");
					this.OnProductVersionChanged();
				}
			}
		}
		
		[Column(Storage="_ParentOrderNumber", DbType="VarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		[DataMember(Order=10)]
		public string ParentOrderNumber
		{
			get
			{
				return this._ParentOrderNumber;
			}
			set
			{
				if ((this._ParentOrderNumber != value))
				{
					this.OnParentOrderNumberChanging(value);
					this.SendPropertyChanging();
					this._ParentOrderNumber = value;
					this.SendPropertyChanged("ParentOrderNumber");
					this.OnParentOrderNumberChanged();
				}
			}
		}
		
		[Association(Name="LicenseTable_OrderTable", Storage="_License", ThisKey="LicenseID", OtherKey="ID", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public LicenseTable LicenseTable
		{
			get
			{
				return this._License.Entity;
			}
			set
			{
				LicenseTable previousValue = this._License.Entity;
				if (((previousValue != value) 
							|| (this._License.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._License.Entity = null;
						previousValue.OrderTables.Remove(this);
					}
					this._License.Entity = value;
					if ((value != null))
					{
						value.OrderTables.Add(this);
						this._LicenseID = value.ID;
					}
					else
					{
						this._LicenseID = default(int);
					}
					this.SendPropertyChanged("LicenseTable");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			this._License = default(EntityRef<LicenseTable>);
			OnCreated();
		}
		
		[OnDeserializing()]
		[System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[Table(Name="dbo.sProducts")]
	[DataContract()]
	public partial class ProductTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _pId;
		
		private int _pVersion;
		
		private string _pName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnpIdChanging(int value);
    partial void OnpIdChanged();
    partial void OnpVersionChanging(int value);
    partial void OnpVersionChanged();
    partial void OnpNameChanging(string value);
    partial void OnpNameChanged();
    #endregion
		
		public ProductTable()
		{
			this.Initialize();
		}
		
		[Column(Storage="_pId", DbType="Int NOT NULL", IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		[DataMember(Order=1)]
		public int pId
		{
			get
			{
				return this._pId;
			}
			set
			{
				if ((this._pId != value))
				{
					this.OnpIdChanging(value);
					this.SendPropertyChanging();
					this._pId = value;
					this.SendPropertyChanged("pId");
					this.OnpIdChanged();
				}
			}
		}
		
		[Column(Storage="_pVersion", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		[DataMember(Order=2)]
		public int pVersion
		{
			get
			{
				return this._pVersion;
			}
			set
			{
				if ((this._pVersion != value))
				{
					this.OnpVersionChanging(value);
					this.SendPropertyChanging();
					this._pVersion = value;
					this.SendPropertyChanged("pVersion");
					this.OnpVersionChanged();
				}
			}
		}
		
		[Column(Storage="_pName", DbType="VarChar(50)", UpdateCheck=UpdateCheck.Never)]
		[DataMember(Order=3)]
		public string pName
		{
			get
			{
				return this._pName;
			}
			set
			{
				if ((this._pName != value))
				{
					this.OnpNameChanging(value);
					this.SendPropertyChanging();
					this._pName = value;
					this.SendPropertyChanged("pName");
					this.OnpNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[OnDeserializing()]
		[System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[Table(Name="dbo.PermissionsTable")]
	[DataContract()]
	public partial class PermissionsTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _pt_login;
		
		private System.Nullable<bool> _pt_create_modify_key;
		
		private System.Nullable<bool> _pt_extension_pwd;
		
		private System.Nullable<bool> _pt_version_pwd;
		
		private System.Nullable<bool> _pt_module_pwd;
		
		private System.Nullable<bool> _pt_permanent_pwd;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpt_loginChanging(string value);
    partial void Onpt_loginChanged();
    partial void Onpt_create_modify_keyChanging(System.Nullable<bool> value);
    partial void Onpt_create_modify_keyChanged();
    partial void Onpt_extension_pwdChanging(System.Nullable<bool> value);
    partial void Onpt_extension_pwdChanged();
    partial void Onpt_version_pwdChanging(System.Nullable<bool> value);
    partial void Onpt_version_pwdChanged();
    partial void Onpt_module_pwdChanging(System.Nullable<bool> value);
    partial void Onpt_module_pwdChanged();
    partial void Onpt_permanent_pwdChanging(System.Nullable<bool> value);
    partial void Onpt_permanent_pwdChanged();
    #endregion
		
		public PermissionsTable()
		{
			this.Initialize();
		}
		
		[Column(Storage="_pt_login", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		[DataMember(Order=1)]
		public string pt_login
		{
			get
			{
				return this._pt_login;
			}
			set
			{
				if ((this._pt_login != value))
				{
					this.Onpt_loginChanging(value);
					this.SendPropertyChanging();
					this._pt_login = value;
					this.SendPropertyChanged("pt_login");
					this.Onpt_loginChanged();
				}
			}
		}
		
		[Column(Storage="_pt_create_modify_key", DbType="Bit", UpdateCheck=UpdateCheck.Never)]
		[DataMember(Order=2)]
		public System.Nullable<bool> pt_create_modify_key
		{
			get
			{
				return this._pt_create_modify_key;
			}
			set
			{
				if ((this._pt_create_modify_key != value))
				{
					this.Onpt_create_modify_keyChanging(value);
					this.SendPropertyChanging();
					this._pt_create_modify_key = value;
					this.SendPropertyChanged("pt_create_modify_key");
					this.Onpt_create_modify_keyChanged();
				}
			}
		}
		
		[Column(Storage="_pt_extension_pwd", DbType="Bit", UpdateCheck=UpdateCheck.Never)]
		[DataMember(Order=3)]
		public System.Nullable<bool> pt_extension_pwd
		{
			get
			{
				return this._pt_extension_pwd;
			}
			set
			{
				if ((this._pt_extension_pwd != value))
				{
					this.Onpt_extension_pwdChanging(value);
					this.SendPropertyChanging();
					this._pt_extension_pwd = value;
					this.SendPropertyChanged("pt_extension_pwd");
					this.Onpt_extension_pwdChanged();
				}
			}
		}
		
		[Column(Storage="_pt_version_pwd", DbType="Bit", UpdateCheck=UpdateCheck.Never)]
		[DataMember(Order=4)]
		public System.Nullable<bool> pt_version_pwd
		{
			get
			{
				return this._pt_version_pwd;
			}
			set
			{
				if ((this._pt_version_pwd != value))
				{
					this.Onpt_version_pwdChanging(value);
					this.SendPropertyChanging();
					this._pt_version_pwd = value;
					this.SendPropertyChanged("pt_version_pwd");
					this.Onpt_version_pwdChanged();
				}
			}
		}
		
		[Column(Storage="_pt_module_pwd", DbType="Bit", UpdateCheck=UpdateCheck.Never)]
		[DataMember(Order=5)]
		public System.Nullable<bool> pt_module_pwd
		{
			get
			{
				return this._pt_module_pwd;
			}
			set
			{
				if ((this._pt_module_pwd != value))
				{
					this.Onpt_module_pwdChanging(value);
					this.SendPropertyChanging();
					this._pt_module_pwd = value;
					this.SendPropertyChanged("pt_module_pwd");
					this.Onpt_module_pwdChanged();
				}
			}
		}
		
		[Column(Storage="_pt_permanent_pwd", DbType="Bit", UpdateCheck=UpdateCheck.Never)]
		[DataMember(Order=6)]
		public System.Nullable<bool> pt_permanent_pwd
		{
			get
			{
				return this._pt_permanent_pwd;
			}
			set
			{
				if ((this._pt_permanent_pwd != value))
				{
					this.Onpt_permanent_pwdChanging(value);
					this.SendPropertyChanging();
					this._pt_permanent_pwd = value;
					this.SendPropertyChanged("pt_permanent_pwd");
					this.Onpt_permanent_pwdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[OnDeserializing()]
		[System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[Table(Name="[CORP\\AChou].Token")]
	[DataContract()]
	public partial class TokenTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _LicenseID;
		
		private byte _TokenType;
		
		private string _TokenValue;
		
		private int _CustID;
		
		private byte _TokenStatus;
		
		private EntityRef<LicenseTable> _LicenseTable;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnLicenseIDChanging(int value);
    partial void OnLicenseIDChanged();
    partial void OnTokenTypeChanging(byte value);
    partial void OnTokenTypeChanged();
    partial void OnTokenValueChanging(string value);
    partial void OnTokenValueChanged();
    partial void OnCustIDChanging(int value);
    partial void OnCustIDChanged();
    partial void OnTokenStatusChanging(byte value);
    partial void OnTokenStatusChanged();
    #endregion
		
		public TokenTable()
		{
			this.Initialize();
		}
		
		[Column(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		[DataMember(Order=1)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[Column(Storage="_LicenseID", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		[DataMember(Order=2)]
		public int LicenseID
		{
			get
			{
				return this._LicenseID;
			}
			set
			{
				if ((this._LicenseID != value))
				{
					if (this._LicenseTable.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnLicenseIDChanging(value);
					this.SendPropertyChanging();
					this._LicenseID = value;
					this.SendPropertyChanged("LicenseID");
					this.OnLicenseIDChanged();
				}
			}
		}
		
		[Column(Storage="_TokenType", DbType="TinyInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		[DataMember(Order=3)]
		public byte TokenType
		{
			get
			{
				return this._TokenType;
			}
			set
			{
				if ((this._TokenType != value))
				{
					this.OnTokenTypeChanging(value);
					this.SendPropertyChanging();
					this._TokenType = value;
					this.SendPropertyChanged("TokenType");
					this.OnTokenTypeChanged();
				}
			}
		}
		
		[Column(Storage="_TokenValue", DbType="VarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		[DataMember(Order=4)]
		public string TokenValue
		{
			get
			{
				return this._TokenValue;
			}
			set
			{
				if ((this._TokenValue != value))
				{
					this.OnTokenValueChanging(value);
					this.SendPropertyChanging();
					this._TokenValue = value;
					this.SendPropertyChanged("TokenValue");
					this.OnTokenValueChanged();
				}
			}
		}
		
		[Column(Storage="_CustID", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		[DataMember(Order=5)]
		public int CustID
		{
			get
			{
				return this._CustID;
			}
			set
			{
				if ((this._CustID != value))
				{
					this.OnCustIDChanging(value);
					this.SendPropertyChanging();
					this._CustID = value;
					this.SendPropertyChanged("CustID");
					this.OnCustIDChanged();
				}
			}
		}
		
		[Column(Storage="_TokenStatus", DbType="TinyInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		[DataMember(Order=6)]
		public byte TokenStatus
		{
			get
			{
				return this._TokenStatus;
			}
			set
			{
				if ((this._TokenStatus != value))
				{
					this.OnTokenStatusChanging(value);
					this.SendPropertyChanging();
					this._TokenStatus = value;
					this.SendPropertyChanged("TokenStatus");
					this.OnTokenStatusChanged();
				}
			}
		}
		
		[Association(Name="LicenseTable_TokenTable", Storage="_LicenseTable", ThisKey="LicenseID", OtherKey="ID", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public LicenseTable LicenseTable
		{
			get
			{
				return this._LicenseTable.Entity;
			}
			set
			{
				LicenseTable previousValue = this._LicenseTable.Entity;
				if (((previousValue != value) 
							|| (this._LicenseTable.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LicenseTable.Entity = null;
						previousValue.TokenTables.Remove(this);
					}
					this._LicenseTable.Entity = value;
					if ((value != null))
					{
						value.TokenTables.Add(this);
						this._LicenseID = value.ID;
					}
					else
					{
						this._LicenseID = default(int);
					}
					this.SendPropertyChanged("LicenseTable");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			this._LicenseTable = default(EntityRef<LicenseTable>);
			OnCreated();
		}
		
		[OnDeserializing()]
		[System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[Table(Name="[CORP\\AChou].Packet")]
	[DataContract()]
	public partial class PacketTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.DateTime _DateCreated;
		
		private string _PacketVerificationCode;
		
		private bool _IsVerified;
		
		private string _PacketComments;
		
		private string _PacketName;
		
		private int _LicenseID;
		
		private string _UserName;
		
		private System.DateTime _ExpiredDate;
		
		private string _VerifiedBy;
		
		private EntityRef<LicenseTable> _LicenseTable;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnDateCreatedChanging(System.DateTime value);
    partial void OnDateCreatedChanged();
    partial void OnPacketVerificationCodeChanging(string value);
    partial void OnPacketVerificationCodeChanged();
    partial void OnIsVerifiedChanging(bool value);
    partial void OnIsVerifiedChanged();
    partial void OnPacketCommentsChanging(string value);
    partial void OnPacketCommentsChanged();
    partial void OnPacketNameChanging(string value);
    partial void OnPacketNameChanged();
    partial void OnLicenseIDChanging(int value);
    partial void OnLicenseIDChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnExpiredDateChanging(System.DateTime value);
    partial void OnExpiredDateChanged();
    partial void OnVerifiedByChanging(string value);
    partial void OnVerifiedByChanged();
    #endregion
		
		public PacketTable()
		{
			this.Initialize();
		}
		
		[Column(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		[DataMember(Order=1)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[Column(Storage="_DateCreated", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		[DataMember(Order=2)]
		public System.DateTime DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				if ((this._DateCreated != value))
				{
					this.OnDateCreatedChanging(value);
					this.SendPropertyChanging();
					this._DateCreated = value;
					this.SendPropertyChanged("DateCreated");
					this.OnDateCreatedChanged();
				}
			}
		}
		
		[Column(Storage="_PacketVerificationCode", DbType="NVarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		[DataMember(Order=3)]
		public string PacketVerificationCode
		{
			get
			{
				return this._PacketVerificationCode;
			}
			set
			{
				if ((this._PacketVerificationCode != value))
				{
					this.OnPacketVerificationCodeChanging(value);
					this.SendPropertyChanging();
					this._PacketVerificationCode = value;
					this.SendPropertyChanged("PacketVerificationCode");
					this.OnPacketVerificationCodeChanged();
				}
			}
		}
		
		[Column(Storage="_IsVerified", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		[DataMember(Order=4)]
		public bool IsVerified
		{
			get
			{
				return this._IsVerified;
			}
			set
			{
				if ((this._IsVerified != value))
				{
					this.OnIsVerifiedChanging(value);
					this.SendPropertyChanging();
					this._IsVerified = value;
					this.SendPropertyChanged("IsVerified");
					this.OnIsVerifiedChanged();
				}
			}
		}
		
		[Column(Storage="_PacketComments", DbType="VarChar(255)", UpdateCheck=UpdateCheck.Never)]
		[DataMember(Order=5)]
		public string PacketComments
		{
			get
			{
				return this._PacketComments;
			}
			set
			{
				if ((this._PacketComments != value))
				{
					this.OnPacketCommentsChanging(value);
					this.SendPropertyChanging();
					this._PacketComments = value;
					this.SendPropertyChanged("PacketComments");
					this.OnPacketCommentsChanged();
				}
			}
		}
		
		[Column(Storage="_PacketName", DbType="VarChar(128) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		[DataMember(Order=6)]
		public string PacketName
		{
			get
			{
				return this._PacketName;
			}
			set
			{
				if ((this._PacketName != value))
				{
					this.OnPacketNameChanging(value);
					this.SendPropertyChanging();
					this._PacketName = value;
					this.SendPropertyChanged("PacketName");
					this.OnPacketNameChanged();
				}
			}
		}
		
		[Column(Storage="_LicenseID", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		[DataMember(Order=7)]
		public int LicenseID
		{
			get
			{
				return this._LicenseID;
			}
			set
			{
				if ((this._LicenseID != value))
				{
					if (this._LicenseTable.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnLicenseIDChanging(value);
					this.SendPropertyChanging();
					this._LicenseID = value;
					this.SendPropertyChanged("LicenseID");
					this.OnLicenseIDChanged();
				}
			}
		}
		
		[Column(Storage="_UserName", DbType="VarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		[DataMember(Order=8)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[Column(Storage="_ExpiredDate", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		[DataMember(Order=9)]
		public System.DateTime ExpiredDate
		{
			get
			{
				return this._ExpiredDate;
			}
			set
			{
				if ((this._ExpiredDate != value))
				{
					this.OnExpiredDateChanging(value);
					this.SendPropertyChanging();
					this._ExpiredDate = value;
					this.SendPropertyChanged("ExpiredDate");
					this.OnExpiredDateChanged();
				}
			}
		}
		
		[Column(Storage="_VerifiedBy", DbType="VarChar(50)", UpdateCheck=UpdateCheck.Never)]
		[DataMember(Order=10)]
		public string VerifiedBy
		{
			get
			{
				return this._VerifiedBy;
			}
			set
			{
				if ((this._VerifiedBy != value))
				{
					this.OnVerifiedByChanging(value);
					this.SendPropertyChanging();
					this._VerifiedBy = value;
					this.SendPropertyChanged("VerifiedBy");
					this.OnVerifiedByChanged();
				}
			}
		}
		
		[Association(Name="LicenseTable_PacketTable", Storage="_LicenseTable", ThisKey="LicenseID", OtherKey="ID", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public LicenseTable LicenseTable
		{
			get
			{
				return this._LicenseTable.Entity;
			}
			set
			{
				LicenseTable previousValue = this._LicenseTable.Entity;
				if (((previousValue != value) 
							|| (this._LicenseTable.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LicenseTable.Entity = null;
						previousValue.PacketTables.Remove(this);
					}
					this._LicenseTable.Entity = value;
					if ((value != null))
					{
						value.PacketTables.Add(this);
						this._LicenseID = value.ID;
					}
					else
					{
						this._LicenseID = default(int);
					}
					this.SendPropertyChanged("LicenseTable");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			this._LicenseTable = default(EntityRef<LicenseTable>);
			OnCreated();
		}
		
		[OnDeserializing()]
		[System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[Table(Name="[CORP\\AChou].DestinationName")]
	[DataContract()]
	public partial class DestinationNameTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _CustID;
		
		private int _DestID;
		
		private string _DestName;
		
		private EntityRef<CustomerTable> _CustomerTable;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCustIDChanging(int value);
    partial void OnCustIDChanged();
    partial void OnDestIDChanging(int value);
    partial void OnDestIDChanged();
    partial void OnDestNameChanging(string value);
    partial void OnDestNameChanged();
    #endregion
		
		public DestinationNameTable()
		{
			this.Initialize();
		}
		
		[Column(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		[DataMember(Order=1)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[Column(Storage="_CustID", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		[DataMember(Order=2)]
		public int CustID
		{
			get
			{
				return this._CustID;
			}
			set
			{
				if ((this._CustID != value))
				{
					if (this._CustomerTable.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCustIDChanging(value);
					this.SendPropertyChanging();
					this._CustID = value;
					this.SendPropertyChanged("CustID");
					this.OnCustIDChanged();
				}
			}
		}
		
		[Column(Storage="_DestID", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		[DataMember(Order=3)]
		public int DestID
		{
			get
			{
				return this._DestID;
			}
			set
			{
				if ((this._DestID != value))
				{
					this.OnDestIDChanging(value);
					this.SendPropertyChanging();
					this._DestID = value;
					this.SendPropertyChanged("DestID");
					this.OnDestIDChanged();
				}
			}
		}
		
		[Column(Storage="_DestName", DbType="VarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		[DataMember(Order=4)]
		public string DestName
		{
			get
			{
				return this._DestName;
			}
			set
			{
				if ((this._DestName != value))
				{
					this.OnDestNameChanging(value);
					this.SendPropertyChanging();
					this._DestName = value;
					this.SendPropertyChanged("DestName");
					this.OnDestNameChanged();
				}
			}
		}
		
		[Association(Name="CustomerTable_DestinationName", Storage="_CustomerTable", ThisKey="CustID", OtherKey="SCRnumber", IsForeignKey=true)]
		public CustomerTable CustomerTable
		{
			get
			{
				return this._CustomerTable.Entity;
			}
			set
			{
				CustomerTable previousValue = this._CustomerTable.Entity;
				if (((previousValue != value) 
							|| (this._CustomerTable.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CustomerTable.Entity = null;
						previousValue.DestinationNameTables.Remove(this);
					}
					this._CustomerTable.Entity = value;
					if ((value != null))
					{
						value.DestinationNameTables.Add(this);
						this._CustID = value.SCRnumber;
					}
					else
					{
						this._CustID = default(int);
					}
					this.SendPropertyChanged("CustomerTable");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			this._CustomerTable = default(EntityRef<CustomerTable>);
			OnCreated();
		}
		
		[OnDeserializing()]
		[System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
}
#pragma warning restore 1591
