// CSpdAttribsBase4.h - Implements Attributes v4 base functionality.
//
// SLB 11.jun.2024 CR.32662.V03; Imported from SPDE and modified to work in the 
// Licensing environment.
//
// SLB 14.jun.2012 CR.15891.V02; Changes made to help with supporting Aliased Resource attrib members.
// Also, changed name of type SAttribMemberMap to TAttribMemberMap. This forced changes in python scripts.
// SLB 11.apr.2013 CR.15891.V04; Added Alias types. Most recently. TAliasAfpdsSharedResource.
// SLB 07.feb.2023 CR.32082.V00.02; FILETIME has muliple possible definitions when 
// compiled under managed C++. Prepended "::" in front to specify the global scope.
// SLB 28.jan.2025 CR.33570.V01; Changes to keep code in sync with SPDE code... 
// Specifically, ISO C++ 20, Conformance Mode = Yes, support.
//
#pragma once
#ifndef _CSpdAttribsBase4_h																			// CR.33897; added.
#define _CSpdAttribsBase4_h																			// CR.33897; added.

#include "..\FromSpd\L_SSILib1Dll.h"
#include <atlbase.h>
#include <atltime.h>
#include <atlcomcli.h>
#include <atlsafe.h>
#include <atlstr.h>
#include <oleauto.h>																						// CR.34222;added.
#include <map>
#include <list>
#include <vector>
#include <string>                                                                   // CR.30115; added.
#include <guiddef.h>
#include "..\FromSpd\L_quadword.h"
#include "..\FromSpd\L_CBuffer.h"
#include <assert.h>
#include "..\FromSpd\L_SpdUtils.h"
#include "..\FromSpd\L_SpdDefines.h"
#include "..\FromSpd\L_SpdStreamable4.h"
#include "..\FromSpd\L_CAliasableResourceString.h"												// CR.15891.V02; added.
#include "..\FromSpd\L_CSpdCrypto.h"                                                // CR.19280; added.
#include "..\FromSpd\L_SpdException.h"
#include "..\FromSpd\L_CSpdJobTransaction.h"
#include "..\FromSpd\L_CSpdblock.h"
#include "..\FromSpd\L_CNtfsFolderName.h"                                           // CR.17862.V05; added.

// header required for throwing std::out_of_range exception.
#include <stdexcept>                                                                // CR.30115; added.

typedef enum TEnginePropertyIds; 
typedef enum DBSpoolJobAttributeID;                                                 // CR.28730; added.

//
// Version 4 of this functionality.
//    Generates leaner XML
//    Can m_bIsModified/Deserialize in compatiblity format (version 3)
//    Has a much smaller memory footprint.
//    Is much more efficient allocating/deallocating object.
//    Simpler template classes.
//
//    This code presumes that there are 3 primitive types (this number may grow):
//       1) QUADWORD             (simple primitive)
//       2) CSpdCString          (simple primitive)
//       3) CStreamableIf        (complex primitive)
//       4) double               // CR.21547
//    There are three basic template functions which are used to m_bIsModified/Deserialize these 
//    primitives.
//       1) PrimitiveSerialize()
//       2) PrimitiveMaxSerializeLen()
//       3) PrimitiveDeserialize()
//    Each template function defines generic operation which will work with any type that can be 
//    cast to a QUADWORD.
//    Additionally, each function has specific implementations for CSpdCString and CStreamableIf.
//    This number may grow.
//
//    These are the building blocks for the more complex constructs which are all derived from CStreamableIf primitive class.
//    At this time there are two fixed template classes for containers (std::list and std::map) and a 
//    Base class (CAttributes) for attribs classes generated by the attribs compiler.
// 
//    All attribs classes will be derived from CAttributes. 
//    It has its own mechanism for managing attribute properties which must be followed by python generated
//    code.
//

using namespace SpdJobTransaction;
using namespace SpdStreamable;
using namespace SpdUtils;                                                           // CR.27916; added.

namespace SpdAttribs4
{

using namespace SpdException; 


/* ReallocateWcsBuffer() - 
 *
 * SLB 06.feb.2008 Modified to catch memory allocation exception.
---------------------------------------------------------------------------*/
inline wchar_t *ReallocateWcsBuffer(
   wchar_t *pwcBufferToCopy, 
   size_t stBuffSize, 
   size_t &stNewBufSize,
   bool bFreeCopyBufferOnError,
   bool bDontCopy = false)
{
   wchar_t *pwcNewBuffer(NULL); 
   stNewBufSize = pwcBufferToCopy ? 2*stBuffSize : stBuffSize; 
   try
   {
      pwcNewBuffer = new wchar_t[stNewBufSize]; 
   }
   catch (...)
   {
   }
   if (!pwcNewBuffer)
   {  
      // problem: failed to allocate a new buffer.
      if (bFreeCopyBufferOnError && pwcBufferToCopy!=NULL)
      {
         delete [](pwcBufferToCopy); 
         sol_assert(pwcNewBuffer!=NULL); 
      }
   }
   else
   {
      pwcNewBuffer[0] = 0; 
      if (pwcBufferToCopy!=NULL)
      {
         if (pwcNewBuffer && !bDontCopy)
         {
            wmemcpy(pwcNewBuffer, pwcBufferToCopy, stBuffSize); 
         }
         delete [](pwcBufferToCopy); 
      }
   }
   return pwcNewBuffer; 
}


/*
 * class CStreamableIf:
 *
 * Note: m_wsTagName and m_bUsingLegacyXml are not values that should be propogated with the copy constructor or
 * the assignment operator, as each object needs to keep these identifiers static.
 * SLB 20.oct.2016 CR.22414; Modified the copy constructor such that a tagname must be passed in. It will no longer
 * use the copy object to determine this if the value is empty.
 * SLB 18.jan.2023 CR.32082; changes in initialization of members by constructor to
 * eliminate compiler warning msg 26495.
*/
class SSILIB1_EXPORT CStreamableIf
{
private:
   CSpdCString m_wsTagName; 
   bool m_bUsingLegacyXml; 

protected:
   bool m_bIsModified; 

public:
   CStreamableIf(
      const CSpdCString &wsTagName = CSpdCString(),
      bool bUseLegacyXml = false
      ) :
      m_wsTagName(wsTagName),
      m_bUsingLegacyXml(bUseLegacyXml),
      m_bIsModified(false) 
   {
   }
   CStreamableIf(const CStreamableIf &cpy, const CSpdCString &wsTag) :              // CR.22414; modified.
      m_bIsModified(cpy.m_bIsModified),
      m_bUsingLegacyXml(false),                                                     // CR.32082; added.
      m_wsTagName(wsTag)                                                            // CR.22414; added.
   {
   }
   CStreamableIf & operator = (const CStreamableIf &cpy) 
   {
      m_bIsModified = cpy.m_bIsModified; 
      return *this; 
   }
   bool IsUsingLegacyXml() const { return m_bUsingLegacyXml; } 
   CSpdCString GetTagName() const { return m_wsTagName; } 
   virtual CSpdCString GetContainerTag() const { return L""; } 

   // The following methods must be defined by all derived classes.
   //
   // XML Serializing/Deserializing methods.
   virtual size_t Serialize(wchar_t *pwcsBuf, size_t stBufCharLen, bool bUseTag, bool bUseContainerTag=true, bool bTransparentOn=false) const = 0; 
   virtual size_t GetMaxSerializeCharLen() const = 0; 
   virtual void Deserialize(const CSpdCString &wsXmlBuf, bool bTransparentOn=false, bool bClearFirst=true) = 0; 
   CSpdCString Serialize(bool bUseTag=true, bool bUseContainerTag=false) const
   {
      CSpdCString wsRetVal; 
      wchar_t *pwcsBuf(NULL); 
      size_t stBuffSize(0x4000); 
      while (stBuffSize>0) 
      {
         pwcsBuf = ReallocateWcsBuffer(
            pwcsBuf, 
            stBuffSize, 
            stBuffSize,
            true,
            true); 
         try 
         { 
            Serialize(pwcsBuf, stBuffSize, bUseTag, bUseContainerTag);  
            wsRetVal = pwcsBuf; 
            delete[] (pwcsBuf); 
            return wsRetVal; 
         }
         catch (...) {}
      }
      return L"Unable to Serialize."; 
   }
   //
   // Methods which may be over-ridden by derived classes.
   //
   virtual size_t SerializeBegin(wchar_t *pwcsBuf, size_t stBufCharLen, bool bUseTag, bool bUseContainerTag) const; 
   virtual size_t SerializeEnd(wchar_t *pwcsBuf, size_t stBufCharLen, bool bUseTag, bool bUseContainerTag) const; 
   //
   // methods to indicate/change Modified state.
   //
   virtual bool IsModified() const 
   { 
      return m_bIsModified;  
   }  
   virtual void ClearModified() 
   { 
      m_bIsModified = false;  
   } 
   virtual void Clear()
   {
      ClearModified(); 
   }
   //
   // Helper methods for derived classes.
   // Returns the length of the data searched.
   //
   static size_t FindDataForTags(
      const CSpdCString &wsTag, 
      const CSpdCString &wsData,
      CSpdCString &wsOutVal,
      bool bKeepTags = false,
      size_t stSearchStartPos = 0); 
}; 

SSILIB1_EXPORT wchar_t * AllocateAndStreamProperty(
   const CStreamableIf &Property, 
   size_t *pstCharCount,
   size_t stSuggestedBufSize = 4096,
   bool bUseTag = true,
   bool bUseContainerTag = false); 

inline wchar_t * AllocateAndStreamProperty(
   const CStreamableIf &Property) 
{
   size_t stCharCount(0); 
   return AllocateAndStreamProperty(Property, &stCharCount, 4096); 
}

class wstring_crypto : public std::wstring
{
public:
   wstring_crypto() : std::wstring() {}
   wstring_crypto(const wstring_crypto &ws) : std::wstring(ws) {}
   wstring_crypto(const std::wstring &ws) : std::wstring(ws) {}
   wstring_crypto(const wchar_t *pwcs) : std::wstring(pwcs) {}
   wstring_crypto &operator =(const std::wstring &ws) { std::wstring::operator =(ws); return *this; } 
}; 

template <class T>
class Primitive
{
public:
   bool m_bNumsInDec; 

   Primitive() : m_bNumsInDec(false) {}
   Primitive(bool bNumsInDec) : m_bNumsInDec(bNumsInDec) {}

   /*
    * Template function used to stream a primitive type (eg int, string, etc.) to a buffer. 
    * Currently, it is presumed that all numeric types (signed or otherwise) will use the 
    * default implementation. CSpdCString types are over ridden in a partial implementation.
    */
   size_t Serialize(const T &tVal, wchar_t *pwcsBuf, size_t stBufLen, bool bTransparentOn = false)
   {
      QUADWORD qw((QUADWORD)tVal); 
      return SSerialize(qw, pwcsBuf, stBufLen, m_bNumsInDec); 
   }

   /*
    * Template function used to determine max length of the primitive type(eg int, string, etc.) if it were streamed to a buffer. 
    * Currently, it is presumed that all numeric types (signed or otherwise) will use the 
    * default implementation. CSpdCString types are over ridden in a partial implementation.
    */
   size_t MaxSerializeLen(const T &tVal)
   {
      return SMaxSerializeLen((QUADWORD)tVal, m_bNumsInDec);                        // CR.21547; modified.
   }

   /*
    * Template function used to 
    */
   void Deserialize(const CSpdCString &wsStreamed, T &tVal, bool bTransparentOn = false)
   {
      QUADWORD qw; 
      SDeserialize(wsStreamed, qw, m_bNumsInDec); 
      tVal = (T)qw; 
   }
   //
   // static methods.
   //
   // T = QUADWORD
   //
   static size_t SSerialize(const QUADWORD &tVal, wchar_t *pwcsBuf, size_t stBufLen, bool bNumsInDec)
   {
      int nWriteLen(0); 
      nWriteLen = _snwprintf_s(pwcsBuf, stBufLen, _TRUNCATE,
         bNumsInDec ? L"%I64u" : L"%I64X",
         tVal); 
      if (nWriteLen < 0) ThrowHr(E_FAIL, __WFUNCTION__, L"Failed to convert QUADWORD to string. Buffer too small?"); 

      return (size_t)nWriteLen; 
   }
   static size_t SMaxSerializeLen(QUADWORD qw, bool bNumsInDec)
   {
      return 64; 
   }
   static void SDeserialize(const CSpdCString &wsStreamed, QUADWORD &tVal, bool bNumsInDec)
   {
      tVal = (QUADWORD)_wcstoui64(
         wsStreamed.c_str(), 
         NULL,
         bNumsInDec ? 10 : 16); 
   }
   //
   // CR.21547; added support for T = double
   //
   static size_t SSerialize(const double &tVal, wchar_t *pwcsBuf, size_t stBufLen)
   {
      int nWriteLen(0); 
      nWriteLen = _snwprintf_s(pwcsBuf, stBufLen, _TRUNCATE,
         L"%.3f",
         tVal); 
      if (nWriteLen < 0) ThrowHr(E_FAIL, __WFUNCTION__, L"Failed to convert QUADWORD to string. Buffer too small?"); 

      return (size_t)nWriteLen; 
   }
   static size_t SMaxSerializeLen(double db)
   {
      return 64; 
   }
   static void SDeserialize(const CSpdCString &wsStreamed, double &tVal)
   {
      tVal = wcstod(wsStreamed.c_str(), NULL); 
   }
   //
   // T = CSpdCString
   //
   static size_t SSerialize(const CSpdCString &tVal, wchar_t *pwcsBuf, size_t stBufLen, bool bTransparentOn = false)
   {
      // For performance of very long strings; do an initial check to see if buflen is too small.
      if (tVal.wcslen() > stBufLen) ThrowHr(E_FAIL, __WFUNCTION__, L"Failed to serialize CSpdCString. Buffer too small?\n   BufLen <0x%08zX>  wcslen <0x%08zX> IsTransparencyOn <%u>\n", stBufLen, tVal.wcslen(), bTransparentOn); 

      int nWriteLen(0); 
      nWriteLen = _snwprintf_s(pwcsBuf, stBufLen, _TRUNCATE, 
         L"%s",
         bTransparentOn ? tVal.c_str() : SpdUtils::XmlEscapeString(tVal).c_str()); 
      if (nWriteLen < 0) ThrowHr(E_FAIL, __WFUNCTION__, L"Failed to serialize CSpdCString. Buffer too small?\n   BufLen <0x%08zX>  wcslen <0x%08zX> IsTransparencyOn <%u>\n", stBufLen, tVal.wcslen(), bTransparentOn); 

      return (size_t)nWriteLen; 
   }
   static size_t SMaxSerializeLen(const CSpdCString &ws, bool bNumsInDec = false)
   {
      return ws.size() + 1; 
   }
   /* SDeserialize()
    * SLB 02.may.2016 CR.FIX.21516; Fix for not unescaping string when transparent mode is off (and visa-versa).
   -----------------------------------------------------------------------------------------------*/
   static void SDeserialize(const CSpdCString &wsStreamed, CSpdCString &tVal, bool bTransparentOn = false)
   {
      if (!bTransparentOn) SpdUtils::XmlUnescapeString(wsStreamed, tVal);           // CR.21516; modified.
      else tVal = wsStreamed; 
   }
   //
   // T = CResourceStringIF::TResourceType
   //
   static void SDeserialize(const CSpdCString &wsStreamed, CResourceStringIF::TResourceType &tVal, bool bNumsInDec = false)
   {
      QUADWORD qw; 
      SDeserialize(wsStreamed, qw, bNumsInDec); 
      tVal = (CResourceStringIF::TResourceType)qw; 
   }
   //
   // T = FILETIME
   //
   static size_t SSerialize(const ::FILETIME &tVal, wchar_t *pwcsBuf, size_t stBufLen, bool bNumsInDec)
   {
      //if (m_bIsStreamInLocalTime)
      //{
      //   FileTimeToLocalFileTime(&ftVal, &ftSystem); 
      //}
      SYSTEMTIME stVal; 
      FileTimeToSystemTime(&tVal, &stVal); 
      int nWriteLen(0); 
      nWriteLen = _snwprintf_s(pwcsBuf, stBufLen, _TRUNCATE, 
         L"%04d-%02d-%02d %02d:%02d:%02d.%04d",
         stVal.wYear,
         stVal.wMonth,
         stVal.wDay,
         stVal.wHour,
         stVal.wMinute,
         stVal.wSecond,
         stVal.wMilliseconds % 1000);                                               // CR.5729
      if (nWriteLen < 0) ThrowHr(E_FAIL, __WFUNCTION__, L"Failed to convert FILETIME to string. Buffer too small?"); 

      return (size_t)nWriteLen; 
   }
   static size_t SMaxSerializeLen(::FILETIME tVal, bool bNumsInDec)
   {
      return 25; 
   }
   static void SDeserialize(const CSpdCString &wsStreamed, ::FILETIME &tVal, bool bNumsInDec)
   {
      // Make a working copy of the const input buffer.
      wchar_t wcsCpy[25]; 
      wcscpy_s(wcsCpy, wsStreamed.c_str()); 

      // Set intermediate delimiters to NULL.
      wcsCpy[4] = wcsCpy[7] = wcsCpy[10] = wcsCpy[13] = wcsCpy[16] = wcsCpy[19] = wcsCpy[24] = 0; 

      // Now convert known fixed offsets to their appropriate values.
      wchar_t *pwcNull(NULL); 
      SYSTEMTIME stVal; 
      stVal.wYear =     (WORD)_wcstoi64(wcsCpy+0 , &pwcNull, 10); 
      stVal.wMonth =    (WORD)_wcstoi64(wcsCpy+5 , &pwcNull, 10); 
      stVal.wDay =      (WORD)_wcstoi64(wcsCpy+8 , &pwcNull, 10); 
      stVal.wHour =     (WORD)_wcstoi64(wcsCpy+11, &pwcNull, 10); 
      stVal.wMinute =   (WORD)_wcstoi64(wcsCpy+14, &pwcNull, 10); 
      stVal.wSecond =   (WORD)_wcstoi64(wcsCpy+17, &pwcNull, 10); 
      stVal.wMilliseconds = (WORD)_wcstoi64(wcsCpy+20, &pwcNull, 10) % 1000; 
      stVal.wDayOfWeek = 0; 

      if (SystemTimeToFileTime(&stVal, &tVal) == FALSE) ThrowHr(E_FAIL, __WFUNCTION__, L"Failed to deserialize FILETIME type."); 
   }

}; 


/* Serialize<T> - T = CSpdCString specific implementation for this template function.
 *
 -------------------------------------------------------------------------------------------*/
template <>
inline size_t Primitive<CSpdCString>::Serialize(const CSpdCString &tVal, wchar_t *pwcsBuf, size_t stBufLen, bool bTransparentOn)
{
   return SSerialize(tVal, pwcsBuf, stBufLen, bTransparentOn); 
}

/* MaxSerializeLen<T> - T = CSpdCString specific implementation for this template function.
 *
 ------------------------------------------------------------------------------------------*/
template <>
inline size_t Primitive<CSpdCString>::MaxSerializeLen(const CSpdCString &tVal)
{
   return SMaxSerializeLen(tVal);  
}

/* Deserialize<T> - T = CSpdCString specific implementation for this template function.
 *
 -------------------------------------------------------------------------------------------*/
template <>
inline void Primitive<CSpdCString>::Deserialize(const CSpdCString &wsStreamed, CSpdCString &tVal, bool bTransparentOn)
{
   SDeserialize(wsStreamed, tVal); 
}

/* Serialize<T> - T = double specific implementation for this template function.
 *
 * SLB 06.may.2016 CR.21547; created.
 -------------------------------------------------------------------------------------------*/
template <>
inline size_t Primitive<double>::Serialize(const double &tVal, wchar_t *pwcsBuf, size_t stBufLen, bool bTransparentOn)
{
   return SSerialize(tVal, pwcsBuf, stBufLen); 
}

/* MaxSerializeLen<T> - T = double specific implementation for this template function.
 *
 * SLB 06.may.2016 CR.21547; created.
 ------------------------------------------------------------------------------------------*/
template <>
inline size_t Primitive<double>::MaxSerializeLen(const double &tVal)
{
   return SMaxSerializeLen(tVal);  
}

/* Deserialize<T> - T = double specific implementation for this template function.
 *
 * SLB 06.may.2016 CR.21547; created.
 -------------------------------------------------------------------------------------------*/
template <>
inline void Primitive<double>::Deserialize(const CSpdCString &wsStreamed, double &tVal, bool bTransparentOn)
{
   SDeserialize(wsStreamed, tVal); 
}

/* Serialize<T> - T = wstring_crypto specific implementation for this template function.
 *
 * SLB 04.dec.2017 CR.24166; Fix for not throwing exception upon encryption error.
 -------------------------------------------------------------------------------------------*/
template <>
inline size_t Primitive<wstring_crypto>::Serialize(const wstring_crypto &tVal, wchar_t *pwcsBuf, size_t stBufLen, bool bTransparentOn)
{
   std::wstring wsEncrypted;
   HRESULT hr;
   hr = CSpdCrypto::EncryptString(tVal, wsEncrypted); 
   if (FAILED(hr)) ThrowHr(hr, __WFUNCTION__, L"Failed to encrypt buffer.");

   return SSerialize(CSpdCString(wsEncrypted.c_str()), pwcsBuf, stBufLen); 
}

/* MaxSerializeLen<T> - T = wstring_crypto specific implementation for this template function.
 *
 * SLB 06.may.2016 CR.21547; created.
 ------------------------------------------------------------------------------------------*/
template <>
inline size_t Primitive<wstring_crypto>::MaxSerializeLen(const wstring_crypto &tVal)
{
   return SMaxSerializeLen(tVal);  
}

/* Deserialize<T> - T = wstring_crypto specific implementation for this template function.
 *
 * SLB 04.dec.2017 CR.24166; Fix for not throwing exception upon decryption error.
 -------------------------------------------------------------------------------------------*/
template <>
inline void Primitive<wstring_crypto>::Deserialize(const CSpdCString &wsStreamed, wstring_crypto &tVal, bool bTransparentOn)
{
   CSpdCString wsVal; 
   SDeserialize(wsStreamed, wsVal); 

   HRESULT hr;
   hr = CSpdCrypto::DecryptString(wsVal.c_str(), tVal); 
   if (FAILED(hr)) ThrowHr(hr, __WFUNCTION__, L"Failed to decrypt value.");
}


/* Serialize<T> - T = CAliasableResourceStringBase specific implementation for this template function.
 *
 -------------------------------------------------------------------------------------------*/
template <>
inline size_t Primitive<CAliasableResourceStringBase>::Serialize(const CAliasableResourceStringBase &tVal, wchar_t *pwcsBuf, size_t stBufLen, bool bTransparentOn)
{
   // Streamed out version of this object looks like:
   //
   //   <t>1</t>
   //   <n>AB0934779523</n>
   size_t stWriteOff(0); 
   int nWriteLen(0); 
   nWriteLen = _snwprintf_s(pwcsBuf+stWriteOff, stBufLen-stWriteOff, _TRUNCATE,
      L"<t>"); 
   if (nWriteLen<0) ThrowHr(E_FAIL, __WFUNCTION__, L"Failed to serialize Aliasable Resource begin tag. Buffer too small?"); 
   stWriteOff += nWriteLen; 

   stWriteOff += SSerialize((QUADWORD)tVal.m_rtType, pwcsBuf+stWriteOff, stBufLen-stWriteOff, m_bNumsInDec);      // CR.21547; modified.

   nWriteLen = _snwprintf_s(pwcsBuf+stWriteOff, stBufLen-stWriteOff, _TRUNCATE,
      L"</t><n>"); 
   if (nWriteLen<0) ThrowHr(E_FAIL, __WFUNCTION__, L"Failed to serialize Aliasable Resource middle tags. Buffer too small?"); 
   stWriteOff += nWriteLen; 

   stWriteOff += SSerialize(tVal.m_wsFullResourceName, pwcsBuf+stWriteOff, stBufLen-stWriteOff); 

   nWriteLen = _snwprintf_s(pwcsBuf+stWriteOff, stBufLen-stWriteOff, _TRUNCATE,
      L"</n>"); 
   if (nWriteLen<0) ThrowHr(E_FAIL, __WFUNCTION__, L"Failed to serialize Aliasable Resource end tags. Buffer too small?"); 
   stWriteOff += nWriteLen; 

   return stWriteOff; 
}

/* MaxSerializeLen<T> - T = CAliasableResourceStringBase specific implementation for this template function.
 *
 * SLB 09.may.2016 CR.21553; Fix for compile time error.
 ----------------------------------------------------------------------------------------*/
template <>
inline size_t Primitive<CAliasableResourceStringBase>::MaxSerializeLen(const CAliasableResourceStringBase &tVal)
{
   //
   // <t></t><n></n>   
   //
   size_t stLen(14); 

   // Now add length for streamed variable values.
   // QUADWORD len for m_rtType + resourcename
   stLen += SMaxSerializeLen((QUADWORD)tVal.m_rtType, m_bNumsInDec);                // CR.21547; modified.
   stLen += SMaxSerializeLen(tVal.m_wsFullResourceName);                            // CR.21553; modified.
   return stLen; 
}

/* Deserialize<T> - T = CAliasableResourceStringBase specific implementation for this template function.
 *
 -------------------------------------------------------------------------------------------*/
template <>
inline void Primitive<CAliasableResourceStringBase>::Deserialize(const CSpdCString &wsStreamed, CAliasableResourceStringBase &tVal, bool bTransparentOn)
{
   CSpdCString wsResourceData; 
   if (CStreamableIf::FindDataForTags(L"n", wsStreamed, wsResourceData) == CSpdCString::npos)
   {  //
      // Not a problem: This is probably legacy form of the stream. This means that the stream should just be 
      // assigned directly to the full name.
      //
      SDeserialize(wsStreamed, tVal.m_wsFullResourceName); 
      //
      // Debug Message for testing/debugging functionality. should be removed in the future.
      // If this message is displayed, then expect to see FullName set to a valid resource name.
      // For example, if it is a folder type resource, FullName should look like a 
      // valid UNC folder name.
      //
      wchar_t wcsMsg[512]; 
      _snwprintf_s(wcsMsg, _TRUNCATE, L"%s() - Legacy form of XML string detected. m_wsFullResourceName has been set to: %s",
         L"CStreamableAliasableResourceString<T>",
         tVal.m_wsFullResourceName.c_str()); 
      CEnterExitMsg::TraceMsg(wcsMsg); 
      return; 
   }
   //
   // class data is valid, look for type in data.
   //
   CSpdCString wsTypeData; 
   if (CStreamableIf::FindDataForTags(L"t", wsStreamed, wsTypeData) == CSpdCString::npos) ThrowHr(E_FAIL, __WFUNCTION__, L"Problem retrieving Aliasable Resource type"); 
   //
   // Convert type and resource data
   //
   SDeserialize(wsTypeData, tVal.m_rtType, m_bNumsInDec); 
   SDeserialize(wsResourceData, tVal.m_wsFullResourceName); 
}


/* MaxSerializeLen<T> - T = CStreamableIf specific implementation for this template function.
 *
 -------------------------------------------------------------------------------------------*/
template <>
inline size_t Primitive<CStreamableIf>::MaxSerializeLen(const CStreamableIf &tVal)
{
   return tVal.GetMaxSerializeCharLen(); 
}
/* Deserialize<T> - T = CStreamableIf specific implementation for this template function.
 *
 -------------------------------------------------------------------------------------------*/
template <>
inline void Primitive<CStreamableIf>::Deserialize(const CSpdCString &wsStreamed, CStreamableIf &tVal, bool bTransparentOn)
{
   tVal.Deserialize(wsStreamed); 
}


/* Serialize<T> - T = CTime specific implementation for this template function.
 *
 -------------------------------------------------------------------------------------------*/
template <>
inline size_t Primitive<CTime>::Serialize(const CTime &tVal, wchar_t *pwcsBuf, size_t stBufLen, bool bTransparentOn)
{
   __time64_t t(tVal.GetTime()); 
   return SSerialize((QUADWORD)t, pwcsBuf, stBufLen, true); 
}

/* MaxSerializeLen<T> - T = FILETIME specific implementation for this template function.
 *
 ----------------------------------------------------------------------------------------*/
template <>
inline size_t Primitive<CTime>::MaxSerializeLen(const CTime &tVal)
{
   __time64_t t(tVal.GetTime()); 
   return SMaxSerializeLen((QUADWORD)t, true); 
}

/* Deserialize<T> - T = CAliasableResourceStringBase specific implementation for this template function.
 *
 -------------------------------------------------------------------------------------------*/
template <>
inline void Primitive<CTime>::Deserialize(const CSpdCString &wsStreamed, CTime &tVal, bool bTransparentOn)
{
   QUADWORD qw(0); 
   SDeserialize(wsStreamed, qw, true); 
   tVal = (__time64_t)qw; 
}

/* Serialize<T> - T = CBuffer specific implementation for this template function.
 *
 * SLB 27.apr.2016 CR.21493; Needed to add the <CBuffer > tag back to the xml stream, otherwise 
 * the GUI would through exceptions.
 * SLB 23.may.2016 CR.21622; Size field is now serialized in Decimal.
 -------------------------------------------------------------------------------------------*/
template <>
inline size_t Primitive<CBuffer>::Serialize(const CBuffer &tVal, wchar_t *pwcsBuf, size_t stBufLen, bool bTransparentOn)
{
   //
   // Streamed out version of this object looks like:
   //   <CBuffer>
   //      <Size>6</Size>
   //      <Data>AB0934779523</Data>
   //   </CBuffer>
   //
   int nWriteLen; 
   size_t stWriteOff(0); 
   nWriteLen = _snwprintf_s(pwcsBuf + stWriteOff, stBufLen - stWriteOff, _TRUNCATE,
      L"<CBuffer><Size>");                                                          // CR.21493; modified.
   if (nWriteLen < 0) ThrowHr(E_FAIL, __WFUNCTION__, L"Failed to serialize CBuffer begin tag. Buffer too small?"); 
   stWriteOff += nWriteLen; 

   stWriteOff += SSerialize(tVal.size(), pwcsBuf+stWriteOff, stBufLen-stWriteOff, true); // CR.21622; modified.

   nWriteLen = _snwprintf_s(pwcsBuf+stWriteOff, stBufLen-stWriteOff, _TRUNCATE,
      L"</Size><Data>"); 
   if (nWriteLen < 0) ThrowHr(E_FAIL, __WFUNCTION__, L"Failed to serialize CBuffer middle tags. Buffer too small?"); 
   stWriteOff += nWriteLen; 

   for (DWORD i=0; i<tVal.size(); i++)
   {
      // For each byte, format it in a hex string then append this to the output.
      nWriteLen = _snwprintf_s(pwcsBuf+stWriteOff, stBufLen-stWriteOff, _TRUNCATE, 
         L"%02X", 
         tVal.data()[i]); 
      if (nWriteLen < 0) ThrowHr(E_FAIL, __WFUNCTION__, L"Failed to serialize CBuffer data. Buffer too small?"); 
      stWriteOff += nWriteLen; 
   }

   nWriteLen = _snwprintf_s(pwcsBuf + stWriteOff, stBufLen - stWriteOff, _TRUNCATE,
      L"</Data></CBuffer>");                                                        // CR.21493; modified.
   if (nWriteLen < 0) ThrowHr(E_FAIL, __WFUNCTION__, L"Failed to serialize Aliasable Resource end tags. Buffer too small?"); 
   stWriteOff += nWriteLen; 

   return stWriteOff; 
}


/* MaxSerializeLen<T> - T = CBuffer specific implementation for this template function.
 *
 * SLB 27.apr.2016 CR.21493; Now includes length of the <CBuffer > tag in calculation.
 ----------------------------------------------------------------------------------------*/
template <>
inline size_t Primitive<CBuffer>::MaxSerializeLen(const CBuffer &tVal)
{
   //
   // <CBuffer><Size></Size><Data></Data></CBuffer> 
   //

   // QUADWORD len for m_rtType + resourcename
   size_t stLen(26+19);                                                             // CR.21493; modified.

   // Now add length for streamed variable values.
   stLen += SMaxSerializeLen(tVal.size(), false); 
   stLen += tVal.size()*2; 
   return stLen; 
}


/* Deserialize<T> - T = CBuffer specific implementation for this template function.
 *
 * SLB 23.may.2016 CR.21622; Size field is now serialized in Decimal. Added check to ensure that size field and data length
 * match.
 -------------------------------------------------------------------------------------------*/
template <>
inline void Primitive<CBuffer>::Deserialize(const CSpdCString &wsStreamed, CBuffer &tVal, bool bTransparentOn)
{
   CSpdCString wsSizeData; 
   if (CStreamableIf::FindDataForTags(L"Size", wsStreamed, wsSizeData) == CSpdCString::npos) ThrowHr(E_FAIL, __WFUNCTION__, L"Corrupt Stream? Size tags not found."); 
   QUADWORD qwSize(0); 
   SDeserialize(wsSizeData, qwSize, true);                                          // CR.21622; modified.

   CSpdCString wsBufferData; 
   if (CStreamableIf::FindDataForTags(L"Data", wsStreamed, wsBufferData) == CSpdCString::npos) ThrowHr(E_FAIL, __WFUNCTION__, L"Corrupt Stream? Data tags not found."); 

   // Check that size field and data length align.
   if (qwSize > wsBufferData.size()/2) ThrowHr(E_FAIL, __WFUNCTION__, L"Corrupt Stream? Length of buffer data is smaller than tagged size."); 

   // Allocate a temporary buffer, then copy/convert the data to binary format.
   PBYTE pbBuf(new BYTE[(size_t)qwSize]); 
   wchar_t wcsBuf[3] = {0,0,0}; 
   size_t stFormattedPos(0); 
   size_t stBufPos(0); 
   while (stBufPos < qwSize)
   {
      wmemcpy(wcsBuf, wsBufferData.c_str()+stFormattedPos, 2); 
      pbBuf[stBufPos] = (BYTE)_wcstoui64(wcsBuf, NULL, 16); 
      stBufPos ++; 
      stFormattedPos += 2; 
   }

   // initialize tOutVal with buffer then delete the temp buffer.
   tVal = CBuffer(pbBuf, (size_t)qwSize); 
   delete[] (pbBuf); 
}


/* Serialize()/Deserialize() for CFILETIME. Generic helper methods. May be used
 * by non-attribs based code. 
------------------------------------------------------------------------------------*/
inline CSpdCString Serialize(const CFILETIME& ft)
{
	wchar_t wcsBuf[128];
	Primitive<FILETIME>::SSerialize(ft, wcsBuf, _countof(wcsBuf), true);
	return wcsBuf;
}
inline CFILETIME Deserialize(const CSpdCString& wsStream)
{
	CFILETIME ft;
	Primitive<FILETIME>::SDeserialize(wsStream, ft, true);
	return ft;
}


class CAttributeResourceIF; 

typedef std::list<const CAttributeResourceIF *> TAttribResourceList; 
typedef TAttribResourceList::iterator TItAttribResourceList; 
typedef TAttribResourceList::const_iterator TItcAttribResourceList; 


/*
 * class CAttributeIF
 *
 * SLB 20.oct.2016 CR.22414; Modified the copy constructor such that a tagname must be passed in. This in turn
 * is passed on to the base class.
 */
class SSILIB1_EXPORT CAttributeIF : 
   public CStreamableIf
{
public:
   CAttributeIF(
      const CSpdCString &wsTagName,
      bool bUseLegacyXml=true
      ) :
      CStreamableIf(wsTagName, bUseLegacyXml)
   {}
   CAttributeIF(const CAttributeIF &cpy, const CSpdCString &wsTagName) :            // CR.22414; modified.
      CStreamableIf(cpy, wsTagName)                                                 // CR.22414; modified.
   {}
   CAttributeIF &operator = (const CAttributeIF &c)
   {
      CStreamableIf::operator = (c); 
      return *this; 
   }

   virtual const wchar_t* GetDescriptiveName() const = 0; 
   virtual const wchar_t *GetAttribsClassName() const = 0; 
   virtual void GetResourceMemberList(TAttribResourceList &arlAttribList) const = 0; 
   virtual bool IsResourceNeeded(const CAttributeResourceIF *pAttrib) const = 0; 
   virtual void Clear() = 0; 
}; 


/*
 * class CAttributeResourceIF
 *
 * SLB 09.may.2016 CR.21553; Fix for retrieving attribute description.
 * SLB 26.oct.2016 CR.22456; Added copy constructor which takes a tagname as a paramater.
 */
class SSILIB1_EXPORT CAttributeResourceIF : 
   public CAttributeIF,
   public CResourceStringIF                                                         // CR.15891.V02; modified.
{
public:
   CAttributeResourceIF(
      const CSpdCString &scsTagName,
      bool bUseLegacyXml
      ) :
   CAttributeIF(scsTagName, bUseLegacyXml)
   {}
   CAttributeResourceIF(const CAttributeResourceIF &cpy) :
      CAttributeIF(cpy)
   {}
   CAttributeResourceIF(                                                            // CR.22456; aded.
      const CAttributeResourceIF &cpy,
      const CSpdCString &scsTagName
      ) :
      CAttributeIF(cpy, scsTagName)
   {}
   CAttributeResourceIF &operator = (const CAttributeResourceIF &c)
   {
      CAttributeIF::operator = (c); 
      return *this; 
   }
   virtual CSpdCString GetResourceDescription() const = 0;                          // CR.21553; added.

}; 


/*
 * class: CAttributes
 *
 * Base class for autogenerated code representing an SPDE Streamalbe attribute class.
 *
 * Derived classes will most likely be autogenerated via python script.
 * The base class supports storing simple primitive types in its Property list.
 * Derived classes must define GetXXX()/SetXXX() methods to access these (using this class's GetMember()
 * SetMember() methods)
 * Complex types must be added as member variables to the derived class. 
 * Additionally, the derived class must make sure that it over-rides the three methods used 
 * for Serializing/De-serializing. This Base class will handle all of the simple primitive members (which 
 * means that derived methods must make calls to the base class method), but all complex primitive members 
 * which are added must be explicitly handled via the over-ridden code.
 * Derived classes will always use the Template classes defined in this file for implementing collections.
 * Collection objects can contain either simple or complex primitives.
 * For Map Collections, Key type must always be a simple primitive.
 * 
 * SLB 22.oct.2015 CR.18552.V02; created.
 * SLB 21.apr.2016 CR.18552.V04; completed release candidate. Removed assignment from string operator. I want
 * Deserialization to be an explicit operation so that coder knows that real work is happening.
 * SLB 22.apr.2016 CR.18552.V05; Modified constructor so that code cannot initialize with a single string param. This 
 * prevents the compiler from allowing assignment (operator =()) via a string. Thus, preventing code which may try to
 * initialize the class from an xml string (Deserialize() should always be used for that.)
 * Also, Added GetMember/SetMember methods for encrypted strings. Now they are treated as simple types by attribs code.
 * SLB 27.may.2016 CR.21630; Made access to m_Properties thread safe. Needed for queueing and its access 
 * to jobproperty objects.
 * SLB 19.jul.2016 CR.21572; Added new member to track which properties contain escaped xml data.
 * SLB 20.oct.2016 CR.22414; Modified the copy constructor such that a tagname must be passed in. This in turn
 * is passed on to the base class.
 * SLB 13.jun.2019 CR.27900.V02; Added static method to calculate a CRC code from a passed in string. 
 * SLB 15.jul.2019 CR.17482; Add new pure virtual method Copy(). And new class for managing 
 * ptr returned by it.
 * SLB 29.may.2020 CR.29294; Attempts to reduce handle leaks. Converted Mutex HANDLEs to use CSmartMutex.
 * SLB 12.nov.2020 CR.28730; Added new overload for getting the TransactionProperty Id. This allows for
 * automation of conversion to DBspool job property format.
 * SLB 21.oct.2021 CR.292940.V04; Changed synchronization object from Mutex to 
 * Critical Section (for performance).
 */
class SSILIB1_EXPORT CAttributes :
   public CAttributeIF
{
   typedef std::list<CResourceStringIF *> TResourceList; 
   typedef TResourceList::iterator TItResourceList; 

public:
   typedef std::map<CSpdCString, CSpdCString> TPropertyList; 
   typedef TPropertyList::iterator TItPropertyList; 
   typedef TPropertyList::const_iterator TItcPropertyList; 

   typedef std::set<CSpdCString> TTagNameList;                                      // CR.21572; added.
   typedef TTagNameList::iterator TItTagNameList;                                   // CR.21572; added.
   typedef TTagNameList::const_iterator TItcTagNameList;                            // CR.21572; added.

   class CPropertyItem
   {
   public:
      CSpdCString m_wsTag; 
      CSpdCString m_wsVal; 
   }; 

private:
   TPropertyList m_Properties; 
   TTagNameList m_EscapedMembers;                                                   // CR.21572; added.
   CSmartCriticalSection m_cs;                                                      // CR.29294.V04; modified. CR.29294; modified.
public:
   TResourceList m_ResourceObjects; 
   bool m_bInSlimMode; 

public:
   CAttributes(
      const CSpdCString &wsTagName,
      bool bDontAssignFromString,                                                   // CR.18552.V05; added.
      bool bUseLegacyXml=true
      ) : 
      CAttributeIF(wsTagName, bUseLegacyXml),
      m_bInSlimMode(false)
   {}

#pragma warning(push)                                                               // CR.24131; added.
#pragma warning(disable: 4297)   /* function assumed not to throw an exception but does */ // CR.24131; added.
   virtual ~CAttributes()  
   {
      CSpdLock block(m_cs);                                                         // CR.29294.V04; modified. CR.21630; added.
      if (!block.Locked()) ThrowHr(E_FAIL, __WFUNCTION__, L"Mutex object in invalid."); 
   }
#pragma warning(pop)                                                                // CR.24131; added.
   CAttributes(const CAttributes &cpy, const CSpdCString &wsTagName) :              // CR.22414; modified.
      CAttributeIF(cpy, wsTagName),                                                 // CR.22414; modified.
      m_Properties(cpy.m_Properties),
      m_EscapedMembers(cpy.m_EscapedMembers),                                       // CR.21572; added.
      m_bInSlimMode(cpy.m_bInSlimMode)
   {}
   virtual CAttributes * Copy() const = 0;                                          // CR.17482; added.
   CAttributes &operator = (const CAttributes &cpy)
   {
      CSpdLock block1(m_cs);                                                        // CR.21630; added.
      if (!block1.Locked()) ThrowHr(E_FAIL, __WFUNCTION__, L"Unable to obtain ownership of CAttributes object.1.");
      CSpdLock block2(cpy.m_cs);                                                    // CR.21630; added.
      if (!block2.Locked()) ThrowHr(E_FAIL, __WFUNCTION__, L"Unable to obtain ownership of CAttributes object.2.");

      CAttributeIF::operator = (cpy); 
      m_Properties = cpy.m_Properties; 
      m_EscapedMembers = cpy.m_EscapedMembers;                                      // CR.21572; added.
      m_bInSlimMode = cpy.m_bInSlimMode; 
      return *this; 
   }
   virtual bool operator == (const CAttributes &cmp) const 
   { 
      CSpdLock block1(m_cs);                                                        // CR.21630; added.
      if (!block1.Locked()) ThrowHr(E_FAIL, __WFUNCTION__, L"Unable to obtain ownership of CAttributes object.1.");
      CSpdLock block2(cmp.m_cs);                                                    // CR.21630; added.
      if (!block2.Locked()) ThrowHr(E_FAIL, __WFUNCTION__, L"Unable to obtain ownership of CAttributes object.2.");

      return (m_Properties == cmp.m_Properties);  
   }
   virtual bool operator != (const CAttributes &cmp) const { return !operator == (cmp); } 
   virtual bool IsModified() const { return m_bIsModified; }  
   bool IsSimplePropertyModified(const CSpdCString &wsTag) const                    // CR.21572; added.
   {
      if (m_Properties.find(wsTag) == m_Properties.end()) return false; 
      return true; 
   }
   virtual void ClearModified() { m_bIsModified = false; }  
   virtual void Clear() 
   { 
      CSpdLock block(m_cs);                                                         // CR.21630; added.
      if (!block.Locked()) ThrowHr(E_FAIL, __WFUNCTION__, L"Unable to obtain ownership of CAttributes object.");

      m_Properties.clear();  
      m_EscapedMembers.clear();                                                     // CR.21572; added.
      ClearModified();  
   }
   void ClearMember(const CSpdCString &wsTag) 
   { 
      CSpdLock block(m_cs);                                                         // CR.21630; added.
      if (!block.Locked()) ThrowHr(E_FAIL, __WFUNCTION__, L"Unable to obtain ownership of CAttributes object.");

      m_Properties.erase(wsTag);  
      m_EscapedMembers.erase(wsTag);                                                // CR.21572; added.
   }

   // Pure virtual methods which must be implemented by derived classes.
   // Note: In reality, this will probably just be the auto-generated Activity Properties class.
   //
   // XML Serializing/Deserializing methods.
   virtual size_t Serialize(wchar_t *pwcsBuf, size_t stBufCharLen, bool bUseTag=true, bool bUseContainerTag=true, bool bTransparentOn=false) const; 
   CSpdCString Serialize(bool bUseTag=true, bool bUseContainerTag=true) const; 
   size_t SerializeBegin(wchar_t *pwcsBuf, size_t stBufCharLen, bool bUseTag, bool bUseContainerTag) const; 
   size_t SerializeEnd(wchar_t *pwcsBuf, size_t stBufCharLen, bool bUseTag, bool bUseContainerTag) const; 
   virtual size_t GetMaxSerializeCharLen() const; 
   size_t FindNextXmlTagAndData(const CSpdCString &wsXmlBuf, size_t stSearchPos, CSpdCString &wsTag, CSpdCString &wsTagData) const; 
   virtual void Deserialize(const CSpdCString &wsXmlBuf, bool bTransparentOn=false, bool bClearFirst=true); 
   void DeserializeFromFile(const CNtfsFolderName &nfnXmlFile);                     // CR.17862.V05; added.

   void AddResourceMembersToList(TAttribResourceList &arlAttribList, bool bAddNeededResourcesOnly) const
   {
      GetResourceMemberList(arlAttribList); 
      if (!bAddNeededResourcesOnly) return; 
      if (arlAttribList.empty()) return; 
      //
      // Not an empty resource list and un-needed resources should be removed.
      // Remove any resource members which are not needed (based upon current attribute values.
      //
      for (TItAttribResourceList it(arlAttribList.begin());  it != arlAttribList.end();  )
      {
         if (IsResourceNeeded(*it)) { it++; continue; } 
         else it = arlAttribList.erase(it); 
      }
   }
   /* AreAllNeededResourcesAliased() - This method loops through all child attrib members and 
    * ensures that all resources are aliased.
    *
    * SLB 18.jun.2014 CR.17862; added.
    * SLB 10.jun.2019 CR.27916; Added "check" mode which throws an exception with problem details when a resource
    * is not aliased.
    ------------------------------------------------------------------------------------------*/
   virtual bool AreAllNeededResourcesAliased(
      bool bIsInCheckMode = false) const                                            // CR.27916; added.
   { 
      // check all resource attrib members to see if they are needed resources and that they are aliased.
      TAttribResourceList arlResourceList; 
      AddResourceMembersToList(arlResourceList, true); 
      for (TItcAttribResourceList itMember(arlResourceList.begin()); itMember != arlResourceList.end(); itMember++)
      {
         if (!(*itMember)->IsResourceAnAlias()) 
         { 
            if (bIsInCheckMode) ThrowHr(E_FAIL, __WFUNCTION__, L"Attribute \"%s\" is not aliased. Current setting <%s>", (*itMember)->GetResourceDescription().c_str(), (*itMember)->GetResourceName().c_str());
            return false; 
         }
      }

      // If this point in the code is reached, then no unaliased, needed, resources were found.
      // return success.
      return true; 
   }

   /* AreAnyModifiedPropertiesReadOnly() - This method loops through all child attrib members and 
    * returns true if a modified property is read only.
    *
    * SLB 03.feb.2016 CR.18552.V03; added.
   ------------------------------------------------------------------------------------------*/
   bool AreAnyModifiedPropertiesReadOnly() const
   {
      for (TItcPropertyList it(m_Properties.begin());  it != m_Properties.end();  it++)
      {
         if (IsPropertyReadOnlyForClients(it->first)) return true; 
      }
      return false; 
   }

   // Low level access provided for initialization by code which is tpi aware.
   // (note: data should always be serialized and xml escaped.)
   // Also exposed to higher level methods which don't deal with data type.
   typedef CSpdCString const * TPtrCString; 
   void SetMemberRaw(const CSpdCString &wsTag, const CSpdCString &wsVal, bool bAddToEscapedList=false);           // CR.21572; modified.
   bool GetMemberRaw(const CSpdCString &wsTag, CSpdCString &wsVal) const; 
   bool GetMemberRaw(const CSpdCString &wsTag, TPtrCString *ppscsVal) const; 

   void GetPrimitivePropertyList(TPropertyList &pl, CAttributes::TTagNameList &tnlEscaped) const                  // CR.21572; modified.
   {
      CSpdLock block(m_cs); 

      pl = m_Properties; 
      tnlEscaped = m_EscapedMembers;                                                // CR.21572; added.
   }

   bool GetFirstPropertyEntry(TItcPropertyList &itLoc, CPropertyItem &peItem) const 
   {
      CSpdLock block(m_cs); 

      itLoc = m_Properties.begin(); 
      if (itLoc==m_Properties.end()) return false; 
      
      peItem.m_wsTag = itLoc->first; 
      return GetMember(peItem.m_wsTag, peItem.m_wsVal); 
   }
   bool GetNextPropertyEntry(TItcPropertyList &itLoc, CPropertyItem &peItem) const 
   {
      CSpdLock block(m_cs); 

      if (itLoc==m_Properties.end()) return false; 
      itLoc++; 
      if (itLoc==m_Properties.end()) return false; 
      
      peItem.m_wsTag = itLoc->first; 
      return GetMember(peItem.m_wsTag, peItem.m_wsVal); 
   }
   DWORD GetPropertyEntryCount() const 
   { 
      CSpdLock block(m_cs); 

      return (DWORD)m_Properties.size();  
   }

#if 0
   virtual bool GetMember(TTransactionPropertyId tpi, CSpdCString &val) const; 
   virtual bool GetMember(TTransactionPropertyId tpi, QUADWORD &val) const; 
   virtual bool GetMember(TTransactionPropertyId tpi, ::FILETIME &val) const; 
   static TTransactionPropertyId GetTransactionPropertyId(
      const CSpdCString &wsAttribTag);
   static TTransactionPropertyId GetTransactionPropertyId(
      TEnginePropertyIds epId);
   static TTransactionPropertyId GetTransactionPropertyId(
      const CSpdCString &wsStringVarTag, 
      bool);
   static TTransactionPropertyId GetTransactionPropertyId(                          // CR.28730; added.
      DBSpoolJobAttributeID dbsjaId);

   static CSpdCString GetLegacyKey(const CSpdCString &wsAttribTag); 
   static int GetDbsId(const CSpdCString &wsAttribTag); 
   static CSpdCString GetTagKeyFromLegacyKey(const CSpdCString &wsLegacyKey); 
   static CSpdCString GetTagKeyFromPropertyId(TTransactionPropertyId tpi); 
   static CSpdCString GetTagKeyFromPropertyId(TEnginePropertyIds epi); 
   static bool IsPropertyReadOnlyForClients(TTransactionPropertyId tpId); 
   static bool IsPropertyReadOnlyForClients(const CSpdCString &wsAttribTag); 
   static QUADWORD CalculateRedundancyCode(const CSpdCString &wsStream);            // CR.27900.V02; added.
#endif
	static bool IsPropertyReadOnlyForClients(const CSpdCString& wsAttribTag);

protected:
   // Get/Set for double
   bool GetMember(const CSpdCString &wsTag, double &val) const;                     // CR.21547; added.
   void SetMember(const CSpdCString &wsTag, double val);                            // CR.21547; added.

   // Get/Set for __int64
   bool GetMember(const CSpdCString &wsTag, QUADWORD &val, bool bInDec=false) const; 
   void SetMember(const CSpdCString &wsTag, QUADWORD val, bool bInDec=false); 

   bool GetMember(const CSpdCString &wsTag, DWORD &val, bool bInDec=false) const 
   {
      QUADWORD qw; 
      if (!GetMember(wsTag, qw, bInDec)) return false; 
      val = (DWORD)qw; 
      return true; 
   }
   bool GetMember(const CSpdCString &wsTag, WORD &val, bool bInDec=false) const 
   {
      QUADWORD qw; 
      if (!GetMember(wsTag, qw, bInDec)) return false; 
      val = (WORD)qw; 
      return true; 
   }
   bool GetMember(const CSpdCString &wsTag, BYTE &val, bool bInDec=false) const 
   {
      QUADWORD qw; 
      if (!GetMember(wsTag, qw, bInDec)) return false; 
      val = (BYTE)qw; 
      return true; 
   }
   bool GetMember(const CSpdCString &wsTag, __int64 &val, bool bInDec=false) const 
   {
      QUADWORD qw; 
      if (!GetMember(wsTag, qw, bInDec)) return false; 
      val = (__int64)qw; 
      return true; 
   }
   bool GetMember(const CSpdCString &wsTag, bool &val) const 
   {
      QUADWORD qw; 
      if (!GetMember(wsTag, qw)) return false; 
      val = qw!=0 ? true : false; 
      return true; 
   }

   // Get/Set for FILETIME
   bool GetMember(const CSpdCString &wsTag, ::FILETIME &val) const 
   {
      CSpdCString wsVal; 
      if (!GetMember(wsTag, wsVal)) return false; 

      Primitive<::FILETIME>::SDeserialize(wsVal, val, true); 
      return true; 
   }
   void SetMember(const CSpdCString &wsTag, const ::FILETIME &val)
   {
      wchar_t wcsStreamed[100]; 
      Primitive<::FILETIME>::SSerialize(val, wcsStreamed, 100, true); 
      SetMember(wsTag, CSpdCString(wcsStreamed)); 
   }

   // Get/Set for strings
   bool GetMember(const CSpdCString &wsTag, CSpdCString &val, bool bTransparencyOn=false) const; 
   void SetMember(const CSpdCString &wsTag, const CSpdCString &val, bool bTransparencyOn=false); 

   // Get/Set for encrypted strings
   bool GetMember(const CSpdCString &wsTag, wstring_crypto &val) const;             // CR.18552.V05; added.
   void SetMember(const CSpdCString &wsTag, const wstring_crypto &val);             // CR.18552.V05; added.
}; 


/*
 * class CAttributesPtr: helper class used to manage use and clean-up of Attributes ptr returned by CAttributes::Copy().
 *
 * SLB 17.jul.2019 CR.17482; created.
 * SLB 18.jan.2023 CR.32082; changed "protected" constructors initialization to 
 * eliminate IntelliSense warning msg 26495.
 */
class CAttributesPtr
{
private:
   CAttributes *m_p;
public:
   CAttributesPtr(CAttributes *p) : m_p(p) {}
   ~CAttributesPtr()  { if (m_p) delete(m_p); }
   CAttributes * operator ->() 
   { 
      if (!m_p) ThrowHr(E_POINTER, __WFUNCTION__, L"Internal error. Failed to create/copy attributes object.");
      return m_p; 
   }
private:
   // prevent mis-use.
   CAttributesPtr() : m_p(NULL) {}                                                  // CR.32082; modified.
   CAttributesPtr(const CAttributesPtr &cpy) : m_p(cpy.m_p) {}                      // CR.32082; modified.
};


/*
 * template class CAttributesMap
 *
 * Templates: class must be 
 * 
 * SLB 26.oct.2016 CR.22456; Copy constructor now requires a tagname as a paramater.
 * SLB 22.mar.2017 CR.23181; Seralize()/Deserialize9) default for bipassing excaping of value node changed from
 * true to false. This is the safer scenario.
 * SLB 12.nov.2024 NoCR.V01; Changes to work when compiling as ISO C++ 20.
 */
template <class K, class V>
class CAttributesMap :
   public CAttributeIF,
   public std::map<K,V> 
{
public:
  typedef std::map<K, V> TCollection; 
  typedef typename TCollection::iterator TItCollection; 
  typedef typename TCollection::const_iterator TItcCollection; 

  using size_type = typename TCollection::size_type;

   bool m_bInSlimMode; 
public:

   CAttributesMap(
      const CSpdCString &wsTagName,
      bool bUseLegacyXml=true,
      bool bUseSlimMode=false
      ) : 
      CAttributeIF(wsTagName, bUseLegacyXml),
      TCollection(),
      m_bInSlimMode(bUseSlimMode)
   {}
   virtual ~CAttributesMap() 
   {}
   CAttributesMap(
      const CAttributesMap &cpy,
      const CSpdCString &wsTag                                                     // CR.22456; added.
      ) :
      CAttributeIF(cpy, wsTag),
      TCollection(cpy),
      m_bInSlimMode(cpy.m_bInSlimMode) 
   {}
   CAttributesMap &operator = (const CAttributesMap &cpy)
   {
      CAttributeIF::operator = (cpy); 
      TCollection::operator = (cpy); 
      m_bInSlimMode = cpy.m_bInSlimMode; 
      return *this; 
   }
   //
   // XML Serializing/Deserializing methods.
   // 
   size_t Serialize(
      wchar_t *pwcsBuf, 
      size_t stBufCharLen,
      bool bUseTag = true,
      bool bUseContainerTag = true, 
      bool bTransparentOn = false) const                                            // CR.23181; modified.
   {
      if (this->empty()) return 0; 

      size_t stWriteOff(0); 
      int nWriteLen(0); 
      if (m_bInSlimMode)
      {
         bUseContainerTag = false; 
         nWriteLen = _snwprintf_s(pwcsBuf+stWriteOff, stBufCharLen-stWriteOff, _TRUNCATE,
            L"<%s>",
            GetTagName().c_str()); 
         if (nWriteLen < 0) ThrowHr(E_FAIL, __WFUNCTION__, L"Insufficient space to serialize list header tag."); 
         stWriteOff += nWriteLen; 
      }
      else if (bUseContainerTag)
      {
         // Legacy Xml requires extra tags. Add them.
         nWriteLen = _snwprintf_s(pwcsBuf+stWriteOff, stBufCharLen-stWriteOff, _TRUNCATE,
            L"<%s><Map>",
            GetTagName().c_str()); 
         if (nWriteLen < 0) ThrowHr(E_FAIL, __WFUNCTION__, L"Insufficient space to serialize list header tag."); 
         stWriteOff += nWriteLen; 
      }
      Primitive<K> k; 
      for (TItcCollection it(this->begin());  it != this->end();  it++)
      {
         // Add begin tags: <N><K>.
         nWriteLen = _snwprintf_s(
            pwcsBuf+stWriteOff, stBufCharLen-stWriteOff, _TRUNCATE,
            L"<N><K>"); 
         if (nWriteLen < 0) ThrowHr(E_FAIL, __WFUNCTION__, L"Insufficient space to serialize map node."); 
         stWriteOff += nWriteLen; 

         // Add key. Serialize() throws hr_exception if it cannot serialize the key, so no need to check
         // the result.
         stWriteOff += k.Serialize(
            it->first,
            pwcsBuf+stWriteOff, 
            stBufCharLen-stWriteOff,
            bTransparentOn); 

         // Add intermediate tags: </K><V>.
         nWriteLen = _snwprintf_s(
            pwcsBuf+stWriteOff, stBufCharLen-stWriteOff, _TRUNCATE,
            L"</K><V>"); 
         if (nWriteLen<0) ThrowHr(E_FAIL, __WFUNCTION__, L"Insufficient space to serialize map node."); 
         stWriteOff += nWriteLen; 

         // Add value. SerializeVal() throws hr_exception if it cannot serialize the key, so no need to check
         // the result.
         stWriteOff += SerializeValue(
            it->second,
            pwcsBuf + stWriteOff, 
            stBufCharLen - stWriteOff,
            m_bInSlimMode ? false : bUseTag,                                        // CR.21446; modified.
            false,
            bTransparentOn); 

         // Add final tags: </V></N>.
         nWriteLen = _snwprintf_s(pwcsBuf + stWriteOff, stBufCharLen - stWriteOff, _TRUNCATE,
            L"</V></N>"); 
         if (nWriteLen < 0) ThrowHr(E_FAIL, __WFUNCTION__, L"Insufficient space to serialize map node."); 
         stWriteOff += nWriteLen; 
      }
      if (m_bInSlimMode)
      {
         nWriteLen = _snwprintf_s(pwcsBuf + stWriteOff, stBufCharLen - stWriteOff, _TRUNCATE,
            L"</%s>",
            GetTagName().c_str()); 
         if (nWriteLen < 0) ThrowHr(E_FAIL, __WFUNCTION__, L"Insufficient space to serialize list header tag."); 
         stWriteOff += nWriteLen; 
      }
      else if (bUseContainerTag)
      {
         // Add Legacy Xml closing tags.
         nWriteLen = _snwprintf_s(pwcsBuf+stWriteOff, stBufCharLen-stWriteOff, _TRUNCATE,
            L"</Map></%s>",
            GetTagName().c_str()); 
         if (nWriteLen < 0) ThrowHr(E_FAIL, __WFUNCTION__, L"Insufficient space to serialize list trailer tag."); 
         stWriteOff += nWriteLen; 
      }
      return stWriteOff; 
   }
   size_t GetMaxSerializeCharLen() const 
   {
      Primitive<K> k; 
      size_t stCharLen(0); 
      for (TItcCollection it(this->begin());  it != this->end();  it++)
      {
         // Add static tag len: "<N><K></K><V></V></N>"
         stCharLen += 21; 

         // Now add length for Serialized Key and Value.
         stCharLen += k.MaxSerializeLen(it->first); 
         stCharLen += MaxSerializeLenValue(it->second); 
      }
      return stCharLen; 
   }
   void Deserialize(
      const CSpdCString &wsXmlBuf, 
      bool bTransparentOn=false,                                                    // CR.23181; modified.
      bool bClearFirst=false) 
   {
      if (bClearFirst) Clear(); 

      size_t stNextReadPos(0); 
      while (true) 
      {
         // Retrieve the next nodes serialized buffer.
         CSpdCString wsNodeData; 
         stNextReadPos = FindDataForTags(
            L"N",
            wsXmlBuf,
            wsNodeData,
            false,
            stNextReadPos); 
         if (stNextReadPos==CSpdCString::npos) break; 

         // Now retrieve the serialized versions of its key and value from this
         // buffer.
         CSpdCString wsKeyData; 
         CSpdCString wsValData; 
         size_t stValReadPos; 
         stValReadPos = FindDataForTags(
            L"K",
            wsNodeData,
            wsKeyData,
            false,
            0); 
         FindDataForTags(
            L"V",
            wsNodeData,
            wsValData,
            false,
            stValReadPos); 

         // Now have isolated both Key and Value in their primitive serialized form.
         // De-serialize them and add the node to the std::map member.
         Primitive<K> k; 
         K key; 
         V val; 
         k.Deserialize(wsKeyData, key, bTransparentOn); 
         DeserializeValue(wsValData, val, bTransparentOn); 
			this->emplace(key, val);
      }
   }
   virtual bool IsModified() const { return this->size() != 0; }
   virtual bool IsResourceNeeded(const CAttributeResourceIF *pAttrib) const { return false; }
   virtual const wchar_t *GetAttribsClassName() const { return L""; }
   virtual const wchar_t *GetDescriptiveName() const { return L""; }
   virtual void Clear() { this->clear(); }
protected:
   virtual size_t SerializeValue(
      const V &val,
      wchar_t *pwcsBuf, 
      size_t stBufCharLen, 
      bool bUseTag,
      bool bUseContainerTag,
      bool bTransparentOn) const = 0; 
   virtual size_t MaxSerializeLenValue(
      const V &val) const = 0; 
   virtual void DeserializeValue(
      const CSpdCString &wsXmlBuf,
      V &val, 
      bool bTransparentOn=true) = 0; 
}; 

/* 
 * template class: CAttributesMapPrimitive:
 *
 * SLB 22.apr.2016 CR.18552.V05; Modified constructor so that code cannot initialize with a single string param. This 
 * prevents the compiler from allowing assignment (operator =()) via a string. Thus, preventing code which may try to
 * initialize the class from an xml string (Deserialize() should always be used for that.)
 * SLB 26.oct.2016 CR.22456; Copy constructor now requires a tagname as a paramater.
 * SLB 13.feb.2019 CR.26999.Item82; Added operator =() which allows for a std::map<K,V> to be assigned.  
 */
template <class K, class V>
class CAttributesMapPrimitive : 
   public CAttributesMap<K, V> 
{
public:
   CAttributesMapPrimitive(
      const CSpdCString &wsTagName,
      bool bDontAssignFromString,                                                   // CR.18552.V05; added.
      bool bUseLegacyXml=true,
      bool bUseSlimMode=false
      ) : 
      CAttributesMap<K, V>(wsTagName, bUseLegacyXml, bUseSlimMode)
   {}
   CAttributesMapPrimitive(
      const CAttributesMapPrimitive &cpy,
      const CSpdCString &wsTag                                                      // CR.22456; added.
      ) :
      CAttributesMap<K, V>(cpy, wsTag)                                              // CR.22456; modified.
   {}
   CAttributesMapPrimitive &operator = (const CAttributesMapPrimitive &cpy)
   {
      CAttributesMap<K, V>::operator = (cpy); 
      return *this; 
   }
   CAttributesMapPrimitive<K,V> &operator = (const std::map<K, V> &cpy)             // CR.26999.Item82; added.
   {
      this->TCollection::operator = (cpy);
      return *this; 
   }
   virtual void GetResourceMemberList(TAttribResourceList &arlAttribList) const 
   {
   }

protected:
   virtual size_t SerializeValue(
      const V &val,
      wchar_t *pwcsBuf, 
      size_t stBufCharLen, 
      bool bUseTag,
      bool bUseContainerTag,
      bool bTransparentOn) const 
   {
      Primitive<V> v; 
      return v.Serialize(val, pwcsBuf, stBufCharLen, bTransparentOn); 
   }; 
   virtual size_t MaxSerializeLenValue(
      const V &val) const 
   {
      Primitive<V> v; 
      return v.MaxSerializeLen(val); 
   }
   virtual void DeserializeValue(
      const CSpdCString &wsXmlBuf,
      V &val, 
      bool bTransparentOn=true) 
   {
      Primitive<V> v; 
      v.Deserialize(wsXmlBuf, val, bTransparentOn); 
   }
}; 

/* 
 * template class: CAttributesMapAttribsIf:
 *
 * SLB 22.apr.2016 CR.18552.V05; Modified constructor so that code cannot initialize with a single string param. This 
 * prevents the compiler from allowing assignment (operator =()) via a string. Thus, preventing code which may try to
 * initialize the class from an xml string (Deserialize() should always be used for that.)
 * SLB 26.oct.2016 CR.22456; Copy constructor now requires a tagname as a paramater.
 * SLB 17.jul.2019 CR.17482.V01; Fix for not over-riding IsResourceNeeded(). 
 * SLB 12.nov.2024 NoCR.V01; Changes to work when compiling as ISO C++ 20.
 */
template <class K, class V>
class CAttributesMapAttribsIf : 
   public CAttributesMap<K, V> 
{
public:
	using TCollection = CAttributesMap<K, V>::TCollection;
	using TItCollection = CAttributesMap<K, V>::TItCollection;
	using TItcCollection = CAttributesMap<K, V>::TItcCollection;

public:
   CAttributesMapAttribsIf(
      const CSpdCString &wsTagName,
      bool bDontAssignFromString,                                                   // CR.18552.V05; added.
      bool bUseLegacyXml=true,
      bool bUseSlimMode=false
      ) : 
      CAttributesMap<K, V>(wsTagName, bUseLegacyXml, bUseSlimMode)
   {}
   CAttributesMapAttribsIf(
      const CAttributesMapAttribsIf &cpy,
      const CSpdCString &wsTag                                                      // CR.22456; added.
      ) :
      CAttributesMap<K, V>(cpy, wsTag)                                              // CR.22456; modified.
   {}
   CAttributesMapAttribsIf &operator = (const CAttributesMapAttribsIf &cpy)
   {
      CAttributesMap<K, V>::operator = (cpy); 
      return *this; 
   }
   virtual void GetResourceMemberList(TAttribResourceList &arlAttribList) const 
   {
      for (TItcCollection  it = this->begin();  it != this->end(); it++)
      {
         it->second.GetResourceMemberList(arlAttribList); 
      }
   }
   virtual bool IsResourceNeeded(const CAttributeResourceIF *pAttrib) const         // CR.17482.V01; added.
   { 
      for (TItcCollection it(this->begin());  it != this->end();  it++)
      {
         if (!it->second.IsResourceNeeded(pAttrib)) continue; 

         return true;
      }
      return false;  
   }

protected:
   virtual size_t SerializeValue(
      const V &val,
      wchar_t *pwcsBuf, 
      size_t stBufCharLen, 
      bool bUseTag,
      bool bUseContainerTag,
      bool bTransparentOn) const 
   {
      return val.Serialize(pwcsBuf, stBufCharLen, bUseTag, bUseContainerTag, bTransparentOn); 
   } 
   virtual size_t MaxSerializeLenValue(
      const V &val) const 
   {
      return val.GetMaxSerializeCharLen(); 
   }
   virtual void DeserializeValue(
      const CSpdCString &wsXmlBuf,
      V &val, 
      bool bTransparentOn=true) 
   {
      val.Deserialize(wsXmlBuf, bTransparentOn); 
   }
}; 


/*
 * template class CAttributesList
 *
 * Templates: 
 * 
 * SLB 26.oct.2016 CR.22456; Copy constructor now requires a tagname as a paramater.
 * SLB 07.jan.2018 CR.26999.Item41; changed base from std::vector to std::list. This was so iterators do not 
 * get invalidated when the container grows. This could affect PERFORMANCE though...
 * Added/implemented operator [] for backward compatibility with code accessing these lists as vectors.
 * SLB 17.apr.2024 CR.32662.V03; Added template param "C" = Collection, to allow for
 * specifying another collection type, if desired. Tested, but not using... went a
 * a differnt route.
 * Added the at() method for better backward compatibility with existing code which 
 * wants to access the data via a size_t offset.
 * SLB 12.nov.2024 NoCR.V01; Changes to work when compiling as ISO C++ 20.
 */
template <class V>
class CAttributesList :
   public CAttributeIF,
   public std::list<V>                                                              // CR.26999.Item41; modified.
{
public:
   typedef std::list<V> TCollection;                                                // CR.26999.Item41; modified.
   typedef typename TCollection::iterator TItCollection; 
   typedef typename TCollection::const_iterator TItcCollection; 

public:
   bool m_bInSlimMode; 

public:
	using size_type = TCollection::size_type;														// NoCR.V01; added.

   CAttributesList(
      const CSpdCString &wsTagName,
      bool bUseLegacyXml=true,
      bool bUseSlimMode=false
      ) : 
      CAttributeIF(wsTagName, bUseLegacyXml),
      TCollection(),
      m_bInSlimMode(bUseSlimMode)
   {}
   virtual ~CAttributesList() 
   {}
   CAttributesList(
      const CAttributesList &cpy, 
      const CSpdCString &wsTag																		// CR.22456; added.
      ) :
      CAttributeIF(cpy, wsTag),																		// CR.22456; modified.
      TCollection(cpy),
      m_bInSlimMode(cpy.m_bInSlimMode)
   {}
   CAttributesList &operator = (const CAttributesList &cpy)
   {
      CAttributeIF::operator = (cpy); 
      TCollection::operator = (cpy); 
      m_bInSlimMode = cpy.m_bInSlimMode; 
      return *this; 
   }

	V& at(size_t _Pos)																					// CR.32662.V03; added.
	{
		if (_Pos >= this->size()) throw (std::out_of_range("Specified postion exceeds attributes list size."));

		size_t i(0);
		for (TItCollection it(this->begin()); it != this->end(); it++, i++)
		{
			if (i == _Pos) return *it;
		}

		// should never get here.
		return *this->begin();
	}

	const V& at(size_t _Pos) const 																	// CR.33570.V01; added.
	{
		if (_Pos >= this->size()) throw (std::out_of_range("Specified postion exceeds attributes list size."));

		size_t i(0);
		for (TItcCollection it(this->begin()); it != this->end(); it++, i++)
		{
			if (i == _Pos) return *it;
		}

		// should never get here.
		return *this->begin();
	}

	V & operator [] (size_t _Pos)																		// CR.26999.Item41; added.
   {
		return this->at(_Pos);
   }

   const V & operator [] (size_t _Pos) const														// CR.26999.Item41; added.
   {
		return this->at(_Pos);
   }

   //
   // XML Serializing/Deserializing methods.
   //
   size_t Serialize(
      wchar_t *pwcsBuf, 
      size_t stBufCharLen,
      bool bUseTag,
      bool bUseContainerTag,
      bool bTransparentOn=false) const                                              // CR.23181; modified.
   {
      if (this->empty()) return 0; 

		// Slim mode over-rides using extra tags in entries and Container tags for object.
      if (m_bInSlimMode) bUseTag = bUseContainerTag = false;                        // CR.23181; added.

      size_t stWriteOff(0); 
      int nWriteLen(0); 
      if (m_bInSlimMode)
      {
         nWriteLen = _snwprintf_s(
            pwcsBuf+stWriteOff, stBufCharLen-stWriteOff, _TRUNCATE,
            L"<%s>",
            GetTagName().c_str()); 
         if (nWriteLen < 0) ThrowHr(E_FAIL, __WFUNCTION__, L"Insufficient space to serialize list header tag."); 
         stWriteOff += nWriteLen; 
      }
      else if (bUseContainerTag)
      {
         // Legacy Xml requires extra tags. Add them.
         nWriteLen = _snwprintf_s(
            pwcsBuf+stWriteOff, stBufCharLen-stWriteOff, _TRUNCATE,
            L"<%s><Vector>",
            GetTagName().c_str()); 
         if (nWriteLen < 0) ThrowHr(E_FAIL, __WFUNCTION__, L"Insufficient space to serialize list header tag."); 
         stWriteOff += nWriteLen; 
      }

      for (TItcCollection it(this->begin());  it != this->end();  it++)
      {
         // Add begin tags: <N>.
         nWriteLen = _snwprintf_s(
            pwcsBuf+stWriteOff, stBufCharLen-stWriteOff, _TRUNCATE,
            L"<N>"); 
         if (nWriteLen < 0) ThrowHr(E_FAIL, __WFUNCTION__, L"Insufficient space to serialize list node."); 
         stWriteOff += nWriteLen; 

         // Add value.. SerializeValue() throws hr_exception if it cannot serialize the value, so no need to check
         // the result.
         stWriteOff += SerializeValue(
            *it,
            pwcsBuf+stWriteOff, 
            stBufCharLen-stWriteOff, 
            bUseTag,                                                                // CR.23181; modified. CR.21446; modified.
            false, 
            bTransparentOn); 

			// Add final tags: </N>.
         nWriteLen = _snwprintf_s(
            pwcsBuf+stWriteOff, stBufCharLen-stWriteOff, _TRUNCATE,
            L"</N>"); 
         if (nWriteLen < 0) ThrowHr(E_FAIL, __WFUNCTION__, L"Insufficient space to serialize map node."); 
         stWriteOff += nWriteLen; 
      }
      if (m_bInSlimMode)
      {
         nWriteLen = _snwprintf_s(
            pwcsBuf+stWriteOff, stBufCharLen-stWriteOff, _TRUNCATE,
            L"</%s>",
            GetTagName().c_str()); 
         if (nWriteLen < 0) ThrowHr(E_FAIL, __WFUNCTION__, L"Insufficient space to serialize list header tag."); 
         stWriteOff += nWriteLen; 
      }
      else if (bUseContainerTag)
      {
         // Add Legacy Xml closing tags.
         nWriteLen = _snwprintf_s(
            pwcsBuf+stWriteOff, stBufCharLen-stWriteOff, _TRUNCATE,
            L"</Vector></%s>",
            GetTagName().c_str()); 
         if (nWriteLen <0 ) ThrowHr(E_FAIL, __WFUNCTION__, L"Insufficient space to serialize list trailer tag."); 
         stWriteOff += nWriteLen; 
      }
      return stWriteOff; 
   }

   size_t GetMaxSerializeCharLen() const 
   {
      size_t stCharLen(0); 
      for (TItcCollection it(this->begin());  it != this->end();  it++)
      {
         //
         // Add static tag len: "<N></N>"
         //
         stCharLen += 7; 
         //
         // Now add length for Serialize Value.
         //
         stCharLen += MaxSerializeLenValue(*it); 
      }
      return stCharLen; 
   }

   void Deserialize(
      const CSpdCString &wsXmlBuf, 
      bool bTransparentOn=false,                                                    // CR.23181; modified.
      bool bClearFirst=true) 
   {
      if (bClearFirst) Clear(); 
      size_t stNextReadPos(0); 
      while (true) 
      {
         //
         // Retrieve the next nodes serialized buffer.
         //
         CSpdCString wsNodeData; 
         stNextReadPos = FindDataForTags(
            L"N",
            wsXmlBuf,
            wsNodeData,
            false,
            stNextReadPos); 
         if (stNextReadPos==CSpdCString::npos) break; 
         //
         // Now have isolated the Value in its primitive serialized form.
         // De-serialize it and add the node to the std::list member.
         //
         V val; 
         //
         // check to see if V is derived from CStreamableIf. If it is, use that specific implementation of 
         // PrimitiveDeserialize, otherwise, allow the compiler to decide which specific implementation to use.
         //
         DeserializeValue(wsNodeData, val, bTransparentOn);  
			this->push_back(val);
      }
   }

   virtual bool IsModified() const { return this->size()!=0; } 
   virtual bool IsResourceNeeded(const CAttributeResourceIF *pAttrib) const { return false; } 
   virtual const wchar_t *GetAttribsClassName() const { return L""; } 
   virtual const wchar_t *GetDescriptiveName() const { return L""; } 
   virtual void Clear() { this->clear(); } 
protected:
   virtual size_t SerializeValue(
      const V &val,
      wchar_t *pwcsBuf, 
      size_t stBufCharLen, 
      bool bUseTag,
      bool bUseContainerTag,
      bool bTransparentOn) const = 0; 
   virtual size_t MaxSerializeLenValue(
      const V &val) const = 0; 
   virtual void DeserializeValue(
      const CSpdCString &wsXmlBuf,
      V &val, 
      bool bTransparentOn=true) = 0; 
}; 



/* 
 * template class: CAttributesListPrimitive:
 *
 * SLB 22.apr.2016 CR.18552.V05; Modified constructor so that code cannot initialize with a single string param. This 
 * prevents the compiler from allowing assignment (operator =()) via a string. Thus, preventing code which may try to
 * initialize the class from an xml string (Deserialize() should always be used for that.)
 * SLB 26.oct.2016 CR.22456; Copy constructor now requires a tagname as a paramater.
 * SLB 13.feb.2019 CR.26999.Item82; Added operator =() which allows for a std::list<V> to be assigned.  
 * SLB 17.apr.2024 CR.32662.V03; Added template param "C" = Collection, to allow for
 * specifying another collection type, if desired. Tested, but not using... went a
 * a differnt route.
 * Added the at() method for better backward compatibility with existing code which 
 * wants to access the data via a size_t offset.
 * SLB 17.apr.2024 CR.32662.V03; Added template param "C" = Collection, to allow for
 * specifying another collection type, if desired. Tested, but not using... went a
 * a differnt route.
 * Added the at() method for better backward compatibility with existing code which 
 * wants to access the data via a size_t offset.
 * SLB 12.nov.2024 NoCR.V01; Changes to work when compiling as ISO C++ 20.
 * SLB 14.apr.2025 CR.33850.V01; needed a const version of at(), so created const GetVal()
 * which is thunked by both const and non-const versions of at().
 */
template <class V>
class CAttributesListPrimitive : 
   public CAttributesList<V> 
{
public:
	using TCollection = CAttributesList<V>::TCollection;
	using TItCollection = CAttributesList<V>::TItCollection;
	using TItcCollection = CAttributesList<V>::TItcCollection;

public:
   CAttributesListPrimitive(
      const CSpdCString &wsTagName,
      bool bDontAssignFromString,                                                   // CR.18552.V05; added.
      bool bUseLegacyXml=true,
      bool bUseSlimMode=false
      ) : 
      CAttributesList<V>(wsTagName, bUseLegacyXml, bUseSlimMode)
   {}
   CAttributesListPrimitive(
      const CAttributesListPrimitive &cpy, 
      const CSpdCString &wsTag                                                     // CR.22456; added.
      ) :
      CAttributesList<V>(cpy, wsTag)                                               // CR.22456; modified.
   {}
   CAttributesListPrimitive &operator = (const CAttributesListPrimitive &cpy)
   {
      CAttributesList<V>::operator = (cpy); 
      return *this; 
   }
   CAttributesListPrimitive<V> &operator = (const std::list<V> &cpy)						// CR.26999.Item82; added.
   {
      TCollection::operator = (cpy);
      return *this; 
   }

	const V& at(size_t _Pos) const																	// CR.33850.V01; added.
	{
		return this->GetVal(_Pos);
	}

	V& at(size_t _Pos) 																					// CR.32662.V03; added.
	{
		return (V&)this->GetVal(_Pos);																// CR.33850.V01; modified. 
	}

	V& operator [] (size_t _Pos)																		// CR.32662.V03; added.
	{
		return this->at(_Pos);
	}

	const V& operator [] (size_t _Pos) const														// CR.32662.V03; added.
	{
		return this->at(_Pos);
	}

   virtual void GetResourceMemberList(TAttribResourceList &arlAttribList) const 
   {
   }

protected:
	/* GetVal() - This method is used internally by the at() methods. Both const and
	 * non-const versions.
	 *
	 * SLB 14.apr.2025 CR.33850.V01; added.
	 --------------------------------------------------------------------------------*/
	const V& GetVal(
		size_t _Pos) const
	{
		if (_Pos >= this->size()) throw (std::out_of_range("Specified postion exceeds attributes list size."));

		size_t i(0);
		for (TItcCollection it(this->begin()); it != this->end(); it++, i++)
		{
			if (i == _Pos) return *it;
		}

		// should never get here.
		return *this->begin();
	}
	
	virtual size_t SerializeValue(
      const V &val,
      wchar_t *pwcsBuf, 
      size_t stBufCharLen, 
      bool bUseTag, 
      bool bUseContainerTag,
      bool bTransparentOn) const 
   {
      Primitive<V> v; 
      return v.Serialize(val, pwcsBuf, stBufCharLen, bTransparentOn); 
   }; 
   virtual size_t MaxSerializeLenValue(
      const V &val) const 
   {
      Primitive<V> v; 
      return v.MaxSerializeLen(val); 
   }
   virtual void DeserializeValue(
      const CSpdCString &wsXmlBuf,
      V &val, 
      bool bTransparentOn=true) 
   {
      Primitive<V> v; 
      v.Deserialize(wsXmlBuf, val, bTransparentOn); 
   }
}; 

/* 
 * template class: CAttributesListAttribsIf:
 *
 * SLB 22.apr.2016 CR.18552.V05; Modified constructor so that code cannot initialize with a single string param. This 
 * prevents the compiler from allowing assignment (operator =()) via a string. Thus, preventing code which may try to
 * initialize the class from an xml string (Deserialize() should always be used for that.)
 * SLB 26.oct.2016 CR.22456; Copy constructor now requires a tagname as a paramater.
 * SLB 17.jul.2019 CR.17482.V01; Fix for not over-riding IsResourceNeeded(). 
 * SLB 12.nov.2024 NoCR.V01; Changes to work when compiling as ISO C++ 20.
 */
template <class V>
class CAttributesListAttribsIf : 
   public CAttributesList<V> 
{
public:
	using TCollection = CAttributesList<V>::TCollection;
	using TItCollection = CAttributesList<V>::TItCollection;
	using TItcCollection = CAttributesList<V>::TItcCollection;

public:
   CAttributesListAttribsIf(
      const CSpdCString &wsTagName,
      bool bDontAssignFromString,                                                   // CR.18552.V05; added.
      bool bUseLegacyXml=true,
      bool bUseSlimMode=false) : 
      CAttributesList<V>(wsTagName, bUseLegacyXml, bUseSlimMode)
   {}
   CAttributesListAttribsIf(
      const CAttributesListAttribsIf &cpy,
      const CSpdCString &wsTag                                                      // CR.22456; added.
      ) :
      CAttributesList<V>(cpy, wsTag)                                                // CR.22456; modified.
   {}
   CAttributesListAttribsIf &operator = (const CAttributesListAttribsIf &cpy)
   {
      CAttributesList<V>::operator = (cpy); 
      return *this; 
   }
   virtual void GetResourceMemberList(TAttribResourceList &arlAttribList) const 
   {
      for (TItcCollection it(this->begin());  it != this->end();  it++)
      {
         it->GetResourceMemberList(arlAttribList); 
      }
   }
   virtual bool IsResourceNeeded(const CAttributeResourceIF *pAttrib) const         // CR.17482.V01; added.
   { 
      for (TItcCollection it(this->begin());  it != this->end();  it++)
      {
         if (!it->IsResourceNeeded(pAttrib)) continue; 
         
         return true;
      }
      return false;  
   }


protected:
   virtual size_t SerializeValue(
      const V &val,
      wchar_t *pwcsBuf, 
      size_t stBufCharLen, 
      bool bUseTag,
      bool bUseContainerTag,
      bool bTransparentOn) const 
   {
      return val.Serialize(pwcsBuf, stBufCharLen, bUseTag, bUseContainerTag, bTransparentOn); 
   }  
   virtual size_t MaxSerializeLenValue(
      const V &val) const 
   {
      return val.GetMaxSerializeCharLen(); 
   }
   virtual void DeserializeValue(
      const CSpdCString &wsXmlBuf,
      V &val, 
      bool bTransparentOn=true) 
   {
      val.Deserialize(wsXmlBuf, bTransparentOn); 
   }
}; 


/*
 * Template class: CAttributeResource
 *
 * Note: class T must always be derived from CResourceStringIF.
 * SLB 20.apr.2016 CR.21468; Changes to ensure that modifying the resource string will tag the attribute as modifed.
 * a) made m_tVal private, so access cannot be bi-passed by addressing the member directly.
 * b) made operator ->() return a const ptr to m_tVal. So, it can be accessed, but only for reading not for modifying.
 * c) Added 3 assignment operators so that the attribute can have the resource string assigned to it directly. These assignment
 * operators ensure that the m_bIsModified flag gets set.
 * d) Added SetResourceName() which can be used instead of assignment operator, provides symmetry with other SetXXX() methods already 
 * provided.
 * SLB 09.may.2016 CR.21553; Fix for setting and retrieving attribute description.
 * SLB 26.oct.2016 CR.22456; Added new copy constructor which requires a tagname as a paramater.
 * SLB 15.jul.2019 CR.17482; Added method so caller can update.change the value of a specific resource.
 */
template <class T>
class CAttributeResource : 
   public CAttributeResourceIF
{
   T m_tVal; 
   CSpdCString m_wsResourceDescription;                                             // CR.21553; added.
public:
   //
   // Required definition for part 1) constructors.
   //
   CAttributeResource(
      const CSpdCString &wsTagName,
      bool bDontAssignFromString,                                                   // CR.18552.V05; added.
      bool bUseLegacyXml,
      const CSpdCString &wsResourceDescription                                      // CR.21553; added.
      ) : 
      CAttributeResourceIF(wsTagName, bUseLegacyXml),
      m_wsResourceDescription(wsResourceDescription)                                // CR.21553; added.
   {
   }

   CAttributeResource(const CAttributeResource &c) : 
      CAttributeResourceIF(c),
      m_tVal(c.m_tVal),
      m_wsResourceDescription(c.m_wsResourceDescription)
   {}

   CAttributeResource(                                                              // CR.22456; added.
      const CAttributeResource &c,
      const CSpdCString &wsTag
      ) : 
      CAttributeResourceIF(c, wsTag),
      m_tVal(c.m_tVal),
      m_wsResourceDescription(c.m_wsResourceDescription)
   {}

   /* assignment operator ()
    * SLB 20.apr.2016 CR.21468; created.
   -------------------------------------------------------------------------------------------*/
   CAttributeResource & operator = (const CSpdCString &scsResourceName)
   {
      SetResourceName(scsResourceName); 
      return *this; 
   }
   /* assignment operator ()
    * SLB 20.apr.2016 CR.21468; created.
   -------------------------------------------------------------------------------------------*/
   CAttributeResource & operator = (const std::wstring &wsResourceName)
   {
      m_tVal.m_wsFullResourceName = wsResourceName.c_str(); 
      m_bIsModified = true; 
      return *this; 
   }
   /* assignment operator ()
    * SLB 20.apr.2016 CR.21468; created.
   -------------------------------------------------------------------------------------------*/
   CAttributeResource & operator = (const wchar_t *pwcsResourceName)
   {
      m_tVal.m_wsFullResourceName = pwcsResourceName; 
      m_bIsModified = true; 
      return *this; 
   }
   /* comparison operator ==()
    *
    * SLB 30.nov.2018 CR.7698; created.
   -------------------------------------------------------------------------------------------*/
   bool operator == (const CAttributeResource &cpy) const
   {
      return m_tVal.m_wsFullResourceName == cpy.m_tVal.m_wsFullResourceName;
   }
   /* comparison operator !=()
    *
    * SLB 30.nov.2018 CR.7698; created.
   -------------------------------------------------------------------------------------------*/
   bool operator != (const CAttributeResource &cpy) const
   {
      return !operator ==(cpy);
   }

   //
   // SLB 11.apr.2013 CR.15891.V04; modified access to local members... Now uses method
   // instead for resource type.
   //
   // XML Serializing/Deserializing methods.
   //
   virtual size_t Serialize(
      wchar_t *pwcsBuf, 
      size_t stBufCharLen, 
      bool bUseTag=true, 
      bool bUseContainerTag=false, 
      bool bTransparentOn=false) const 
   {
      //
      // Streamed out version of this object looks like:
      //
      // <CAR>
      //   <t>1</t>
      //   <n>AB0934779523</n>
      // </CAR>
      //
      size_t stWriteOff(0); 
      stWriteOff += SerializeBegin(pwcsBuf+stWriteOff, stBufCharLen-stWriteOff, bUseTag, bUseContainerTag); 

      int nWriteLen; 
      nWriteLen = _snwprintf_s(
         pwcsBuf+stWriteOff, stBufCharLen-stWriteOff, _TRUNCATE,
         L"<CAR><t>%X</t><n>%s</n></CAR>",
         m_tVal.GetResourceType(),
         SpdUtils::XmlEscapeString(m_tVal.m_wsFullResourceName).c_str()); 
      if (nWriteLen < 0) ThrowHr(E_FAIL, __WFUNCTION__, L"Failed to serialize Aliasable Resource. Buffer too small?"); 
      stWriteOff+=nWriteLen; 

      stWriteOff += SerializeEnd(pwcsBuf+stWriteOff, stBufCharLen-stWriteOff, bUseTag, bUseContainerTag); 
      return stWriteOff; 
   }

   size_t GetMaxSerializeCharLen() const 
   {
      //
      // Initialize length to that of tags uses: CAR, t, n.
      //
      size_t stMaxCharLen(25); 
      stMaxCharLen += 2; 
      stMaxCharLen += SpdUtils::XmlEscapeString(m_tVal.m_wsFullResourceName).size(); 
      return stMaxCharLen; 
   }

   /* Deserialize()
    *
    * SLB 24.jul.2012 Added support for legacy format. Because this attribute will typically replace an 
    * existing "string" type attribute, I have added support to initialize the object from both the legacy
    * format as well as the current format. This will save a lot of porting work for each Attrib class which 
    * gets changed to use Aliasable resources.
    * SLB 23.jul.2013 CR.17121.Item12; Fix for not un-escaping legacy form before assigning it to the 
    * m_wsFullResourceName member.
    * SLB 28.oct.2013 CR.17124.Item29; Fixed problem with de-serializing GUI generated attribs. It was encoding
    * the resource type in hex vs. decimal. Modified code to handle hex.
   ------------------------------------------------------------------------------------------------------*/
   void Deserialize(
      const CSpdCString &wsXmlBuf, 
      bool bTransparentOn=false, 
      bool bClearFirst=true) 
   {
      if (bClearFirst) Clear(); 
      CSpdCString wsClassData; 
      if (FindDataForTags(L"CAR", wsXmlBuf, wsClassData) == CSpdCString::npos)
      {  
         // Not a problem: This is probably legacy form of the stream. This means that the stream should just be 
         // assigned directly to the full name.
         m_tVal.m_wsFullResourceName = SpdUtils::XmlUnescapeString(wsXmlBuf);       // CR.17124.Item29; modified. CR.17121.Item12; modified.
         m_bIsModified = true; 

         // Debug Message for testing/debugging functionality. should be removed in the future.
         // If this message is displayed, then expect to see FullName set to a valid resource name.
         // For example, if it is a folder type resource, FullName should look like a 
         // valid UNC folder name.
         CEnterExitMsg::TraceMsg(L"%s() - Legacy form of XML string detected. m_wsFullResourceName has been set to: %s",
            L"CAttributeResource<T>",
            m_tVal.m_wsFullResourceName.c_str());                                   // CR.17121.Item12; modified.
      }
      else
      {  
         // class data is valid, look for type in data.
         CSpdCString wsTypeData; 
         CSpdCString wsResourceData; 
         if (FindDataForTags(L"t", wsClassData, wsTypeData) == CSpdCString::npos) ThrowHr(E_FAIL, __WFUNCTION__, L"Problem retrieving Resource type"); 
         if (FindDataForTags(L"n", wsClassData, wsResourceData) == CSpdCString::npos) ThrowHr(E_FAIL, __WFUNCTION__, L"Problem retrieving Resource data"); 

         // Convert type and resource data
         Primitive<T::TResourceType> rt; 
         rt.Deserialize(wsTypeData, m_tVal.m_rtType); 
         Primitive<CSpdCString> rn; 
         rn.Deserialize(wsResourceData, m_tVal.m_wsFullResourceName); 
         m_bIsModified = true; 
      }
   }

   /* GetDescriptiveName() - This method returns a description for the resource type.
    *
    * SLB 01.apr.2016 CR.18552.V04; created.
   -----------------------------------------------------------------------------------------------------*/
   const wchar_t *GetDescriptiveName() const
   {
      switch (GetResourceType())
      {
      case rtPlaceHolder: return L"Place Holder"; 
      case rtFolderName: return L"Folder Name"; 
      case rtFileName: return L"File Name"; 
      case rtPclMetaDriver: return L"PCL::Meta Driver option set"; 
      case rtPclMetaMedia: return L"PCL::Meta Media option set"; 
      case rtPclMetaOutput: return L"PCL::Meta Output option set"; 
      case rtAfpdsSharedResource: return L"AFPDS Shared resource"; 
      case rtRje3211Fcb: return L"RJE/3211 FCB"; 
      case rtMachineName: return L"Machine Name"; 
      case rtDbsCheckpoint: return L"Solitrack Checkpoint"; 
      case rtDbsMonitor: return L"Solitrack Monitor"; 
      }
      return L"Invalid resource type"; 
   }
   virtual const wchar_t *GetAttribsClassName() const { return L"GetAttribsClassName() not implemented."; } 
   virtual void GetResourceMemberList(TAttribResourceList &arlAttribList) const {}; 
   virtual bool IsResourceNeeded(const CAttributeResourceIF *pAttrib) const { return false; } 

   const T * operator ->() const { return &m_tVal; } 

   virtual void Clear() { m_tVal.Clear(); } 
   virtual size_t Size() const { return m_tVal.Size(); } 
   virtual bool IsEmpty() const { return m_tVal.IsEmpty(); } 

   /* IsMemberAnAliasableResource()
    *
    * SLB 14.jun.2012 CR.15891.V02; created.
   ------------------------------------------------------------------------------------------*/
   virtual bool IsAnAliasedResource() const 
   { 
      return m_tVal.IsResourceAnAlias();  
   }

   /* GetAliasResourceName()
    *
    * SLB 14.jun.2012 CR.15891.V02; created.
   ------------------------------------------------------------------------------------------*/
   virtual CSpdCString GetAliasResourceName() const 
   { 
      return m_tVal.C_str();  
   }

   /* SetAliasResourceName()
    *
    * SLB 12.jul.2019 CR.17482; created.
   ------------------------------------------------------------------------------------------*/
   virtual void SetAliasResourceName(
      const CSpdCString &wsNewName) 
   { 
      m_tVal.SetAliasResourceName(wsNewName); 
   }

   virtual bool IsResourceAnAlias() const                                           // CR.15891.V02; added.
   {
      return m_tVal.IsResourceAnAlias(); 
   }

   virtual CSpdCString GetResourceName() const 
   {
      return m_tVal.GetResourceName(); 
   }; 
   virtual CResourceStringIF::TResourceType GetResourceType() const                 // CR.15891.V02; added.
   {
      return m_tVal.GetResourceType(); 
   }

   virtual TPackageOptionsDesired GetPackageOptionsDesired() const                  // CR.15891.V06; modified; CR.15891.V04; added.
   {
      return m_tVal.GetPackageOptionsDesired(); 
   }

   TValidationOptions GetValidationOptions() const                                  // CR.15891.V04; added.
   {
      return m_tVal.GetValidationOptions(); 
   }

   TRuntimeOptions GetRuntimeOptions() const                                        // CR.15891.V04; added.
   {
      return m_tVal.GetRuntimeOptions(); 
   }

   virtual void SetResourceName(const CSpdCString &scs)                             // CR.21648; added.
   {
      m_tVal.m_wsFullResourceName = scs; 
      m_bIsModified = true; 
   }

   virtual void SetPackageOptionsDesired(                                           // CR.15891.V04; added.
      CResourceStringIF::TPackageOptionsDesired pod)
   {
      m_tVal.SetPackageOptionsDesired(pod); 
      m_bIsModified = true; 
   }

   virtual void SetValidationOptions(                                               // CR.15891.V04; added.
      CResourceStringIF::TValidationOptions vo)
   {
      m_tVal.SetValidationOptions(vo); 
      m_bIsModified = true; 
   }

   virtual void SetRuntimeOptions(                                                  // CR.15891.V04; added.
      CResourceStringIF::TRuntimeOptions ro)
   {
      m_tVal.SetRuntimeOptions(ro); 
      m_bIsModified = true; 
   }

   virtual CSpdCString GetResourceDescription() const                               // CR.21553; added.
   {
      return m_wsResourceDescription; 
   }
}; 

typedef CAttributeResource<TAliasPlaceHolder> CStreamableResPlaceHolder;            // CR.15891.V02; added.
typedef CAttributeResource<TAliasFolderName> CStreamableResFolderName;              // CR.15891.V02; added.
typedef CAttributeResource<TAliasFileName> CStreamableResFileName;                  // CR.15891.V02; added.
typedef CAttributeResource<TAliasPclMetaDriver> CStreamableResPclMetaDriver;        // CR.15891.V04; added.
typedef CAttributeResource<TAliasPclMetaMedia> CStreamableResPclMetaMedia;          // CR.15891.V04; added.
typedef CAttributeResource<TAliasPclMetaOutput> CStreamableResPclMetaOutput;        // CR.15891.V04; added.
typedef CAttributeResource<TAliasAfpdsSharedResource> CStreamableResAfpdsSharedResource; // CR.15891.V04; added.
typedef CAttributeResource<TAliasRje3211Fcb> CStreamableResRje3211Fcb;              // CR.15891.V04; added.
typedef CAttributeResource<TAliasMachineName> CStreamableResMachineName;            // CR.15891.V04; added.
typedef CAttributeResource<TAliasDbsCheckpoint> CStreamableResDbsCheckPoint;        // CR.15891.V04; added.
typedef CAttributeResource<TAliasDbsMonitor> CStreamableResDbsMonitor;              // CR.15891.V04; added.


/*
 * class CAttributeComplexPrimitive
 *
 * SLB 20.apr.2016 CR.21468; Fix for not indicating value is modified when assignment operator is used.
 * SLB 26.oct.2016 CR.22456; Added new copy constructor which requires a tagname as a paramater.
 * SLB 28.mar.2023 CR.32290; Fix for not handling "default" behavior when an attribute of this type 
 * is initialized with an empty string. Now stores the default string, then the Clear() method 
 * initializes the underlying type with this default (vs. 0).
 * SLB 15.apr.2024 CR.32662.V03; Added a default constructor so that derived objects can be 
 * added to collections.
 * 
 */
template <class T>
class CAttributeComplexPrimitive : 
   public CAttributeIF,
   public T
{
	CSpdCString m_wsDefaultInit;																		// CR.32290; added.
public:
	CAttributeComplexPrimitive() :																	// CR.32662.V03; added.
		CAttributeIF(L"", false)
	{
	}

   //
   // Required definition for part 1) constructors.
   //
   CAttributeComplexPrimitive(
      const CSpdCString &wsTagName,
      bool bDontAssignFromString,                                                   // CR.18552.V05; added.
      bool bUseLegacyXml=false,
      const CSpdCString &wsDefault = L""                                            // CR.21547; added.
      ) : 
      CAttributeIF(wsTagName, bUseLegacyXml),
		m_wsDefaultInit(wsDefault),																	// CR.32290; added.
      T(wsDefault)                                                                  // CR.21547; modified.
   {
   }

   CAttributeComplexPrimitive(const CAttributeComplexPrimitive &c) : 
      CAttributeIF(c),
      T(c)
   {}

   CAttributeComplexPrimitive(                                                      // CR.22456; added.
      const CAttributeComplexPrimitive &c,
      const CSpdCString &wsTagName
      ) : 
      CAttributeIF(c, wsTagName),
      T(c)
   {}

   T &operator = (const T &cpy)
   {
      m_bIsModified = true;                                                         // CR.21468; added.
      return T::operator = (cpy); 
   }

   //
   // XML Serializing/Deserializing methods.
   //
   virtual size_t Serialize(wchar_t *pwcsBuf, size_t stBufCharLen, bool bUseTag=true, bool bUseContainerTag=false, bool bTransparentOn=false) const 
   {
      size_t stWriteOff(0); 
      stWriteOff += SerializeBegin(pwcsBuf+stWriteOff, stBufCharLen-stWriteOff, bUseTag, bUseContainerTag); 

      Primitive<T> p; 
      stWriteOff += p.Serialize(*this, pwcsBuf+stWriteOff, stBufCharLen-stWriteOff); 

      stWriteOff += SerializeEnd(pwcsBuf+stWriteOff, stBufCharLen-stWriteOff, bUseTag, bUseContainerTag); 
      return stWriteOff; 
   }

   /* GetMaxSerializeCharLen()
   ------------------------------------------------------------------------------------------------------*/
   size_t GetMaxSerializeCharLen() const 
   {
      // Max length presumes that bUseContainerTag==true. Initialize length to lengths of container tag brackets <> + </>
      size_t stMaxCharLen(5);             
      stMaxCharLen += 2*GetTagName().size(); 

      Primitive<T> p; 
      stMaxCharLen += p.MaxSerializeLen(*this); 
      return stMaxCharLen; 
   }

   /* Deserialize()
    *
    * SLB 27.apr.2016 CR.21493; Sets modified flag now. This fixes attributes serializing code never serizling
    * the complex primitive attrib members.
   ------------------------------------------------------------------------------------------------------*/
   void Deserialize(const CSpdCString &wsXmlBuf, bool bTransparentOn = false, bool bClearFirst = true) 
   {
      if (bClearFirst) Clear(); 
      Primitive<T> p; 
      p.Deserialize(wsXmlBuf, *this); 
      m_bIsModified = true;                                                         // CR.21493; added.
   }

   virtual const wchar_t* GetDescriptiveName() const { return L"GetDescriptiveName() not implemented."; }
   virtual const wchar_t *GetAttribsClassName() const { return L"GetAttribsClassName() not implemented."; }
   virtual void GetResourceMemberList(TAttribResourceList &arlAttribList) const {}; 
   virtual bool IsResourceNeeded(const CAttributeResourceIF *pAttrib) const { return false; }
   virtual void Clear() { T::operator = (m_wsDefaultInit); ClearModified(); }			// CR.32290; modified. CR.21493; modified.
}; 

// CR.32290; comment out the T=CBuffer Clear() over-ride. Default functionality should work now.
//void CAttributeComplexPrimitive<CBuffer>::Clear() { CBuffer::Clear(); ClearModified(); } // CR.21493; modified.
inline void CAttributeComplexPrimitive<wstring_crypto>::Clear() { wstring_crypto::clear(); ClearModified(); } // CR.21493; modified.

typedef CAttributeComplexPrimitive<CBuffer> CAttributeCBuffer; 

} // end of namespace


/* class CLicFILETIME
 *
 * A FILETIME overload which adds support for timestamp stored in a VARIANT 
 * (AKA .NET time) format. 
 * This definition really should go in a different file, but this is convenient 
 * and I'm being lazy. It is intentionally not in the attributes namespace
 * 
 * SLB 17.jul.2025 CR.34222; Created.
 */
class CLicFILETIME : public CFILETIME																// CR.34222; added.
{
public:
	CLicFILETIME() : CFILETIME() {}
	CLicFILETIME(const ::FILETIME& ft) : CFILETIME(ft) {}
	CLicFILETIME(QUADWORD qw) : CFILETIME(qw) {}
	CLicFILETIME(time_t tt) : CFILETIME(tt) {}
	CLicFILETIME(const SYSTEMTIME& st) : CFILETIME(st) {}

	CLicFILETIME(const VARIANT& vt)	
	{
		this->operator = (vt);
	}

	CFILETIME& operator = (const VARIANT& vt)	
	{
		SYSTEMTIME st;
		VariantTimeToSystemTime(vt.dblVal, &st);
		return CFILETIME::operator = (st);
	}

	operator CFILETIME() { return *this; }
};

#endif