#ifndef _LicenseError_h_9515ABE0E22648899A90CF0001BBBB05_
#define _LicenseError_h_9515ABE0E22648899A90CF0001BBBB05_

#include <windows.h>
#include <string>

namespace LicenseServerError
{
	/* Custom Error Base   HR Error Codes should all offset from this base. */
	const unsigned long ITF_MIN				= 0x00000;
	const unsigned long ITF_CR_MIN			= ITF_MIN+0x9000;
	const unsigned long ITF_LIC_SVR_OFFSET	= ITF_CR_MIN+0x0000;
	const unsigned long ITF_RNBO_OFFSET		= ITF_CR_MIN+0x0100;
	const unsigned long ITF_MAX				= 0xFFFF;
	
#ifndef SP_ACCESS_DENIED	//Rainbow API Error Codes
	const unsigned long SP_INVALID_FUNCTION_CODE = 1;
	const unsigned long SP_INVALID_PACKET = 2;
	const unsigned long SP_UNIT_NOT_FOUND = 3;
	const unsigned long SP_ACCESS_DENIED = 4;
	const unsigned long SP_INVALID_MEMORY_ADDRESS = 5;
	const unsigned long SP_INVALID_ACCESS_CODE = 6;
	const unsigned long SP_PORT_IS_BUSY = 7;
	const unsigned long SP_WRITE_NOT_READY = 8;
	const unsigned long SP_NO_PORT_FOUND = 9;
	const unsigned long SP_ALREADY_ZERO = 10;
	const unsigned long SP_DRIVER_NOT_INSTALLED = 12;
	const unsigned long SP_COMMUNICATIONS_ERROR = 13;
	const unsigned long SP_VERSION_NOT_SUPPORTED = 18;
	const unsigned long SP_OS_ENVIRONMENT_NOT_SUPPORTED = 19;
	const unsigned long SP_QUERY_TOO_LONG = 20;
	const unsigned long SP_DRIVER_IS_BUSY = 30;
	const unsigned long SP_PORT_ALLOCATION_FAILURE = 31;
	const unsigned long SP_PORT_RELEASE_FAILURE = 32;
	const unsigned long SP_ACQUIRE_PORT_TIMEOUT = 39;
	const unsigned long SP_SIGNAL_NOT_SUPPORTED = 42;
	const unsigned long SP_INIT_NOT_CALLED = 57;
	const unsigned long SP_DRIVER_TYPE_NOT_SUPPORTED = 58;
	const unsigned long SP_FAIL_ON_DRIVER_COMM = 59;
	const unsigned long SP_SERVER_PROBABLY_NOT_UP = 60;
	const unsigned long SP_UNKNOWN_HOST = 61;
	const unsigned long SP_SENDTO_FAILED = 62;
	const unsigned long SP_SOCKET_CREATION_FAILED = 63;
	const unsigned long SP_NORESOURCES = 64;
	const unsigned long SP_BROADCAST_NOT_SUPPORTED = 65;
	const unsigned long SP_BAD_SERVER_MESSAGE = 66;
	const unsigned long SP_NO_SERVER_RUNNING = 67;
	const unsigned long SP_NO_NETWORK = 68;
	const unsigned long SP_NO_SERVER_RESPONSE = 69;
	const unsigned long SP_NO_LICENSE_AVAILABLE = 70;
	const unsigned long SP_INVALID_LICENSE = 71;
	const unsigned long SP_INVALID_OPERATION = 72;
	const unsigned long SP_BUFFER_TOO_SMALL = 73;
	const unsigned long SP_INTERNAL_ERROR = 74;
	const unsigned long SP_PACKET_ALREADY_INITIALIZED = 75;
#endif

	//07-01-11 - JWL 
	//Note: This is a rainbow error that is not defined in current 3rd party .h file.  
	//If receive a new .h file and receive an error because it is already defined, move
	//this above.
	const unsigned long SP_INVALID_STATUS = 255;

	/* Error Codes used for custom HRESULTs. */
	const unsigned long EC_UNKNOWN					= ITF_LIC_SVR_OFFSET + 1;
	const unsigned long EC_DRIVER_INIT_FAILURE		= ITF_LIC_SVR_OFFSET + 2;
	const unsigned long EC_PASSWORD_NO_MATCH		= ITF_LIC_SVR_OFFSET + 3;
	const unsigned long EC_PASSWORD_INVALID_FORMAT	= ITF_LIC_SVR_OFFSET + 4;
	const unsigned long EC_LICENSE_INSUFFICIENT		= ITF_LIC_SVR_OFFSET + 5;
	const unsigned long EC_LICENSE_INVALID			= ITF_LIC_SVR_OFFSET + 6;
	const unsigned long EC_LICENSE_EXPRIED			= ITF_LIC_SVR_OFFSET + 7;
	const unsigned long EC_KEY_TRIAL_EXPIRED		= ITF_LIC_SVR_OFFSET + 8;
	const unsigned long EC_KEY_NOT_PRESENT			= ITF_LIC_SVR_OFFSET + 9;
	const unsigned long EC_CLOCK_ERROR				= ITF_LIC_SVR_OFFSET + 10;
	const unsigned long EC_KEY_WRITE_FAILURE		= ITF_LIC_SVR_OFFSET + 11;
	const unsigned long EC_KEY_WRITE_ACCESS_DENIED	= ITF_LIC_SVR_OFFSET + 12;
	const unsigned long EC_KEY_NOT_ACTIVATED		= ITF_LIC_SVR_OFFSET + 13;
	const unsigned long EC_AUTHENTICATION_FAILURE	= ITF_LIC_SVR_OFFSET + 14;
	const unsigned long EC_MANAGER_NOT_INITIALIZED	= ITF_LIC_SVR_OFFSET + 15;
	const unsigned long EC_KEY_NO_SUITABLE_KEY		= ITF_LIC_SVR_OFFSET + 16;
	const unsigned long EC_KEY_LOCKED				= ITF_LIC_SVR_OFFSET + 17;
	const unsigned long EC_CLIENT_TIMEOUT			= ITF_LIC_SVR_OFFSET + 18;
	const unsigned long EC_PACKET_EXPIRED			= ITF_LIC_SVR_OFFSET + 19;
	
	// Rainbow driver errors
	const unsigned long EC_SP_INVALID_FUNCTION_CODE		= ITF_RNBO_OFFSET + SP_INVALID_FUNCTION_CODE;
	const unsigned long EC_SP_INVALID_PACKET			= ITF_RNBO_OFFSET + SP_INVALID_PACKET;
    const unsigned long EC_SP_UNIT_NOT_FOUND			= ITF_RNBO_OFFSET + SP_UNIT_NOT_FOUND;
	const unsigned long EC_SP_ACCESS_DENIED				= ITF_RNBO_OFFSET + SP_ACCESS_DENIED;
	const unsigned long EC_SP_INVALID_MEMORY_ADDRESS	= ITF_RNBO_OFFSET + SP_INVALID_MEMORY_ADDRESS;
	const unsigned long EC_SP_INVALID_ACCESS_CODE		= ITF_RNBO_OFFSET + SP_INVALID_ACCESS_CODE;
	const unsigned long EC_SP_PORT_IS_BUSY				= ITF_RNBO_OFFSET + SP_PORT_IS_BUSY;
	const unsigned long EC_SP_WRITE_NOT_READY			= ITF_RNBO_OFFSET + SP_WRITE_NOT_READY;
	const unsigned long EC_SP_NO_PORT_FOUND				= ITF_RNBO_OFFSET + SP_NO_PORT_FOUND;
	const unsigned long EC_SP_ALREADY_ZERO				= ITF_RNBO_OFFSET + SP_ALREADY_ZERO;
	const unsigned long EC_SP_DRIVER_NOT_INSTALLED		= ITF_RNBO_OFFSET + SP_DRIVER_NOT_INSTALLED;
	const unsigned long EC_SP_VERSION_NOT_SUPPORTED		= ITF_RNBO_OFFSET + SP_VERSION_NOT_SUPPORTED;
	const unsigned long EC_SP_QUERY_TOO_LONG			= ITF_RNBO_OFFSET + SP_QUERY_TOO_LONG;
	const unsigned long EC_SP_DRIVER_IS_BUSY			= ITF_RNBO_OFFSET + SP_DRIVER_IS_BUSY;
	const unsigned long EC_SP_PORT_ALLOCATION_FAILURE	= ITF_RNBO_OFFSET + SP_PORT_ALLOCATION_FAILURE;
	const unsigned long EC_SP_PORT_RELEASE_FAILURE		= ITF_RNBO_OFFSET + SP_PORT_RELEASE_FAILURE;
	const unsigned long EC_SP_ACQUIRE_PORT_TIMEOUT		= ITF_RNBO_OFFSET + SP_ACQUIRE_PORT_TIMEOUT;
	const unsigned long EC_SP_SIGNAL_NOT_SUPPORTED		= ITF_RNBO_OFFSET + SP_SIGNAL_NOT_SUPPORTED;
	const unsigned long EC_SP_INIT_NOT_CALLED			= ITF_RNBO_OFFSET + SP_INIT_NOT_CALLED;
	const unsigned long EC_SP_FAIL_ON_DRIVER_COMM		= ITF_RNBO_OFFSET + SP_FAIL_ON_DRIVER_COMM;
	const unsigned long EC_SP_SERVER_PROBABLY_NOT_UP	= ITF_RNBO_OFFSET + SP_SERVER_PROBABLY_NOT_UP;
	const unsigned long EC_SP_UNKNOWN_HOST				= ITF_RNBO_OFFSET + SP_UNKNOWN_HOST;
	const unsigned long EC_SP_SENDTO_FAILED				= ITF_RNBO_OFFSET + SP_SENDTO_FAILED;
	const unsigned long EC_SP_SOCKET_CREATION_FAILED	= ITF_RNBO_OFFSET + SP_SOCKET_CREATION_FAILED;
	const unsigned long EC_SP_NORESOURCES				= ITF_RNBO_OFFSET + SP_NORESOURCES;
	const unsigned long EC_SP_BROADCAST_NOT_SUPPORTED	= ITF_RNBO_OFFSET + SP_BROADCAST_NOT_SUPPORTED;
	const unsigned long EC_SP_BAD_SERVER_MESSAGE		= ITF_RNBO_OFFSET + SP_BAD_SERVER_MESSAGE;
	const unsigned long EC_SP_NO_SERVER_RUNNING			= ITF_RNBO_OFFSET + SP_NO_SERVER_RUNNING;
	const unsigned long EC_SP_NO_NETWORK				= ITF_RNBO_OFFSET + SP_NO_NETWORK;
	const unsigned long EC_SP_NO_SERVER_RESPONSE		= ITF_RNBO_OFFSET + SP_NO_SERVER_RESPONSE;
	const unsigned long EC_SP_NO_LICENSE_AVAILABLE		= ITF_RNBO_OFFSET + SP_NO_LICENSE_AVAILABLE;
	const unsigned long EC_SP_INVALID_LICENSE			= ITF_RNBO_OFFSET + SP_INVALID_LICENSE;
	const unsigned long EC_SP_INVALID_OPERATION			= ITF_RNBO_OFFSET + SP_INVALID_OPERATION;
	const unsigned long EC_SP_BUFFER_TOO_SMALL			= ITF_RNBO_OFFSET + SP_BUFFER_TOO_SMALL;
	const unsigned long EC_SP_INTERNAL_ERROR			= ITF_RNBO_OFFSET + SP_INTERNAL_ERROR;
	const unsigned long EC_SP_PACKET_ALREADY_INITIALIZED= ITF_RNBO_OFFSET + SP_PACKET_ALREADY_INITIALIZED;
	const unsigned long EC_SP_INVALID_STATUS			= ITF_RNBO_OFFSET + SP_INVALID_STATUS;
	
	
	/* HRESULTS defined from custom error codes above. */
	const HRESULT EHR_UNKNOWN						= MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, EC_UNKNOWN);
	const HRESULT EHR_DRIVER_INIT_FAILURE			= MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, EC_DRIVER_INIT_FAILURE);
	const HRESULT EHR_PASSWORD_NO_MATCH				= MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, EC_PASSWORD_NO_MATCH);
	const HRESULT EHR_PASSWORD_INVALID_FORMAT		= MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, EC_PASSWORD_INVALID_FORMAT);
	const HRESULT EHR_LICENSE_INSUFFICIENT			= MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, EC_LICENSE_INSUFFICIENT);
	const HRESULT EHR_LICENSE_INVALID				= MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, EC_LICENSE_INVALID);
	const HRESULT EHR_LICENSE_EXPRIED				= MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, EC_LICENSE_EXPRIED);
	const HRESULT EHR_KEY_TRIAL_EXPIRED				= MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, EC_KEY_TRIAL_EXPIRED);
	const HRESULT EHR_KEY_NOT_PRESENT				= MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, EC_KEY_NOT_PRESENT);
	const HRESULT EHR_CLOCK_ERROR					= MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, EC_CLOCK_ERROR);
	const HRESULT EHR_KEY_WRITE_FAILURE				= MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, EC_KEY_WRITE_FAILURE);
	const HRESULT EHR_KEY_WRITE_ACCESS_DENIED		= MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, EC_KEY_WRITE_ACCESS_DENIED);
	const HRESULT EHR_KEY_NOT_ACTIVATED				= MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, EC_KEY_NOT_ACTIVATED);
	const HRESULT EHR_AUTHENTICATION_FAILURE		= MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, EC_AUTHENTICATION_FAILURE);
	const HRESULT EHR_MANAGER_NOT_INITIALIZED		= MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, EC_MANAGER_NOT_INITIALIZED);
	const HRESULT EHR_KEY_NO_SUITABLE_KEY			= MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, EC_KEY_NO_SUITABLE_KEY);
	const HRESULT EHR_KEY_LOCKED					= MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, EC_KEY_LOCKED);
	const HRESULT EHR_CLIENT_TIMEOUT				= MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, EC_CLIENT_TIMEOUT);
	const HRESULT EHR_PACKET_EXPIRED				= MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, EC_PACKET_EXPIRED);
	
	const HRESULT EHR_SP_INVALID_FUNCTION_CODE		= MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, EC_SP_INVALID_FUNCTION_CODE);
	const HRESULT EHR_SP_INVALID_PACKET				= MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, EC_SP_INVALID_PACKET);
	const HRESULT EHR_SP_UNIT_NOT_FOUND				= MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, EC_SP_UNIT_NOT_FOUND);
	const HRESULT EHR_SP_ACCESS_DENIED				= MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, EC_SP_ACCESS_DENIED);
	const HRESULT EHR_SP_INVALID_MEMORY_ADDRESS		= MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, EC_SP_INVALID_MEMORY_ADDRESS);
	const HRESULT EHR_SP_INVALID_ACCESS_CODE		= MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, EC_SP_INVALID_ACCESS_CODE);
	const HRESULT EHR_SP_PORT_IS_BUSY				= MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, EC_SP_PORT_IS_BUSY);
	const HRESULT EHR_SP_WRITE_NOT_READY			= MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, EC_SP_WRITE_NOT_READY);
	const HRESULT EHR_SP_NO_PORT_FOUND				= MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, EC_SP_NO_PORT_FOUND);
	const HRESULT EHR_SP_ALREADY_ZERO				= MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, EC_SP_ALREADY_ZERO);
	const HRESULT EHR_SP_DRIVER_NOT_INSTALLED		= MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, EC_SP_DRIVER_NOT_INSTALLED);
	const HRESULT EHR_SP_VERSION_NOT_SUPPORTED		= MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, EC_SP_VERSION_NOT_SUPPORTED);
	const HRESULT EHR_SP_QUERY_TOO_LONG				= MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, EC_SP_QUERY_TOO_LONG);
	const HRESULT EHR_SP_DRIVER_IS_BUSY				= MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, EC_SP_DRIVER_IS_BUSY);
	const HRESULT EHR_SP_PORT_ALLOCATION_FAILURE	= MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, EC_SP_PORT_ALLOCATION_FAILURE);
	const HRESULT EHR_SP_PORT_RELEASE_FAILURE		= MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, EC_SP_PORT_RELEASE_FAILURE);
	const HRESULT EHR_SP_ACQUIRE_PORT_TIMEOUT		= MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, EC_SP_ACQUIRE_PORT_TIMEOUT);
	const HRESULT EHR_SP_SIGNAL_NOT_SUPPORTED		= MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, EC_SP_SIGNAL_NOT_SUPPORTED);
	const HRESULT EHR_SP_INIT_NOT_CALLED			= MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, EC_SP_INIT_NOT_CALLED);
	const HRESULT EHR_SP_FAIL_ON_DRIVER_COMM		= MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, EC_SP_FAIL_ON_DRIVER_COMM);
	const HRESULT EHR_SP_SERVER_PROBABLY_NOT_UP		= MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, EC_SP_SERVER_PROBABLY_NOT_UP);
	const HRESULT EHR_SP_UNKNOWN_HOST				= MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, EC_SP_UNKNOWN_HOST);
	const HRESULT EHR_SP_SENDTO_FAILED				= MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, EC_SP_SENDTO_FAILED);
	const HRESULT EHR_SP_SOCKET_CREATION_FAILED		= MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, EC_SP_SOCKET_CREATION_FAILED);
	const HRESULT EHR_SP_NORESOURCES				= MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, EC_SP_NORESOURCES);
	const HRESULT EHR_SP_BROADCAST_NOT_SUPPORTED	= MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, EC_SP_BROADCAST_NOT_SUPPORTED);
	const HRESULT EHR_SP_BAD_SERVER_MESSAGE			= MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, EC_SP_BAD_SERVER_MESSAGE);
	const HRESULT EHR_SP_NO_SERVER_RUNNING			= MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, EC_SP_NO_SERVER_RUNNING);
	const HRESULT EHR_SP_NO_NETWORK					= MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, EC_SP_NO_NETWORK);
	const HRESULT EHR_SP_NO_SERVER_RESPONSE			= MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, EC_SP_NO_SERVER_RESPONSE);
	const HRESULT EHR_SP_NO_LICENSE_AVAILABLE		= MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, EC_SP_NO_LICENSE_AVAILABLE);
	const HRESULT EHR_SP_INVALID_LICENSE			= MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, EC_SP_INVALID_LICENSE);
	const HRESULT EHR_SP_INVALID_OPERATION			= MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, EC_SP_INVALID_OPERATION);
	const HRESULT EHR_SP_BUFFER_TOO_SMALL			= MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, EC_SP_BUFFER_TOO_SMALL);
	const HRESULT EHR_SP_INTERNAL_ERROR				= MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, EC_SP_INTERNAL_ERROR);
	const HRESULT EHR_SP_PACKET_ALREADY_INITIALIZED	= MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, EC_SP_PACKET_ALREADY_INITIALIZED);
	const HRESULT EHR_SP_INVALID_STATUS				= MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, EC_SP_INVALID_STATUS);
	
	/*
	* SL_ERROR - Solimar License Error
	*/
	typedef struct _SL_ERROR {
		unsigned long	EC;
		HRESULT			HR;
		wchar_t*		message;
	} SL_ERROR;

	std::wstring GetErrorMessage(HRESULT hr);
	std::wstring GetECMessage(unsigned long echr);
	HRESULT WriteEventLog(wchar_t *event_log_msg, unsigned int event_type);


	/*
	* SL_IS_LIC_HR()
	*
	* Determin if hr is a Lic hr
	*/

	#define SL_IS_LIC_HR(hr) \
		((hr) & ITF_CR_MIN)

	/*
	* SL_EC_FROM_EHR()
	*
	* Extracts the error code code portion from an HRESULT.
	*/
	#define SL_EC_FROM_EHR(hr) \
		((hr) & 0x0000FFFF)
};
#endif