#ifndef __LICENSEREGISTRYKEYS_H
#define __LICENSEREGISTRYKEYS_H

#define REGISTRY_LICENSING_BASE					L"SOFTWARE\\Solimar\\Solimar Licensing"
#define REGISTRY_LICENSINGSERVER_KEY			L"SolimarLicenseServer"
#define REGISTRY_LICENSING_SERVERNAME_VALUE	L"ServerName"
#define REGISTRY_LICENSING_BACKUP_VALUE		L"Backup"
#define REGISTRY_LICENSING_SHARED_VALUE		L"Shared"



#endif
