
import re, string, xml.dom.minidom, copy

def NameToDefineName(prefix,n):
	s = prefix + ' ' + n
	s = string.upper(s)
	s = re.sub(' +','_',s)
	return s

def isNumeric(s):
	return re.search(r'\d+',s)


def XMLProcessProductFormat(node, productMap):
	products = {}
	for child in node.childNodes:
		if (child.nodeName==u'Lic_ProductSoftwareSpecAttribs'):
			pSpec = productSpec()
			pSpec.attribsMap = {}
			pSpec.modulesMap = {}
			XMLProcessAttribs(child, pSpec.attribsMap)
			XMLProcessModuleMapFormat(child, pSpec.modulesMap)
			productMap[pSpec.attribsMap['productID']] = pSpec

def XMLProcessModuleMapFormat(node, moduleMap):
	for child in node.childNodes:
		if (child.nodeName==u'Lic_ModuleSoftwareSpecAttribsMap'):
			XMLProcessModuleFormat(child, moduleMap)
def XMLProcessModuleFormat(node, moduleMap):
	for child in node.childNodes:
		if (child.nodeName==u'Lic_ModuleSoftwareSpecAttribs'):
			#print child.nodeName
			mSpec = moduleSpec()
			mSpec.attribsMap = {}
			XMLProcessAttribs(child, mSpec.attribsMap)
			moduleMap[mSpec.attribsMap['moduleID']] = mSpec;

	#print all the modules...
	#for modSpecKey, modSpecValue in moduleMap.iteritems():
	#	print modSpecKey
	#	print modSpecValue.attribsMap

	
def XMLProcessAttribs(node, attribMap):
	#attribMap = {}
	for i in range(node.attributes.length):
		attribMap[node.attributes.item(i).nodeName] = node.attributes.item(i).nodeValue
		#print node.attributes.item(i).nodeName + ', ' + node.attributes.item(i).nodeValue

def ConvertSoftwareSpecToH(swSpec) :
	fout_product = open('.\\SoftwareProductSpecInitialize.h','w')
	fout_product.write('//\n')
	fout_product.write('//This file is generated by SoftwareSpecXMLCompiler.py\n')
	fout_product.write('\n')
	
	fout = open('.\\SoftwareSpecInitialize.h','w')
	fout.write('//\n')
	fout.write('//This file is generated by SoftwareSpecXMLCompiler.py\n')
	fout.write('\n')
	#print "Attribs Map - "
	#print swSpec['attribsMap']
	
	# Doesn't do complex swSpecAttribValue
	for swSpecAttribKey, swSpecAttribValue in swSpec['attribsMap'].iteritems():
		fout.write('softwareSpec.%s = %s;\n' % (swSpecAttribKey, swSpecAttribValue,))
	
	for prodSpecKey, prodSpecValue in swSpec['productsMap'].iteritems():
		#print prodSpecKey
		#print prodSpecValue.attribsMap
		#print prodSpecValue.modulesMap
		
		prodFunctionName = 'InititalizeProduct' + prodSpecKey + '()'
		fout_product.write('void %s\n{\n' % (prodFunctionName))
		fout_product.write('\tLic_PackageAttribs::Lic_ProductSoftwareSpecAttribs* pTmpProdSpec;\n')

		fout.write('%s;\n' % (prodFunctionName))

		fout_product.write('\t\n')
		fout_product.write('\t//\n')
		fout_product.write('\t// ProdID:%s, ProdName: %s\n' %(prodSpecKey, prodSpecValue.attribsMap['productName'],))
		fout_product.write('\tsoftwareSpec.productSpecMap->insert(Lic_PackageAttribs::Lic_SoftwareSpecAttribs::TMap_Lic_ProductSoftwareSpecAttribsMap::value_type(%s, Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs()));\n' % (prodSpecKey,))
		fout_product.write('\tpTmpProdSpec = &((softwareSpec.productSpecMap->find(%s))->second);\n'% (prodSpecKey,))
		fout_product.write('\tpTmpProdSpec->productID = %s;\n' % (prodSpecKey,))
		fout_product.write('\tpTmpProdSpec->productName = std::wstring(L"%s");\n' % (prodSpecValue.attribsMap['productName'],))
		if(prodSpecValue.attribsMap.has_key('sameModSpecProductID')):
			fout_product.write('\tpTmpProdSpec->sameModSpecProductID = %s;\n' % (prodSpecValue.attribsMap['sameModSpecProductID'],))
		if(prodSpecValue.attribsMap.has_key('prevSharedProductID')):
			fout_product.write('\tpTmpProdSpec->prevSharedProductID = %s;\n' % (prodSpecValue.attribsMap['prevSharedProductID'],))
		if(prodSpecValue.attribsMap.has_key('productLicType')):
			fout_product.write('\tpTmpProdSpec->productLicType = Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::%s;\n' % (prodSpecValue.attribsMap['productLicType'],))

		bFirstTime = 'true'
		for modSpecKey, modSpecValue in prodSpecValue.modulesMap.iteritems():
			if(bFirstTime == 'true'):
				fout_product.write('\n\tLic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs* pTmpModSpec;\n')
				bFirstTime = 'false'
			fout_product.write('\t\n')
			fout_product.write('\tpTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(%s, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));\n' % (modSpecKey,))
			fout_product.write('\tpTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(%s))->second);\n' % (modSpecKey,))
			fout_product.write('\tpTmpModSpec->moduleID = %s;\n' % (modSpecKey,))
			fout_product.write('\tpTmpModSpec->moduleName = std::wstring(L"%s");\n' % (modSpecValue.attribsMap['moduleName'],))
			
			if(modSpecValue.attribsMap.get('modUnlimitedValue',0) != 0):
				fout_product.write('\tpTmpModSpec->modUnlimitedValue = %s;\n' %(modSpecValue.attribsMap.get('modUnlimitedValue',0),))
				
			if(modSpecValue.attribsMap.get('moduleTrialLicense',-1) != -1):
				fout_product.write('\tpTmpModSpec->moduleTrialLicense = %s;\n' %(modSpecValue.attribsMap.get('moduleTrialLicense',0),))
			else:
					if(modSpecValue.attribsMap.get('modUnlimitedValue',-1) != -1):
						fout_product.write('\tpTmpModSpec->moduleTrialLicense = %s;\n' %(modSpecValue.attribsMap.get('modUnlimitedValue',0),))
					else:
						fout_product.write('\tpTmpModSpec->moduleTrialLicense = 127;\n')
			if(modSpecValue.attribsMap.get('modulePoolModuleID',0) != 0):
				fout_product.write('\tpTmpModSpec->modulePoolModuleID = %s;\n' %(modSpecValue.attribsMap.get('modulePoolModuleID',0),))
			if(modSpecValue.attribsMap.get('moduleDefaultLicense',0) != 0):
				fout_product.write('\tpTmpModSpec->moduleDefaultLicense = %s;\n' %(modSpecValue.attribsMap.get('moduleDefaultLicense',0),))
			if(modSpecValue.attribsMap.get('bModuleIsCounter','false') != 'false'):
				fout_product.write('\tpTmpModSpec->bModuleIsCounter = %s;\n' %(modSpecValue.attribsMap.get('bModuleIsCounter','false'),))
			if(modSpecValue.attribsMap.get('bModuleIsPool','false') != 'false'):
				fout_product.write('\tpTmpModSpec->bModuleIsPool = %s;\n' %(modSpecValue.attribsMap.get('bModuleIsPool','false'),))
			if(modSpecValue.attribsMap.get('moduleVersionIntroduced_Major',0) != 0):
				fout_product.write('\tpTmpModSpec->moduleVersionIntroduced_Major = %s;\n' %(modSpecValue.attribsMap.get('moduleVersionIntroduced_Major',0),))
			if(modSpecValue.attribsMap.get('moduleVersionIntroduced_Minor',0) != 0):				
				fout_product.write('\tpTmpModSpec->moduleVersionIntroduced_Minor = %s;\n' %(modSpecValue.attribsMap.get('moduleVersionIntroduced_Minor',0),))
			if(modSpecValue.attribsMap.get('moduleVersionIntroduced_SubMajor',0) != 0):
				fout_product.write('\tpTmpModSpec->moduleVersionIntroduced_SubMajor = %s;\n' %(modSpecValue.attribsMap.get('moduleVersionIntroduced_SubMajor',0),))
			if(modSpecValue.attribsMap.get('moduleVersionIntroduced_SubMinor',0) != 0):
				fout_product.write('\tpTmpModSpec->moduleVersionIntroduced_SubMinor = %s;\n' %(modSpecValue.attribsMap.get('moduleVersionIntroduced_SubMinor',0),))
			if(modSpecValue.attribsMap.get('moduleVersionDeprecated_Major',0) != 0):
				fout_product.write('\tpTmpModSpec->moduleVersionDeprecated_Major = %s;\n' %(modSpecValue.attribsMap.get('moduleVersionDeprecated_Major',0),))
			if(modSpecValue.attribsMap.get('moduleVersionDeprecated_Minor',0) != 0):
				fout_product.write('\tpTmpModSpec->moduleVersionDeprecated_Minor = %s;\n' %(modSpecValue.attribsMap.get('moduleVersionDeprecated_Minor',0),))
			if(modSpecValue.attribsMap.get('moduleVersionDeprecated_SubMajor',0) != 0):
				fout_product.write('\tpTmpModSpec->moduleVersionDeprecated_SubMajor = %s;\n' %(modSpecValue.attribsMap.get('moduleVersionDeprecated_SubMajor',0),))
			if(modSpecValue.attribsMap.get('moduleVersionDeprecated_SubMinor',0) != 0):
				fout_product.write('\tpTmpModSpec->moduleVersionDeprecated_SubMinor = %s;\n' %(modSpecValue.attribsMap.get('moduleVersionDeprecated_SubMinor',0),))
		fout_product.write('}\n')
		fout_product.write('\n')
	fout.close()
	fout_product.close()


def ConvertSoftwareSpecToCS(swSpec) :
	fout = open('.\\SoftwareSpecInstance.cs','w')

	fout.write('//\n')
	fout.write('//This file is generated by SoftwareSpecXMLCompiler.py\n')
	fout.write('\n')

	fout.write('using System;\n')
	fout.write('using System.Collections;\n')
	fout.write('using System.Collections.Specialized;\n')
	fout.write('namespace Solimar.Licensing\n')
	fout.write('{\n')
	fout.write('\tpublic class GlobalSoftwareSpec\n')
	fout.write('\t{\n')
	fout.write('\t\tpublic GlobalSoftwareSpec()\n')
	fout.write('\t\t{\n')
	fout.write('\t\t\tm_softwareSpec = new Solimar.Licensing.Attribs.Lic_PackageAttribs.Lic_SoftwareSpecAttribs();\n')
	# Doesn't do complex swSpecAttribValue
	for swSpecAttribKey, swSpecAttribValue in swSpec['attribsMap'].iteritems():
		fout.write('\t\t\tm_softwareSpec.%s.TVal = %s;\n' % (swSpecAttribKey, swSpecAttribValue,))
	fout.write('\t\t\t\n')

	fout.write('\t\t\tSolimar.Licensing.Attribs.Lic_PackageAttribs.Lic_ProductSoftwareSpecAttribs tmpProdSpec;\n')
	fout.write('\t\t\tSolimar.Licensing.Attribs.Lic_PackageAttribs.Lic_ModuleSoftwareSpecAttribs tmpModSpec;\n')
	for prodSpecKey, prodSpecValue in swSpec['productsMap'].iteritems():
		#print prodSpecKey + ', ' + prodSpecValue.attribsMap['productName']
		fout.write('\t\t\t\n')
		fout.write('\t\t\t#region ProdID:%s, ProdName: %s\n' %(prodSpecKey, prodSpecValue.attribsMap['productName'],))
		fout.write('\t\t\ttmpProdSpec = new Solimar.Licensing.Attribs.Lic_PackageAttribs.Lic_ProductSoftwareSpecAttribs();\n')
		fout.write('\t\t\ttmpProdSpec.productID.TVal = %s;\n' % ( prodSpecKey,))
		fout.write('\t\t\ttmpProdSpec.productName.TVal = "%s";\n' % (prodSpecValue.attribsMap['productName'],))
		if(prodSpecValue.attribsMap.has_key('sameModSpecProductID')):
			fout.write('\t\t\ttmpProdSpec.sameModSpecProductID.TVal = %s;\n' % (prodSpecValue.attribsMap['sameModSpecProductID'],))
		if(prodSpecValue.attribsMap.has_key('prevSharedProductID')):
			fout.write('\t\t\ttmpProdSpec.prevSharedProductID.TVal = %s;\n' % (prodSpecValue.attribsMap['prevSharedProductID'],))
		if(prodSpecValue.attribsMap.has_key('productLicType')):
			fout.write('\t\t\ttmpProdSpec.productLicType.EVal = Solimar.Licensing.Attribs.Lic_PackageAttribs.Lic_ProductSoftwareSpecAttribs.TProductLicenseType.%s;\n' % (prodSpecValue.attribsMap['productLicType'],))
		fout.write('\t\t\tm_softwareSpec.productSpecMap.TVal.Add(tmpProdSpec.productID.TVal, tmpProdSpec);\n')

		for modSpecKey, modSpecValue in prodSpecValue.modulesMap.iteritems():
			fout.write('\n')
			fout.write('\t\t\ttmpModSpec = new Solimar.Licensing.Attribs.Lic_PackageAttribs.Lic_ModuleSoftwareSpecAttribs();\n')
			fout.write('\t\t\ttmpModSpec.moduleID.TVal = %s;\n' % (modSpecKey,))
			fout.write('\t\t\ttmpModSpec.moduleName.TVal = "%s";\n' % (modSpecValue.attribsMap['moduleName'],))
			fout.write('\t\t\ttmpModSpec.modUnlimitedValue.TVal = %s;\n' %(modSpecValue.attribsMap.get('modUnlimitedValue',0),))
			if(modSpecValue.attribsMap.get('moduleTrialLicense',-1) != -1):
				fout.write('\t\t\ttmpModSpec.moduleTrialLicense.TVal = %s;\n' %(modSpecValue.attribsMap.get('moduleTrialLicense',0),))
			else:
				if(modSpecValue.attribsMap.get('modUnlimitedValue',-1) != -1):
					fout.write('\t\t\ttmpModSpec.moduleTrialLicense.TVal = %s;\n' %(modSpecValue.attribsMap.get('modUnlimitedValue',0),))
				else:
					fout.write('\t\t\ttmpModSpec.moduleTrialLicense.TVal = 127;\n')
			fout.write('\t\t\ttmpModSpec.modulePoolModuleID.TVal = %s;\n' %(modSpecValue.attribsMap.get('modulePoolModuleID',0),))
			fout.write('\t\t\ttmpModSpec.moduleDefaultLicense.TVal = %s;\n' %(modSpecValue.attribsMap.get('moduleDefaultLicense',0),))
			fout.write('\t\t\ttmpModSpec.bModuleIsCounter.TVal = %s;\n' %(modSpecValue.attribsMap.get('bModuleIsCounter','false'),))
			fout.write('\t\t\ttmpModSpec.bModuleIsPool.TVal = %s;\n' %(modSpecValue.attribsMap.get('bModuleIsPool','false'),))
			fout.write('\t\t\ttmpModSpec.moduleVersionIntroduced_Major.TVal = %s;\n' %(modSpecValue.attribsMap.get('moduleVersionIntroduced_Major',0),))
			fout.write('\t\t\ttmpModSpec.moduleVersionIntroduced_Minor.TVal = %s;\n' %(modSpecValue.attribsMap.get('moduleVersionIntroduced_Minor',0),))
			fout.write('\t\t\ttmpModSpec.moduleVersionIntroduced_SubMajor.TVal = %s;\n' %(modSpecValue.attribsMap.get('moduleVersionIntroduced_SubMajor',0),))
			fout.write('\t\t\ttmpModSpec.moduleVersionIntroduced_SubMinor.TVal = %s;\n' %(modSpecValue.attribsMap.get('moduleVersionIntroduced_SubMinor',0),))
			fout.write('\t\t\ttmpModSpec.moduleVersionDeprecated_Major.TVal = %s;\n' %(modSpecValue.attribsMap.get('moduleVersionDeprecated_Major',0),))
			fout.write('\t\t\ttmpModSpec.moduleVersionDeprecated_Minor.TVal = %s;\n' %(modSpecValue.attribsMap.get('moduleVersionDeprecated_Minor',0),))
			fout.write('\t\t\ttmpModSpec.moduleVersionDeprecated_SubMajor.TVal = %s;\n' %(modSpecValue.attribsMap.get('moduleVersionDeprecated_SubMajor',0),))
			fout.write('\t\t\ttmpModSpec.moduleVersionDeprecated_SubMinor.TVal = %s;\n' %(modSpecValue.attribsMap.get('moduleVersionDeprecated_SubMinor',0),))
			fout.write('\t\t\ttmpProdSpec.moduleSpecMap.TVal.Add(tmpModSpec.moduleID.TVal, tmpModSpec);\n')
		fout.write('\t\t\t#endregion\n')
	fout.write('\t\t}\n')
	fout.write('\t\tprivate Solimar.Licensing.Attribs.Lic_PackageAttribs.Lic_SoftwareSpecAttribs m_softwareSpec = null;\n')
	fout.write('\t\tpublic Solimar.Licensing.Attribs.Lic_PackageAttribs.Lic_SoftwareSpecAttribs softwareSpec {get {return m_softwareSpec;}}\n')
	fout.write('\t};\n')
	fout.write('}\n')
	fout.close()
	
#def XMLProcessModuleFormat() :

	
##############################
# Parse the KeySpec.xml file #
##############################

print 'SoftwareSpecXMLCompiler.py - Start'

softwareSpec={'attribsMap':{}, 'productsMap':{}}

class moduleSpec:
	attribsMap = []

class productSpec:
	attribsMap = {}
	modulesMap = []


dom = xml.dom.minidom.parse('.\\SoftwareSpec.xml')
root = dom.documentElement

#########################################################
# create the data structure initialization include file #
#########################################################





#print "##############################"
#print root.nodeName
#print root

XMLProcessAttribs(root, softwareSpec['attribsMap'])

#print "##############################"
XMLProcessProductFormat(root, softwareSpec['productsMap'])
#print softwareSpec
ConvertSoftwareSpecToH(softwareSpec)
ConvertSoftwareSpecToCS(softwareSpec)

print 'SoftwareSpecXMLCompiler.py - Finished'
