//
//This file is generated by SoftwareSpecXMLCompiler.py

softwareSpec.softwareSpec_SubMajor = 0;
softwareSpec.softwareSpec_Major = 1;
softwareSpec.softwareSpec_SubMinor = 10;
softwareSpec.softwareSpec_Minor = 0;
InititalizeProduct120();
InititalizeProduct115();
InititalizeProduct114();
InititalizeProduct108();
InititalizeProduct109();
InititalizeProduct110();
InititalizeProduct113();
InititalizeProduct112();
InititalizeProduct20();
InititalizeProduct119();
InititalizeProduct107();
InititalizeProduct10();
InititalizeProduct13();
InititalizeProduct12();
InititalizeProduct15();
InititalizeProduct14();
InititalizeProduct17();
InititalizeProduct16();
InititalizeProduct19();
InititalizeProduct18();
InititalizeProduct117();
InititalizeProduct118();
InititalizeProduct116();
InititalizeProduct7();
InititalizeProduct9();
InititalizeProduct8();
