//
//This file is generated by SoftwareSpecXMLCompiler.py

void InititalizeProduct24()
{
	Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs* pTmpProdSpec;
	
	//
	// ProdID:24, ProdName: SOLsearcher Enterprise Single Plateform Test/Dev
	softwareSpec.productSpecMap->insert(Lic_PackageAttribs::Lic_SoftwareSpecAttribs::TMap_Lic_ProductSoftwareSpecAttribsMap::value_type(24, Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs()));
	pTmpProdSpec = &((softwareSpec.productSpecMap->find(24))->second);
	pTmpProdSpec->productID = 24;
	pTmpProdSpec->productName = std::wstring(L"SOLsearcher Enterprise Single Plateform Test/Dev");
	pTmpProdSpec->sameModSpecProductID = 8;
}

void InititalizeProduct25()
{
	Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs* pTmpProdSpec;
	
	//
	// ProdID:25, ProdName: SOLfusion Single Plateform Test/Dev
	softwareSpec.productSpecMap->insert(Lic_PackageAttribs::Lic_SoftwareSpecAttribs::TMap_Lic_ProductSoftwareSpecAttribsMap::value_type(25, Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs()));
	pTmpProdSpec = &((softwareSpec.productSpecMap->find(25))->second);
	pTmpProdSpec->productID = 25;
	pTmpProdSpec->productName = std::wstring(L"SOLfusion Single Plateform Test/Dev");
	pTmpProdSpec->sameModSpecProductID = 13;
}

void InititalizeProduct26()
{
	Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs* pTmpProdSpec;
	
	//
	// ProdID:26, ProdName: SDX Designer Test/Dev
	softwareSpec.productSpecMap->insert(Lic_PackageAttribs::Lic_SoftwareSpecAttribs::TMap_Lic_ProductSoftwareSpecAttribsMap::value_type(26, Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs()));
	pTmpProdSpec = &((softwareSpec.productSpecMap->find(26))->second);
	pTmpProdSpec->productID = 26;
	pTmpProdSpec->productName = std::wstring(L"SDX Designer Test/Dev");
	pTmpProdSpec->sameModSpecProductID = 17;
	pTmpProdSpec->productLicType = Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::pltClient;
}

void InititalizeProduct27()
{
	Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs* pTmpProdSpec;
	
	//
	// ProdID:27, ProdName: SPDE Queue Manager Test/Dev
	softwareSpec.productSpecMap->insert(Lic_PackageAttribs::Lic_SoftwareSpecAttribs::TMap_Lic_ProductSoftwareSpecAttribsMap::value_type(27, Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs()));
	pTmpProdSpec = &((softwareSpec.productSpecMap->find(27))->second);
	pTmpProdSpec->productID = 27;
	pTmpProdSpec->productName = std::wstring(L"SPDE Queue Manager Test/Dev");
	pTmpProdSpec->sameModSpecProductID = 18;
	pTmpProdSpec->productLicType = Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::pltClient;
}

void InititalizeProduct20()
{
	Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs* pTmpProdSpec;
	
	//
	// ProdID:20, ProdName: SOLsearcher Enterprise Test/Dev
	softwareSpec.productSpecMap->insert(Lic_PackageAttribs::Lic_SoftwareSpecAttribs::TMap_Lic_ProductSoftwareSpecAttribsMap::value_type(20, Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs()));
	pTmpProdSpec = &((softwareSpec.productSpecMap->find(20))->second);
	pTmpProdSpec->productID = 20;
	pTmpProdSpec->productName = std::wstring(L"SOLsearcher Enterprise Test/Dev");
	pTmpProdSpec->sameModSpecProductID = 8;
}

void InititalizeProduct21()
{
	Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs* pTmpProdSpec;
	
	//
	// ProdID:21, ProdName: SOLindexer Test/Dev
	softwareSpec.productSpecMap->insert(Lic_PackageAttribs::Lic_SoftwareSpecAttribs::TMap_Lic_ProductSoftwareSpecAttribsMap::value_type(21, Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs()));
	pTmpProdSpec = &((softwareSpec.productSpecMap->find(21))->second);
	pTmpProdSpec->productID = 21;
	pTmpProdSpec->productName = std::wstring(L"SOLindexer Test/Dev");
	pTmpProdSpec->sameModSpecProductID = 10;
}

void InititalizeProduct22()
{
	Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs* pTmpProdSpec;
	
	//
	// ProdID:22, ProdName: Rubika Test/Dev
	softwareSpec.productSpecMap->insert(Lic_PackageAttribs::Lic_SoftwareSpecAttribs::TMap_Lic_ProductSoftwareSpecAttribsMap::value_type(22, Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs()));
	pTmpProdSpec = &((softwareSpec.productSpecMap->find(22))->second);
	pTmpProdSpec->productID = 22;
	pTmpProdSpec->productName = std::wstring(L"Rubika Test/Dev");
	pTmpProdSpec->sameModSpecProductID = 12;
}

void InititalizeProduct23()
{
	Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs* pTmpProdSpec;
	
	//
	// ProdID:23, ProdName: SPDE Test/Dev
	softwareSpec.productSpecMap->insert(Lic_PackageAttribs::Lic_SoftwareSpecAttribs::TMap_Lic_ProductSoftwareSpecAttribsMap::value_type(23, Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs()));
	pTmpProdSpec = &((softwareSpec.productSpecMap->find(23))->second);
	pTmpProdSpec->productID = 23;
	pTmpProdSpec->productName = std::wstring(L"SPDE Test/Dev");
	pTmpProdSpec->sameModSpecProductID = 14;
}

void InititalizeProduct28()
{
	Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs* pTmpProdSpec;
	
	//
	// ProdID:28, ProdName: Rubika Process Builder Test/Dev
	softwareSpec.productSpecMap->insert(Lic_PackageAttribs::Lic_SoftwareSpecAttribs::TMap_Lic_ProductSoftwareSpecAttribsMap::value_type(28, Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs()));
	pTmpProdSpec = &((softwareSpec.productSpecMap->find(28))->second);
	pTmpProdSpec->productID = 28;
	pTmpProdSpec->productName = std::wstring(L"Rubika Process Builder Test/Dev");
	pTmpProdSpec->sameModSpecProductID = 16;
	pTmpProdSpec->productLicType = Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::pltClient;
}

void InititalizeProduct29()
{
	Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs* pTmpProdSpec;
	
	//
	// ProdID:29, ProdName: SOLscript Test/Dev
	softwareSpec.productSpecMap->insert(Lic_PackageAttribs::Lic_SoftwareSpecAttribs::TMap_Lic_ProductSoftwareSpecAttribsMap::value_type(29, Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs()));
	pTmpProdSpec = &((softwareSpec.productSpecMap->find(29))->second);
	pTmpProdSpec->productID = 29;
	pTmpProdSpec->productName = std::wstring(L"SOLscript Test/Dev");
	pTmpProdSpec->sameModSpecProductID = 9;
}

void InititalizeProduct7()
{
	Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs* pTmpProdSpec;
	
	//
	// ProdID:7, ProdName: iCONVERT
	softwareSpec.productSpecMap->insert(Lic_PackageAttribs::Lic_SoftwareSpecAttribs::TMap_Lic_ProductSoftwareSpecAttribsMap::value_type(7, Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs()));
	pTmpProdSpec = &((softwareSpec.productSpecMap->find(7))->second);
	pTmpProdSpec->productID = 7;
	pTmpProdSpec->productName = std::wstring(L"iCONVERT");

	Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs* pTmpModSpec;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(56, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(56))->second);
	pTmpModSpec->moduleID = 56;
	pTmpModSpec->moduleName = std::wstring(L"Emailer");
	pTmpModSpec->moduleTrialLicense = 127;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(43, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(43))->second);
	pTmpModSpec->moduleID = 43;
	pTmpModSpec->moduleName = std::wstring(L"IConvertType1");
	pTmpModSpec->moduleTrialLicense = 127;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(48, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(48))->second);
	pTmpModSpec->moduleID = 48;
	pTmpModSpec->moduleName = std::wstring(L"AFPEncryption");
	pTmpModSpec->moduleTrialLicense = 127;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(49, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(49))->second);
	pTmpModSpec->moduleID = 49;
	pTmpModSpec->moduleName = std::wstring(L"AFPURL");
	pTmpModSpec->moduleTrialLicense = 127;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(42, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(42))->second);
	pTmpModSpec->moduleID = 42;
	pTmpModSpec->moduleName = std::wstring(L"IConvertOverlay");
	pTmpModSpec->moduleTrialLicense = 127;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(29, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(29))->second);
	pTmpModSpec->moduleID = 29;
	pTmpModSpec->moduleName = std::wstring(L"AFP Job Event");
	pTmpModSpec->moduleTrialLicense = 127;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(40, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(40))->second);
	pTmpModSpec->moduleID = 40;
	pTmpModSpec->moduleName = std::wstring(L"IConvertEncryption");
	pTmpModSpec->moduleTrialLicense = 127;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(41, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(41))->second);
	pTmpModSpec->moduleID = 41;
	pTmpModSpec->moduleName = std::wstring(L"IConvertURL");
	pTmpModSpec->moduleTrialLicense = 127;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(1, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(1))->second);
	pTmpModSpec->moduleID = 1;
	pTmpModSpec->moduleName = std::wstring(L"LUA");
	pTmpModSpec->moduleTrialLicense = 127;
	pTmpModSpec->modulePoolModuleID = 128;
	pTmpModSpec->moduleDefaultLicense = 15;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(0, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(0))->second);
	pTmpModSpec->moduleID = 0;
	pTmpModSpec->moduleName = std::wstring(L"APPC");
	pTmpModSpec->moduleTrialLicense = 127;
	pTmpModSpec->modulePoolModuleID = 128;
	pTmpModSpec->moduleDefaultLicense = 15;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(2, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(2))->second);
	pTmpModSpec->moduleID = 2;
	pTmpModSpec->moduleName = std::wstring(L"TCP/IP");
	pTmpModSpec->moduleTrialLicense = 127;
	pTmpModSpec->modulePoolModuleID = 128;
	pTmpModSpec->moduleDefaultLicense = 15;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(9, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(9))->second);
	pTmpModSpec->moduleID = 9;
	pTmpModSpec->moduleName = std::wstring(L"IPDS::2dBarCodes");
	pTmpModSpec->moduleTrialLicense = 127;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(8, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(8))->second);
	pTmpModSpec->moduleID = 8;
	pTmpModSpec->moduleName = std::wstring(L"IConvert Job Event");
	pTmpModSpec->moduleTrialLicense = 127;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(128, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(128))->second);
	pTmpModSpec->moduleID = 128;
	pTmpModSpec->moduleName = std::wstring(L"Max LU");
	pTmpModSpec->moduleTrialLicense = 127;
	pTmpModSpec->bModuleIsPool = true;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(13, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(13))->second);
	pTmpModSpec->moduleID = 13;
	pTmpModSpec->moduleName = std::wstring(L"IPDS::PDF");
	pTmpModSpec->moduleTrialLicense = 127;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(12, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(12))->second);
	pTmpModSpec->moduleID = 12;
	pTmpModSpec->moduleName = std::wstring(L"IPDS::PCL");
	pTmpModSpec->moduleTrialLicense = 127;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(15, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(15))->second);
	pTmpModSpec->moduleID = 15;
	pTmpModSpec->moduleName = std::wstring(L"IPDS::TIFF");
	pTmpModSpec->moduleTrialLicense = 127;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(14, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(14))->second);
	pTmpModSpec->moduleID = 14;
	pTmpModSpec->moduleName = std::wstring(L"IPDS::PS");
	pTmpModSpec->moduleTrialLicense = 127;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(33, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(33))->second);
	pTmpModSpec->moduleID = 33;
	pTmpModSpec->moduleName = std::wstring(L"AFP::PDF");
	pTmpModSpec->moduleTrialLicense = 127;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(32, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(32))->second);
	pTmpModSpec->moduleID = 32;
	pTmpModSpec->moduleName = std::wstring(L"AFP::PCL");
	pTmpModSpec->moduleTrialLicense = 127;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(30, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(30))->second);
	pTmpModSpec->moduleID = 30;
	pTmpModSpec->moduleName = std::wstring(L"AFP::2dBarCodes");
	pTmpModSpec->moduleTrialLicense = 127;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(51, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(51))->second);
	pTmpModSpec->moduleID = 51;
	pTmpModSpec->moduleName = std::wstring(L"AFPType1");
	pTmpModSpec->moduleTrialLicense = 127;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(50, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(50))->second);
	pTmpModSpec->moduleID = 50;
	pTmpModSpec->moduleName = std::wstring(L"AFPOverlay");
	pTmpModSpec->moduleTrialLicense = 127;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(35, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(35))->second);
	pTmpModSpec->moduleID = 35;
	pTmpModSpec->moduleName = std::wstring(L"AFP::TIFF");
	pTmpModSpec->moduleTrialLicense = 127;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(34, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(34))->second);
	pTmpModSpec->moduleID = 34;
	pTmpModSpec->moduleName = std::wstring(L"AFP::PS");
	pTmpModSpec->moduleTrialLicense = 127;
}

void InititalizeProduct9()
{
	Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs* pTmpProdSpec;
	
	//
	// ProdID:9, ProdName: SOLscript
	softwareSpec.productSpecMap->insert(Lic_PackageAttribs::Lic_SoftwareSpecAttribs::TMap_Lic_ProductSoftwareSpecAttribsMap::value_type(9, Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs()));
	pTmpProdSpec = &((softwareSpec.productSpecMap->find(9))->second);
	pTmpProdSpec->productID = 9;
	pTmpProdSpec->productName = std::wstring(L"SOLscript");

	Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs* pTmpModSpec;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(25, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(25))->second);
	pTmpModSpec->moduleID = 25;
	pTmpModSpec->moduleName = std::wstring(L"PostScript::IPDS");
	pTmpModSpec->moduleTrialLicense = 127;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(12, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(12))->second);
	pTmpModSpec->moduleID = 12;
	pTmpModSpec->moduleName = std::wstring(L"PS::PS(Rip)");
	pTmpModSpec->moduleTrialLicense = 127;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(21, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(21))->second);
	pTmpModSpec->moduleID = 21;
	pTmpModSpec->moduleName = std::wstring(L"PostScript::Metacode");
	pTmpModSpec->moduleTrialLicense = 127;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(46, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(46))->second);
	pTmpModSpec->moduleID = 46;
	pTmpModSpec->moduleName = std::wstring(L"PostScript::TIFF");
	pTmpModSpec->moduleTrialLicense = 127;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(50, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(50))->second);
	pTmpModSpec->moduleID = 50;
	pTmpModSpec->moduleName = std::wstring(L"PostScript::AFPDS");
	pTmpModSpec->moduleTrialLicense = 127;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(53, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(53))->second);
	pTmpModSpec->moduleID = 53;
	pTmpModSpec->moduleName = std::wstring(L"PostScript::PostScript");
	pTmpModSpec->moduleTrialLicense = 127;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(52, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(52))->second);
	pTmpModSpec->moduleID = 52;
	pTmpModSpec->moduleName = std::wstring(L"PostScript::PDF");
	pTmpModSpec->moduleTrialLicense = 127;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(1, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(1))->second);
	pTmpModSpec->moduleID = 1;
	pTmpModSpec->moduleName = std::wstring(L"GhostScript");
	pTmpModSpec->moduleTrialLicense = 127;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(0, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(0))->second);
	pTmpModSpec->moduleID = 0;
	pTmpModSpec->moduleName = std::wstring(L"Distiller");
	pTmpModSpec->moduleTrialLicense = 127;
}

void InititalizeProduct8()
{
	Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs* pTmpProdSpec;
	
	//
	// ProdID:8, ProdName: SOLsearcher Enterprise
	softwareSpec.productSpecMap->insert(Lic_PackageAttribs::Lic_SoftwareSpecAttribs::TMap_Lic_ProductSoftwareSpecAttribsMap::value_type(8, Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs()));
	pTmpProdSpec = &((softwareSpec.productSpecMap->find(8))->second);
	pTmpProdSpec->productID = 8;
	pTmpProdSpec->productName = std::wstring(L"SOLsearcher Enterprise");

	Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs* pTmpModSpec;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(133, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(133))->second);
	pTmpModSpec->moduleID = 133;
	pTmpModSpec->moduleName = std::wstring(L"Full Text");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(132, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(132))->second);
	pTmpModSpec->moduleID = 132;
	pTmpModSpec->moduleName = std::wstring(L"PDF");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(131, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(131))->second);
	pTmpModSpec->moduleID = 131;
	pTmpModSpec->moduleName = std::wstring(L"Ascii");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(130, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(130))->second);
	pTmpModSpec->moduleID = 130;
	pTmpModSpec->moduleName = std::wstring(L"SSE Notes");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(1, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(1))->second);
	pTmpModSpec->moduleID = 1;
	pTmpModSpec->moduleName = std::wstring(L"Report Servers");
	pTmpModSpec->moduleTrialLicense = 127;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(0, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(0))->second);
	pTmpModSpec->moduleID = 0;
	pTmpModSpec->moduleName = std::wstring(L"Index Servers");
	pTmpModSpec->moduleTrialLicense = 127;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(3, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(3))->second);
	pTmpModSpec->moduleID = 3;
	pTmpModSpec->moduleName = std::wstring(L"Application Databases");
	pTmpModSpec->modUnlimitedValue = 255;
	pTmpModSpec->moduleTrialLicense = 255;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(2, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(2))->second);
	pTmpModSpec->moduleID = 2;
	pTmpModSpec->moduleName = std::wstring(L"Concurrent Users");
	pTmpModSpec->moduleTrialLicense = 127;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(5, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(5))->second);
	pTmpModSpec->moduleID = 5;
	pTmpModSpec->moduleName = std::wstring(L"Server");
	pTmpModSpec->moduleTrialLicense = 127;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(4, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(4))->second);
	pTmpModSpec->moduleID = 4;
	pTmpModSpec->moduleName = std::wstring(L"Document Assembler");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(7, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(7))->second);
	pTmpModSpec->moduleID = 7;
	pTmpModSpec->moduleName = std::wstring(L"Archive");
	pTmpModSpec->moduleTrialLicense = 127;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(6, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(6))->second);
	pTmpModSpec->moduleID = 6;
	pTmpModSpec->moduleName = std::wstring(L"CPU");
	pTmpModSpec->moduleTrialLicense = 127;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(128, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(128))->second);
	pTmpModSpec->moduleID = 128;
	pTmpModSpec->moduleName = std::wstring(L"SSE Full");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(129, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(129))->second);
	pTmpModSpec->moduleID = 129;
	pTmpModSpec->moduleName = std::wstring(L"Net Folders");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
}

void InititalizeProduct10()
{
	Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs* pTmpProdSpec;
	
	//
	// ProdID:10, ProdName: SOLindexer
	softwareSpec.productSpecMap->insert(Lic_PackageAttribs::Lic_SoftwareSpecAttribs::TMap_Lic_ProductSoftwareSpecAttribsMap::value_type(10, Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs()));
	pTmpProdSpec = &((softwareSpec.productSpecMap->find(10))->second);
	pTmpProdSpec->productID = 10;
	pTmpProdSpec->productName = std::wstring(L"SOLindexer");

	Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs* pTmpModSpec;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(1, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(1))->second);
	pTmpModSpec->moduleID = 1;
	pTmpModSpec->moduleName = std::wstring(L"SOLmonitor");
	pTmpModSpec->moduleTrialLicense = 127;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(0, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(0))->second);
	pTmpModSpec->moduleID = 0;
	pTmpModSpec->moduleName = std::wstring(L"SDX Designer");
	pTmpModSpec->moduleTrialLicense = 127;
}

void InititalizeProduct13()
{
	Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs* pTmpProdSpec;
	
	//
	// ProdID:13, ProdName: SOLfusion
	softwareSpec.productSpecMap->insert(Lic_PackageAttribs::Lic_SoftwareSpecAttribs::TMap_Lic_ProductSoftwareSpecAttribsMap::value_type(13, Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs()));
	pTmpProdSpec = &((softwareSpec.productSpecMap->find(13))->second);
	pTmpProdSpec->productID = 13;
	pTmpProdSpec->productName = std::wstring(L"SOLfusion");

	Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs* pTmpModSpec;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(0, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(0))->second);
	pTmpModSpec->moduleID = 0;
	pTmpModSpec->moduleName = std::wstring(L"SOLfusion");
	pTmpModSpec->moduleTrialLicense = 127;
}

void InititalizeProduct12()
{
	Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs* pTmpProdSpec;
	
	//
	// ProdID:12, ProdName: Rubika
	softwareSpec.productSpecMap->insert(Lic_PackageAttribs::Lic_SoftwareSpecAttribs::TMap_Lic_ProductSoftwareSpecAttribsMap::value_type(12, Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs()));
	pTmpProdSpec = &((softwareSpec.productSpecMap->find(12))->second);
	pTmpProdSpec->productID = 12;
	pTmpProdSpec->productName = std::wstring(L"Rubika");

	Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs* pTmpModSpec;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(20, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(20))->second);
	pTmpModSpec->moduleID = 20;
	pTmpModSpec->moduleName = std::wstring(L"Cleanse/Sort Counter");
	pTmpModSpec->moduleTrialLicense = 127;
	pTmpModSpec->moduleDefaultLicense = 0;
	pTmpModSpec->bModuleIsCounter = true;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(21, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(21))->second);
	pTmpModSpec->moduleID = 21;
	pTmpModSpec->moduleName = std::wstring(L"Merge Counter");
	pTmpModSpec->moduleTrialLicense = 127;
	pTmpModSpec->moduleDefaultLicense = 0;
	pTmpModSpec->bModuleIsCounter = true;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(1, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(1))->second);
	pTmpModSpec->moduleID = 1;
	pTmpModSpec->moduleName = std::wstring(L"Cleanse & Sort");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(0, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(0))->second);
	pTmpModSpec->moduleID = 0;
	pTmpModSpec->moduleName = std::wstring(L"Merge");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(3, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(3))->second);
	pTmpModSpec->moduleID = 3;
	pTmpModSpec->moduleName = std::wstring(L"Finishing");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(2, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(2))->second);
	pTmpModSpec->moduleID = 2;
	pTmpModSpec->moduleName = std::wstring(L"Split");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(5, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(5))->second);
	pTmpModSpec->moduleID = 5;
	pTmpModSpec->moduleName = std::wstring(L"Imposition");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(4, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(4))->second);
	pTmpModSpec->moduleID = 4;
	pTmpModSpec->moduleName = std::wstring(L"Concatentate");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(7, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(7))->second);
	pTmpModSpec->moduleID = 7;
	pTmpModSpec->moduleName = std::wstring(L"Insert");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(6, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(6))->second);
	pTmpModSpec->moduleID = 6;
	pTmpModSpec->moduleName = std::wstring(L"Underlay");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(9, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(9))->second);
	pTmpModSpec->moduleID = 9;
	pTmpModSpec->moduleName = std::wstring(L"Archive Assistant");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(8, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(8))->second);
	pTmpModSpec->moduleID = 8;
	pTmpModSpec->moduleName = std::wstring(L"Segment");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(11, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(11))->second);
	pTmpModSpec->moduleID = 11;
	pTmpModSpec->moduleName = std::wstring(L"Barcode - ***Deprecated***");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	pTmpModSpec->moduleVersionDeprecated_Major = 2;
	pTmpModSpec->moduleVersionDeprecated_Minor = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(10, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(10))->second);
	pTmpModSpec->moduleID = 10;
	pTmpModSpec->moduleName = std::wstring(L"Mark");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(13, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(13))->second);
	pTmpModSpec->moduleID = 13;
	pTmpModSpec->moduleName = std::wstring(L"Delete");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(12, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(12))->second);
	pTmpModSpec->moduleID = 12;
	pTmpModSpec->moduleName = std::wstring(L"Text Marking - ***Deprecated***");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	pTmpModSpec->moduleVersionDeprecated_Major = 2;
	pTmpModSpec->moduleVersionDeprecated_Minor = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(15, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(15))->second);
	pTmpModSpec->moduleID = 15;
	pTmpModSpec->moduleName = std::wstring(L"Export / Import");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(14, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(14))->second);
	pTmpModSpec->moduleID = 14;
	pTmpModSpec->moduleName = std::wstring(L"Replace");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(17, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(17))->second);
	pTmpModSpec->moduleID = 17;
	pTmpModSpec->moduleName = std::wstring(L"Book Blocks");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(16, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(16))->second);
	pTmpModSpec->moduleID = 16;
	pTmpModSpec->moduleName = std::wstring(L"N-to-1");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(19, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(19))->second);
	pTmpModSpec->moduleID = 19;
	pTmpModSpec->moduleName = std::wstring(L"Scale & Translate");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(18, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(18))->second);
	pTmpModSpec->moduleID = 18;
	pTmpModSpec->moduleName = std::wstring(L"2-Up");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(31, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(31))->second);
	pTmpModSpec->moduleID = 31;
	pTmpModSpec->moduleName = std::wstring(L"Process Builders");
	pTmpModSpec->moduleTrialLicense = 127;
	pTmpModSpec->moduleDefaultLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(30, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(30))->second);
	pTmpModSpec->moduleID = 30;
	pTmpModSpec->moduleName = std::wstring(L"Instances");
	pTmpModSpec->moduleTrialLicense = 127;
	pTmpModSpec->moduleDefaultLicense = 1;
}

void InititalizeProduct15()
{
	Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs* pTmpProdSpec;
	
	//
	// ProdID:15, ProdName: SOLsearcher Enterprise Single Plateform
	softwareSpec.productSpecMap->insert(Lic_PackageAttribs::Lic_SoftwareSpecAttribs::TMap_Lic_ProductSoftwareSpecAttribsMap::value_type(15, Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs()));
	pTmpProdSpec = &((softwareSpec.productSpecMap->find(15))->second);
	pTmpProdSpec->productID = 15;
	pTmpProdSpec->productName = std::wstring(L"SOLsearcher Enterprise Single Plateform");
	pTmpProdSpec->sameModSpecProductID = 8;
}

void InititalizeProduct14()
{
	Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs* pTmpProdSpec;
	
	//
	// ProdID:14, ProdName: SPDE
	softwareSpec.productSpecMap->insert(Lic_PackageAttribs::Lic_SoftwareSpecAttribs::TMap_Lic_ProductSoftwareSpecAttribsMap::value_type(14, Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs()));
	pTmpProdSpec = &((softwareSpec.productSpecMap->find(14))->second);
	pTmpProdSpec->productID = 14;
	pTmpProdSpec->productName = std::wstring(L"SPDE");

	Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs* pTmpModSpec;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(42, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(42))->second);
	pTmpModSpec->moduleID = 42;
	pTmpModSpec->moduleName = std::wstring(L"RJE::3211");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(48, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(48))->second);
	pTmpModSpec->moduleID = 48;
	pTmpModSpec->moduleName = std::wstring(L"PDF::PostScript(PDFL-RIP)");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(43, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(43))->second);
	pTmpModSpec->moduleID = 43;
	pTmpModSpec->moduleName = std::wstring(L"AFPDS::IPDS");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(49, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(49))->second);
	pTmpModSpec->moduleID = 49;
	pTmpModSpec->moduleName = std::wstring(L"PDF::AFPDS");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(24, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(24))->second);
	pTmpModSpec->moduleID = 24;
	pTmpModSpec->moduleName = std::wstring(L"PostScript::Postscript (RIP)");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(25, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(25))->second);
	pTmpModSpec->moduleID = 25;
	pTmpModSpec->moduleName = std::wstring(L"PostScript::TIFF");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(26, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(26))->second);
	pTmpModSpec->moduleID = 26;
	pTmpModSpec->moduleName = std::wstring(L"SCS::3211");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(27, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(27))->second);
	pTmpModSpec->moduleID = 27;
	pTmpModSpec->moduleName = std::wstring(L"SCS::Metacode");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(20, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(20))->second);
	pTmpModSpec->moduleID = 20;
	pTmpModSpec->moduleName = std::wstring(L"PostScript::IPDS");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(21, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(21))->second);
	pTmpModSpec->moduleID = 21;
	pTmpModSpec->moduleName = std::wstring(L"PostScript::Metacode");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(22, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(22))->second);
	pTmpModSpec->moduleID = 22;
	pTmpModSpec->moduleName = std::wstring(L"PostScript::PDF");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(23, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(23))->second);
	pTmpModSpec->moduleID = 23;
	pTmpModSpec->moduleName = std::wstring(L"PostScript::Postscript");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(46, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(46))->second);
	pTmpModSpec->moduleID = 46;
	pTmpModSpec->moduleName = std::wstring(L"PDF::TIFF(PDFL)");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(47, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(47))->second);
	pTmpModSpec->moduleID = 47;
	pTmpModSpec->moduleName = std::wstring(L"PDF::AFPDS(PDFL)");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(44, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(44))->second);
	pTmpModSpec->moduleID = 44;
	pTmpModSpec->moduleName = std::wstring(L"PDF::Postscript(PDFL)");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(45, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(45))->second);
	pTmpModSpec->moduleID = 45;
	pTmpModSpec->moduleName = std::wstring(L"PDF::IPDS(PDFL)");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(28, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(28))->second);
	pTmpModSpec->moduleID = 28;
	pTmpModSpec->moduleName = std::wstring(L"SMART");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(29, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(29))->second);
	pTmpModSpec->moduleID = 29;
	pTmpModSpec->moduleName = std::wstring(L"Tape Input");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(40, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(40))->second);
	pTmpModSpec->moduleID = 40;
	pTmpModSpec->moduleName = std::wstring(L"XRocks Printer Controller");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	pTmpModSpec->moduleDefaultLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(41, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(41))->second);
	pTmpModSpec->moduleID = 41;
	pTmpModSpec->moduleName = std::wstring(L"IPDS Print Controller");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(1, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(1))->second);
	pTmpModSpec->moduleID = 1;
	pTmpModSpec->moduleName = std::wstring(L"AFPDS::PDF");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(0, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(0))->second);
	pTmpModSpec->moduleID = 0;
	pTmpModSpec->moduleName = std::wstring(L"3211::ASCII");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	pTmpModSpec->moduleDefaultLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(3, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(3))->second);
	pTmpModSpec->moduleID = 3;
	pTmpModSpec->moduleName = std::wstring(L"ASCII::3211");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	pTmpModSpec->moduleDefaultLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(2, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(2))->second);
	pTmpModSpec->moduleID = 2;
	pTmpModSpec->moduleName = std::wstring(L"AFPDS::PS");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(5, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(5))->second);
	pTmpModSpec->moduleID = 5;
	pTmpModSpec->moduleName = std::wstring(L"Data Converter");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	pTmpModSpec->moduleDefaultLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(4, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(4))->second);
	pTmpModSpec->moduleID = 4;
	pTmpModSpec->moduleName = std::wstring(L"Blocker");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	pTmpModSpec->moduleDefaultLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(7, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(7))->second);
	pTmpModSpec->moduleID = 7;
	pTmpModSpec->moduleName = std::wstring(L"File Inserter");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	pTmpModSpec->moduleDefaultLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(6, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(6))->second);
	pTmpModSpec->moduleID = 6;
	pTmpModSpec->moduleName = std::wstring(L"Disk Spooler");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	pTmpModSpec->moduleDefaultLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(9, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(9))->second);
	pTmpModSpec->moduleID = 9;
	pTmpModSpec->moduleName = std::wstring(L"FTP Queuer");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(8, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(8))->second);
	pTmpModSpec->moduleID = 8;
	pTmpModSpec->moduleName = std::wstring(L"File Queuer");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	pTmpModSpec->moduleDefaultLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(201, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(201))->second);
	pTmpModSpec->moduleID = 201;
	pTmpModSpec->moduleName = std::wstring(L"TCP IP Output Dynamic Host Selection");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(200, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(200))->second);
	pTmpModSpec->moduleID = 200;
	pTmpModSpec->moduleName = std::wstring(L"PS Interpreter");
	pTmpModSpec->moduleTrialLicense = 127;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(202, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(202))->second);
	pTmpModSpec->moduleID = 202;
	pTmpModSpec->moduleName = std::wstring(L"PS(PDFL) Interpreter");
	pTmpModSpec->moduleTrialLicense = 127;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(401, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(401))->second);
	pTmpModSpec->moduleID = 401;
	pTmpModSpec->moduleName = std::wstring(L"Named User Sessions");
	pTmpModSpec->modUnlimitedValue = 255;
	pTmpModSpec->moduleTrialLicense = 255;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(400, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(400))->second);
	pTmpModSpec->moduleID = 400;
	pTmpModSpec->moduleName = std::wstring(L"Concurrent Operator Sessions");
	pTmpModSpec->modUnlimitedValue = 255;
	pTmpModSpec->moduleTrialLicense = 255;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(300, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(300))->second);
	pTmpModSpec->moduleID = 300;
	pTmpModSpec->moduleName = std::wstring(L"Pages Per Minute Extensions");
	pTmpModSpec->moduleTrialLicense = 127;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(301, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(301))->second);
	pTmpModSpec->moduleID = 301;
	pTmpModSpec->moduleName = std::wstring(L"AFPDS::PS PPM");
	pTmpModSpec->modUnlimitedValue = 500;
	pTmpModSpec->moduleTrialLicense = 500;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(302, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(302))->second);
	pTmpModSpec->moduleID = 302;
	pTmpModSpec->moduleName = std::wstring(L"XCHANGE::IPDS PPM");
	pTmpModSpec->modUnlimitedValue = 500;
	pTmpModSpec->moduleTrialLicense = 500;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(303, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(303))->second);
	pTmpModSpec->moduleID = 303;
	pTmpModSpec->moduleName = std::wstring(L"XCHANGE::PCL PPM");
	pTmpModSpec->modUnlimitedValue = 500;
	pTmpModSpec->moduleTrialLicense = 500;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(304, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(304))->second);
	pTmpModSpec->moduleID = 304;
	pTmpModSpec->moduleName = std::wstring(L"XCHANGE::PS PPM");
	pTmpModSpec->modUnlimitedValue = 500;
	pTmpModSpec->moduleTrialLicense = 500;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(39, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(39))->second);
	pTmpModSpec->moduleID = 39;
	pTmpModSpec->moduleName = std::wstring(L"XCHANGE::PS (DBCS)");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(305, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(305))->second);
	pTmpModSpec->moduleID = 305;
	pTmpModSpec->moduleName = std::wstring(L"XCHANGE::PS (DBCS) PPM");
	pTmpModSpec->modUnlimitedValue = 500;
	pTmpModSpec->moduleTrialLicense = 500;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(38, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(38))->second);
	pTmpModSpec->moduleID = 38;
	pTmpModSpec->moduleName = std::wstring(L"XCHANGE::PS");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(240, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(240))->second);
	pTmpModSpec->moduleID = 240;
	pTmpModSpec->moduleName = std::wstring(L"Output Pool");
	pTmpModSpec->modUnlimitedValue = 10;
	pTmpModSpec->moduleTrialLicense = 10;
	pTmpModSpec->bModuleIsPool = true;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(102, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(102))->second);
	pTmpModSpec->moduleID = 102;
	pTmpModSpec->moduleName = std::wstring(L"Bus/Tag Output (PCI)");
	pTmpModSpec->moduleTrialLicense = 127;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(103, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(103))->second);
	pTmpModSpec->moduleID = 103;
	pTmpModSpec->moduleName = std::wstring(L"Parallel Input");
	pTmpModSpec->moduleTrialLicense = 127;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(101, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(101))->second);
	pTmpModSpec->moduleID = 101;
	pTmpModSpec->moduleName = std::wstring(L"Bus/Tag Input (polaris)");
	pTmpModSpec->moduleTrialLicense = 127;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(104, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(104))->second);
	pTmpModSpec->moduleID = 104;
	pTmpModSpec->moduleName = std::wstring(L"Parallel Output");
	pTmpModSpec->moduleTrialLicense = 127;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(105, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(105))->second);
	pTmpModSpec->moduleID = 105;
	pTmpModSpec->moduleName = std::wstring(L"SCSI SDI Output");
	pTmpModSpec->moduleTrialLicense = 127;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(11, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(11))->second);
	pTmpModSpec->moduleID = 11;
	pTmpModSpec->moduleName = std::wstring(L"Job Separator");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	pTmpModSpec->moduleDefaultLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(10, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(10))->second);
	pTmpModSpec->moduleID = 10;
	pTmpModSpec->moduleName = std::wstring(L"IPDS Output");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	pTmpModSpec->moduleVersionDeprecated_Major = 6;
	pTmpModSpec->moduleVersionDeprecated_Minor = 0;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(13, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(13))->second);
	pTmpModSpec->moduleID = 13;
	pTmpModSpec->moduleName = std::wstring(L"Output Selector");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	pTmpModSpec->moduleDefaultLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(12, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(12))->second);
	pTmpModSpec->moduleID = 12;
	pTmpModSpec->moduleName = std::wstring(L"Line Data::AFPD");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(15, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(15))->second);
	pTmpModSpec->moduleID = 15;
	pTmpModSpec->moduleName = std::wstring(L"PDF::IPDS");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(14, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(14))->second);
	pTmpModSpec->moduleID = 14;
	pTmpModSpec->moduleName = std::wstring(L"PCL::Metacode");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(17, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(17))->second);
	pTmpModSpec->moduleID = 17;
	pTmpModSpec->moduleName = std::wstring(L"PDF::PostScript");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(16, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(16))->second);
	pTmpModSpec->moduleID = 16;
	pTmpModSpec->moduleName = std::wstring(L"PDF::Metacode");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(19, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(19))->second);
	pTmpModSpec->moduleID = 19;
	pTmpModSpec->moduleName = std::wstring(L"PDF::TIFF");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(18, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(18))->second);
	pTmpModSpec->moduleID = 18;
	pTmpModSpec->moduleName = std::wstring(L"PDF::PostScript (Rip)");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(31, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(31))->second);
	pTmpModSpec->moduleID = 31;
	pTmpModSpec->moduleName = std::wstring(L"TCP/IP lpd Output");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(30, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(30))->second);
	pTmpModSpec->moduleID = 30;
	pTmpModSpec->moduleName = std::wstring(L"TCP/IP lpr Input");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(37, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(37))->second);
	pTmpModSpec->moduleID = 37;
	pTmpModSpec->moduleName = std::wstring(L"XCHANGE::PDF");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(36, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(36))->second);
	pTmpModSpec->moduleID = 36;
	pTmpModSpec->moduleName = std::wstring(L"XCHANGE::PCL");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(35, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(35))->second);
	pTmpModSpec->moduleID = 35;
	pTmpModSpec->moduleName = std::wstring(L"XCHANGE::Metacode");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(34, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(34))->second);
	pTmpModSpec->moduleID = 34;
	pTmpModSpec->moduleName = std::wstring(L"XCHANGE::IPDS");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(33, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(33))->second);
	pTmpModSpec->moduleID = 33;
	pTmpModSpec->moduleName = std::wstring(L"Windows Printer Spooler");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(32, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(32))->second);
	pTmpModSpec->moduleID = 32;
	pTmpModSpec->moduleName = std::wstring(L"Trash Can");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
	pTmpModSpec->moduleDefaultLicense = 1;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(50, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(50))->second);
	pTmpModSpec->moduleID = 50;
	pTmpModSpec->moduleName = std::wstring(L"PostScript::AFPDS");
	pTmpModSpec->modUnlimitedValue = 1;
	pTmpModSpec->moduleTrialLicense = 1;
}

void InititalizeProduct17()
{
	Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs* pTmpProdSpec;
	
	//
	// ProdID:17, ProdName: SDX Designer
	softwareSpec.productSpecMap->insert(Lic_PackageAttribs::Lic_SoftwareSpecAttribs::TMap_Lic_ProductSoftwareSpecAttribsMap::value_type(17, Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs()));
	pTmpProdSpec = &((softwareSpec.productSpecMap->find(17))->second);
	pTmpProdSpec->productID = 17;
	pTmpProdSpec->productName = std::wstring(L"SDX Designer");
	pTmpProdSpec->prevSharedProductID = 10;
	pTmpProdSpec->productLicType = Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::pltClient;

	Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs* pTmpModSpec;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(0, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(0))->second);
	pTmpModSpec->moduleID = 0;
	pTmpModSpec->moduleName = std::wstring(L"SDX Designer");
	pTmpModSpec->moduleTrialLicense = 127;
}

void InititalizeProduct16()
{
	Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs* pTmpProdSpec;
	
	//
	// ProdID:16, ProdName: Rubika Process Builder
	softwareSpec.productSpecMap->insert(Lic_PackageAttribs::Lic_SoftwareSpecAttribs::TMap_Lic_ProductSoftwareSpecAttribsMap::value_type(16, Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs()));
	pTmpProdSpec = &((softwareSpec.productSpecMap->find(16))->second);
	pTmpProdSpec->productID = 16;
	pTmpProdSpec->productName = std::wstring(L"Rubika Process Builder");
	pTmpProdSpec->prevSharedProductID = 12;
	pTmpProdSpec->productLicType = Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::pltClient;

	Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs* pTmpModSpec;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(31, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(31))->second);
	pTmpModSpec->moduleID = 31;
	pTmpModSpec->moduleName = std::wstring(L"Process Builders");
	pTmpModSpec->moduleTrialLicense = 127;
}

void InititalizeProduct19()
{
	Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs* pTmpProdSpec;
	
	//
	// ProdID:19, ProdName: iCONVERT Test/Dev
	softwareSpec.productSpecMap->insert(Lic_PackageAttribs::Lic_SoftwareSpecAttribs::TMap_Lic_ProductSoftwareSpecAttribsMap::value_type(19, Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs()));
	pTmpProdSpec = &((softwareSpec.productSpecMap->find(19))->second);
	pTmpProdSpec->productID = 19;
	pTmpProdSpec->productName = std::wstring(L"iCONVERT Test/Dev");
	pTmpProdSpec->sameModSpecProductID = 7;
}

void InititalizeProduct18()
{
	Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs* pTmpProdSpec;
	
	//
	// ProdID:18, ProdName: SPDE Queue Manager
	softwareSpec.productSpecMap->insert(Lic_PackageAttribs::Lic_SoftwareSpecAttribs::TMap_Lic_ProductSoftwareSpecAttribsMap::value_type(18, Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs()));
	pTmpProdSpec = &((softwareSpec.productSpecMap->find(18))->second);
	pTmpProdSpec->productID = 18;
	pTmpProdSpec->productName = std::wstring(L"SPDE Queue Manager");
	pTmpProdSpec->prevSharedProductID = 14;
	pTmpProdSpec->productLicType = Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::pltClient;

	Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs* pTmpModSpec;
	
	pTmpProdSpec->moduleSpecMap->insert(Lic_PackageAttribs::Lic_ProductSoftwareSpecAttribs::TMap_Lic_ModuleSoftwareSpecAttribsMap::value_type(400, Lic_PackageAttribs::Lic_ModuleSoftwareSpecAttribs()));
	pTmpModSpec = &((pTmpProdSpec->moduleSpecMap->find(400))->second);
	pTmpModSpec->moduleID = 400;
	pTmpModSpec->moduleName = std::wstring(L"Concurrent Operator Sessions");
	pTmpModSpec->modUnlimitedValue = 255;
	pTmpModSpec->moduleTrialLicense = 255;
}

