//
// L_CAliasableResourceString.h : 
//
#pragma once
#ifndef _CAliasableResourceString_h																	// CR.33897; added.
#define _CAliasableResourceString_h																	// CR.33897; added.

#ifndef STRICT
#define STRICT
#endif
#include <windows.h>
#include <string>
#include "L_AliasedResourceIf.h"                                                    // CR.15891.V03; added.
#include "L_SpdStreamable4.h"

using namespace SpdStreamable ;

/*
 * class CResourceStringIF
 *
 * This class is used as a base class for CAliasableResourceStringBase. It is needed so base class attribs classes
 * can query AliasableResourceString objects for basic info.
 *
 * SLB 29.mar.2013 CR.15891.V03; added this comment header.
 * SLB 04.apr.2013 CR.15891.V04; Added support for more Alias types.
 * SLB 08.apr.2013 CR.15891.V04; Synched up TResourceType with the enum generated by
 * the attribs compiler CSpdAliasResourceAttribs::TAliasResourceType. 
 * SLB 17.apr.2013 CR.15891.V04; Added new fields and corresponding access methods for 
 * resource handling (e.g. package file handling, runtime access requirements, etc.).
 */
class CResourceStringIF
{
public:
   //
   // Note: this enum type must be kept in sync with CSpdAliasResourceAttribs::TAliasResourceType
   // which is generated by the attribs compiler.
   //
   typedef enum TResourceType
   {
      rtPlaceHolder=0,
      rtFolderName=1,
      rtFileName=2,
      rtPclMetaDriver=3,
      rtPclMetaMedia=4,
      rtPclMetaOutput=5,
      rtAfpdsSharedResource=6,                                                      // CR.15891.V04; added.
      rtRje3211Fcb=7,
      rtMachineName=8,                                                              // CR.15891.V04; added.
      rtDbsCheckpoint=9,                                                            // CR.15891.V04; added.
      rtDbsMonitor=10,                                                              // CR.15891.V04; added.
      rtNotAResource=-1,                                                            // CR.15891.V04; modified.
   } ;
   //
   // SLB 15.apr.2013 CR.15891.V04; added TPackageOptionsDesired.
   //
   typedef enum TPackageOptionsDesired
   {
      podNoSetting =             0x0000,
      podEnabled =               0x0001,     // Package File enabled 
	   podManageContents =        0x0002,     // Manage contents of resource (context specific: e.g. manage files if the resource is a folder)
      podManageSubFolders =      0x0004,     // Manages sub-folders as well. If podManageContents is included, subfolder contents are also managed.
      podIsShadow =              0x0008,     // Shadowed Resource
      podManageSubStreams =      0x0010      // Manages sub-streams of files 
   } ;
   //
   // SLB 15.apr.2013 CR.15891.V04; added TValidationOptions.
   //
   typedef enum TValidationOptions
   {
      voNoSetting =              0x0000,
      voMustExist =              0x0001,     // Resource must exist.
      voPermReqRead =            0x0002,     // attribute requires read access to the resource.
      voPermReqWrite =           0x0004,     // attribute requires write access to the resource.
      voPermReqCreateObjects =   0x0008,     // attribute requires the ability to create objects within the resource (e.g. files if resource is a folder).
      voPermReqDeleteObject =    0x0010,     // attribute requires the ability to delete objects within the resource.
      voPermReqCreateNode =      0x0020,     // attribute requires the ability to create a child node within the resource (e.g. a subfolder if resource is a folder)
      voPermReqDeleteNode =      0x0040,     // attribute requires the ability to delete a child node within the resource.
      //
      // Some combined settings for ease in definition.
      //
      voWRITE_CREAT_ALL =        0x002F,
      voDELETE_ALL =             0x0053,
      voALL =                    0xFFFF,
   } ;
   //
   // SLB 15.apr.2013 CR.15891.V04; added TRuntimeOptions.
   // SLB 01.may.2013 CR.15891.V06; added new enum: roSharingDisabled
   //
   typedef enum TRuntimeOptions
   {
      roNoSetting =              0x0000,
      roShareResourceRead =      0x0001,     // This means that the attribute allows others read access to its resource.
      roShareResourceWrite =     0x0002,     // This means that the attribute allows others write access to its resource.
      roShareCreateObjects =     0x0004,     // This means that the attribute allows others Create access to its resource.
      roShareDeleteObjects =     0x0008,     // This means that the attribute allows others Delete access to its resource.
      roShareCreateNodes =       0x0010,     // This means that the attribute allows others to create child nodes within its resource (e.g. a subfolder)
      roShareDeleteNodes =       0x0020,     // This means that the attribute allows others to delete child nodes within its resource (e.g. a subfolder)
      roEncryptedResource =      0x0040,     // This means that the attribute specifies that the resource will be/must be encrypted.
      roSharingDisabled =        0x0080,
      //
      // Some combined settings 
      //
      roShareAll =               0x003F,     // This means that the attribute allows others full access while it is accessing the resource.
   } ;

public:
   virtual bool IsResourceAnAlias() const = 0 ;
   virtual TResourceType GetResourceType() const = 0 ;
   virtual CSpdCString GetAliasResourceName() const = 0 ;
   virtual void SetAliasResourceName(                                               // CR.17482; added.
      const CSpdCString &wsNewName) = 0;
   virtual CSpdCString GetResourceName() const = 0 ;
   virtual TPackageOptionsDesired GetPackageOptionsDesired() const = 0 ;            // CR.15891.V04; added.
   virtual TValidationOptions GetValidationOptions() const = 0 ;                    // CR.15891.V04; added.
   virtual TRuntimeOptions GetRuntimeOptions() const = 0 ;                          // CR.15891.V04; added.
   virtual void SetPackageOptionsDesired(TPackageOptionsDesired pod) = 0 ;          // CR.15891.V04; added.
   virtual void SetValidationOptions(TValidationOptions vo) = 0 ;                   // CR.15891.V04; added.
   virtual void SetRuntimeOptions(TRuntimeOptions ro) = 0 ;                         // CR.15891.V04; added.
} ;


/*
 * class CAliasableResourceStringBase
 *
 * SLB 12.jul.2012 CR.15891.V02; Created. Also, removed operator std::wstring() ;
 * SLB 29.mar.2013 CR.15891.V03; Added GetResourceName().  
 * SLB 15.apr.2013 CR.15891.V04; Added new members to track options
 * SLB 17.jul.2019 CR.17482; Implemented new SetResourceName() method so that it is available for 
 * all aliasable resource classes.
 */
class CAliasableResourceStringBase : 
   public CResourceStringIF
{
public:
   TResourceType m_rtType ;
   CSpdCString m_wsFullResourceName ;
   TPackageOptionsDesired m_podResPackageOptions ;                                  // CR.15891.V04; added.
   TValidationOptions m_voResValidationOptions ;                                    // CR.15891.V04; added.
   TRuntimeOptions m_roResRuntimeOptions ;                                          // CR.15891.V04; added.

public:
   CAliasableResourceStringBase() :
      m_rtType(rtPlaceHolder),                                                      // CR.15891.V04; moved.
      m_podResPackageOptions(podEnabled),                                           // CR.15891.V04; added.
      m_voResValidationOptions((TValidationOptions)(voMustExist|voPermReqWrite)),   // CR.15891.V04; added.
      m_roResRuntimeOptions(roNoSetting)                                            // CR.15891.V04; added.
   {
   }
   
   CAliasableResourceStringBase(const CAliasableResourceStringBase &c) :
      m_wsFullResourceName(c.m_wsFullResourceName),
      m_rtType(c.m_rtType),
      m_podResPackageOptions(c.m_podResPackageOptions),                             // CR.15891.V04; added.
      m_voResValidationOptions(c.m_voResValidationOptions),                         // CR.15891.V04; added.
      m_roResRuntimeOptions(c.m_roResRuntimeOptions)                                // CR.15891.V04; added.
   {
   }

   CAliasableResourceStringBase(const CSpdCString &wsResourceName) :
      m_wsFullResourceName(wsResourceName),
      m_rtType(rtPlaceHolder),
      m_podResPackageOptions(podEnabled),                                           // CR.15891.V04; added.
      m_voResValidationOptions((TValidationOptions)(voMustExist|voPermReqWrite)),   // CR.15891.V04; added.
      m_roResRuntimeOptions(roNoSetting)                                            // CR.15891.V04; added.
   {
   }

   CAliasableResourceStringBase &operator = (const CAliasableResourceStringBase &c)
   {
      m_rtType = c.m_rtType ;
      m_wsFullResourceName = c.m_wsFullResourceName ;
      m_podResPackageOptions = c.m_podResPackageOptions ;                           // CR.15891.V04; added.
      m_voResValidationOptions = c.m_voResValidationOptions ;                       // CR.15891.V04; added.
      m_roResRuntimeOptions = c.m_roResRuntimeOptions ;                             // CR.15891.V04; added.
      return *this ;
   }


   const wchar_t *C_str() const { return m_wsFullResourceName.c_str() ; }
   void Clear() { m_wsFullResourceName.clear() ; }
   bool IsEmpty() const { return m_wsFullResourceName.empty() ; }
   size_t Size() const { return m_wsFullResourceName.size() ; }

   CAliasableResourceStringBase &operator = (const CSpdCString &ws)   
   {
      m_wsFullResourceName = ws ;
      return *this ;
   }

   bool operator != (const CAliasableResourceStringBase &c) const
   {
      return !(m_wsFullResourceName==c.m_wsFullResourceName) ;
   }

   bool operator == (const CAliasableResourceStringBase &c) const
   {
      return (m_wsFullResourceName==c.m_wsFullResourceName) ;
   }

   bool operator < (const CAliasableResourceStringBase &c) const
   {
      return (m_wsFullResourceName < c.m_wsFullResourceName) ;
   }

   bool operator > (const CAliasableResourceStringBase &c) const
   {
      return (m_wsFullResourceName > c.m_wsFullResourceName) ;
   }


   bool IsResourceAnAlias() const 
   {
      if (m_wsFullResourceName.substr(0,3) != CSpdCString(L"\\\\\\")) return false ;
      return true ;
   }

   TResourceType GetResourceType() const
   {
      return m_rtType ;
   }

   virtual TPackageOptionsDesired GetPackageOptionsDesired() const                  // CR.15891.V04; added.
   {
      return m_podResPackageOptions ;
   }

   virtual TValidationOptions GetValidationOptions() const                          // CR.15891.V04; added.
   {
      return m_voResValidationOptions ;
   }

   virtual TRuntimeOptions GetRuntimeOptions() const                                // CR.15891.V04; added.
   {
      return m_roResRuntimeOptions ;
   }

   virtual void SetPackageOptionsDesired(TPackageOptionsDesired pod)                // CR.15891.V04; added.
   {
      m_podResPackageOptions = pod ;
   }

   virtual void SetValidationOptions(TValidationOptions vo)                         // CR.15891.V04; added.
   {
      m_voResValidationOptions = vo ;
   }

   virtual void SetRuntimeOptions(TRuntimeOptions ro)                               // CR.15891.V04; added.
   {
      m_roResRuntimeOptions = ro;
   }

   CSpdCString GetAliasResourceName() const
   {
      return m_wsFullResourceName ;
   }

   void SetAliasResourceName(                                                       // CR.17482; added.
      const CSpdCString &wsNewName)
   {
      m_wsFullResourceName = wsNewName;
   }

   /* GetResourceName() - This method resolves the resource name and returns it. If the value is aliased,
    * then it uses the active AliasedResource manager to retrieve the resourcename. If it is not aliased,
    * then it just returns the current value.
    *
    * SLB 29.mar.2013 CR.15891.V03; created.
   -----------------------------------------------------------------------------------------------------*/
   CSpdCString GetResourceName() const
   {
      if (IsResourceAnAlias())
      {
         CSpdCString wsRes ;
         AliasedResourceIf::IFADTGetResourceName(m_wsFullResourceName, wsRes) ;
         return wsRes ;
      }
      return m_wsFullResourceName ;
   }

} ;

/*
 * Template class: CAliasableResourceString
 *
 * SLB 29.mar.2013 CR.15891.V03; added this comment header.
 */
template <CAliasableResourceStringBase::TResourceType rtVal>
class CAliasableResourceString : 
   public CAliasableResourceStringBase
{
public:
   CAliasableResourceString() : 
      CAliasableResourceStringBase()
   {
      m_rtType = rtVal ;
   }
   CAliasableResourceString(const CSpdCString &scsResourceName) :
      CAliasableResourceStringBase(scsResourceName)
   {
      m_rtType = rtVal ;
   }
} ;


typedef CAliasableResourceString<CAliasableResourceStringBase::rtPlaceHolder> TAliasPlaceHolder ;
typedef CAliasableResourceString<CAliasableResourceStringBase::rtFolderName> TAliasFolderName ;
typedef CAliasableResourceString<CAliasableResourceStringBase::rtFileName> TAliasFileName ;
typedef CAliasableResourceString<CAliasableResourceStringBase::rtPclMetaDriver> TAliasPclMetaDriver ;          // CR.15891.V04; added.
typedef CAliasableResourceString<CAliasableResourceStringBase::rtPclMetaMedia> TAliasPclMetaMedia ;            // CR.15891.V04; added.
typedef CAliasableResourceString<CAliasableResourceStringBase::rtPclMetaOutput> TAliasPclMetaOutput ;          // CR.15891.V04; added.
typedef CAliasableResourceString<CAliasableResourceStringBase::rtAfpdsSharedResource> TAliasAfpdsSharedResource ; // CR.15891.V04; added.
typedef CAliasableResourceString<CAliasableResourceStringBase::rtRje3211Fcb> TAliasRje3211Fcb ;                // CR.15891.V04; added.
typedef CAliasableResourceString<CAliasableResourceStringBase::rtMachineName> TAliasMachineName ;              // CR.15891.V04; added.
typedef CAliasableResourceString<CAliasableResourceStringBase::rtDbsCheckpoint> TAliasDbsCheckpoint ;          // CR.15891.V04; added.
typedef CAliasableResourceString<CAliasableResourceStringBase::rtDbsMonitor> TAliasDbsMonitor ;                // CR.15891.V04; added.

#endif